using System.Linq;
using Microsoft.Maui.Controls.BindingSourceGen;
using Xunit;

namespace BindingSourceGen.UnitTests;

public class BindingCodeWriterTests
{
	[Fact]
	public void BuildsCommonCode()
	{
		var code = BindingCodeWriter.GenerateCommonCode();
		AssertExtensions.CodeIsEqual(
			$$"""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a .NET MAUI source generator.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            #nullable enable

            namespace Microsoft.Maui.Controls.Generated
            {
                {{BindingCodeWriter.GeneratedCodeAttribute}}
                internal static partial class GeneratedBindingInterceptors
                {
                    private static bool ShouldUseSetter(BindingMode mode, BindableProperty bindableProperty)
                        => mode == BindingMode.OneWayToSource
                            || mode == BindingMode.TwoWay
                            || (mode == BindingMode.Default
                                && (bindableProperty.DefaultBindingMode == BindingMode.OneWayToSource
                                    || bindableProperty.DefaultBindingMode == BindingMode.TwoWay));

                    private static bool ShouldUseSetter(BindingMode mode)
                        => mode == BindingMode.OneWayToSource
                            || mode == BindingMode.TwoWay
                            || mode == BindingMode.Default;
                }
            }
            """,
			code);
	}

	[Fact]
	public void BuildsWholeBinding()
	{
		var code = BindingCodeWriter.GenerateBinding(methodName: "SetBinding", binding: new BindingInvocationDescription(
			InterceptableLocation: new InterceptableLocationRecord(Version: 1, Data: "serializedData"),
			SimpleLocation: new SimpleLocation(FilePath: @"Path\To\Program.cs", Line: 20, Column: 30),
			SourceType: new TypeDescription("global::MyNamespace.MySourceClass", IsValueType: false, IsNullable: false, IsGenericParameter: false),
			PropertyType: new TypeDescription("global::MyNamespace.MyPropertyClass", IsValueType: false, IsNullable: false, IsGenericParameter: false),
			Path: new EquatableArray<IPathPart>([
				new MemberAccess("A", MaybeImplementsINPC: true),
				new ConditionalAccess(new MemberAccess("B", MaybeImplementsINPC: true)),
				new ConditionalAccess(new MemberAccess("C", MaybeImplementsINPC: true)),
			]),
			SetterOptions: new(IsWritable: true, AcceptsNullValue: false),
			NullableContextEnabled: true,
			MethodType: InterceptedMethodType.SetBinding));

		AssertExtensions.CodeIsEqual(
			$$"""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a .NET MAUI source generator.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            #nullable enable

            namespace System.Runtime.CompilerServices
            {
                using System;
                using System.Diagnostics;

                {{BindingCodeWriter.GeneratedCodeAttribute}}
                [Conditional("DEBUG")]
                [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
                file sealed class InterceptsLocationAttribute : Attribute
                {
                    public InterceptsLocationAttribute(int version, string data)
                    {
                        _ = version;
                        _ = data;
                    }
                }
            }

            namespace Microsoft.Maui.Controls.Generated
            {
                internal static partial class GeneratedBindingInterceptors
                {
            
                    {{BindingCodeWriter.GeneratedCodeAttribute}}
                    [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, @"serializedData")]
                    public static void SetBinding(
                        this global::Microsoft.Maui.Controls.BindableObject bindableObject,
                        global::Microsoft.Maui.Controls.BindableProperty bindableProperty,
                        global::System.Func<global::MyNamespace.MySourceClass, global::MyNamespace.MyPropertyClass> getter,
                        global::Microsoft.Maui.Controls.BindingMode mode = global::Microsoft.Maui.Controls.BindingMode.Default,
                        global::Microsoft.Maui.Controls.IValueConverter? converter = null,
                        object? converterParameter = null,
                        string? stringFormat = null,
                        object? source = null,
                        object? fallbackValue = null,
                        object? targetNullValue = null)
                    {
                        global::System.Action<global::MyNamespace.MySourceClass, global::MyNamespace.MyPropertyClass>? setter = null;
                        if (ShouldUseSetter(mode, bindableProperty))
                        {
                            setter = static (source, value) => 
                            {
                                if (source.A is {} p0
                                    && p0.B is {} p1)
                                {
                                    p1.C = value;
                                }
                            };
                        }

                        static global::System.Collections.Generic.IEnumerable<global::System.ValueTuple<global::System.ComponentModel.INotifyPropertyChanged?, string>> GetHandlers(global::MyNamespace.MySourceClass source)
                        {
                            if (source is global::System.ComponentModel.INotifyPropertyChanged p0) yield return (p0, "A");
                            var p1 = source.A;
                            if (p1 is global::System.ComponentModel.INotifyPropertyChanged p2) yield return (p2, "B");
                            var p3 = p1?.B;
                            if (p3 is global::System.ComponentModel.INotifyPropertyChanged p4) yield return (p4, "C");
                        }

                        var binding = new global::Microsoft.Maui.Controls.Internals.TypedBinding<global::MyNamespace.MySourceClass, global::MyNamespace.MyPropertyClass>(
                            getter: source => (getter(source), true),
                            setter,
                            handlersCount: 3,
                            GetHandlers)
                        {
                            Mode = mode,
                            Converter = converter,
                            ConverterParameter = converterParameter,
                            StringFormat = stringFormat,
                            Source = source,
                            FallbackValue = fallbackValue,
                            TargetNullValue = targetNullValue,
                        };

                        bindableObject.SetBinding(bindableProperty, binding);
                    }
                }
            }
            """,
			code);
	}

	[Fact]
	public void CorrectlyFormatsSimpleBinding()
	{
		var codeBuilder = new BindingCodeWriter.BindingInterceptorCodeBuilder();
		codeBuilder.AppendBindingFactoryMethod(methodName: "SetBinding", binding: new BindingInvocationDescription(
			InterceptableLocation: new InterceptableLocationRecord(Version: 1, Data: "serializedData"),
			SimpleLocation: new SimpleLocation(FilePath: @"Path\To\Program.cs", Line: 20, Column: 30), SourceType: new TypeDescription("global::MyNamespace.MySourceClass", IsValueType: false, IsNullable: false, IsGenericParameter: false),
			PropertyType: new TypeDescription("global::MyNamespace.MyPropertyClass", IsValueType: false, IsNullable: false, IsGenericParameter: false),
			Path: new EquatableArray<IPathPart>([
				new MemberAccess("A", MaybeImplementsINPC: true),
				new ConditionalAccess(new MemberAccess("B", MaybeImplementsINPC: true)),
				new ConditionalAccess(new MemberAccess("C", MaybeImplementsINPC: true)),
			]),
			SetterOptions: new(IsWritable: true, AcceptsNullValue: false),
			NullableContextEnabled: true,
			MethodType: InterceptedMethodType.SetBinding));

		var code = codeBuilder.ToString();
		AssertExtensions.CodeIsEqual(
			$$"""
            {{BindingCodeWriter.GeneratedCodeAttribute}}
            [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, @"serializedData")]
            public static void SetBinding(
                this global::Microsoft.Maui.Controls.BindableObject bindableObject,
                global::Microsoft.Maui.Controls.BindableProperty bindableProperty,
                global::System.Func<global::MyNamespace.MySourceClass, global::MyNamespace.MyPropertyClass> getter,
                global::Microsoft.Maui.Controls.BindingMode mode = global::Microsoft.Maui.Controls.BindingMode.Default,
                global::Microsoft.Maui.Controls.IValueConverter? converter = null,
                object? converterParameter = null,
                string? stringFormat = null,
                object? source = null,
                object? fallbackValue = null,
                object? targetNullValue = null)
            {
                global::System.Action<global::MyNamespace.MySourceClass, global::MyNamespace.MyPropertyClass>? setter = null;
                if (ShouldUseSetter(mode, bindableProperty))
                {
                    setter = static (source, value) => 
                    {
                        if (source.A is {} p0
                            && p0.B is {} p1)
                        {
                            p1.C = value;
                        }
                    };
                }

                static global::System.Collections.Generic.IEnumerable<global::System.ValueTuple<global::System.ComponentModel.INotifyPropertyChanged?, string>> GetHandlers(global::MyNamespace.MySourceClass source)
                {
                    if (source is global::System.ComponentModel.INotifyPropertyChanged p0) yield return (p0, "A");
                    var p1 = source.A;
                    if (p1 is global::System.ComponentModel.INotifyPropertyChanged p2) yield return (p2, "B");
                    var p3 = p1?.B;
                    if (p3 is global::System.ComponentModel.INotifyPropertyChanged p4) yield return (p4, "C");
                }

                var binding = new global::Microsoft.Maui.Controls.Internals.TypedBinding<global::MyNamespace.MySourceClass, global::MyNamespace.MyPropertyClass>(
                    getter: source => (getter(source), true),
                    setter,
                    handlersCount: 3,
                    GetHandlers)
                {
                    Mode = mode,
                    Converter = converter,
                    ConverterParameter = converterParameter,
                    StringFormat = stringFormat,
                    Source = source,
                    FallbackValue = fallbackValue,
                    TargetNullValue = targetNullValue,
                };

                bindableObject.SetBinding(bindableProperty, binding);
            }
            """,
			code);
	}

	[Fact]
	public void CorrectlyFormatsBindingWithoutAnyNullablesInPath()
	{
		var codeBuilder = new BindingCodeWriter.BindingInterceptorCodeBuilder();
		codeBuilder.AppendBindingFactoryMethod(methodName: "SetBinding", binding: new BindingInvocationDescription(
			InterceptableLocation: new InterceptableLocationRecord(Version: 1, Data: "serializedData"),
			SimpleLocation: new SimpleLocation(FilePath: @"Path\To\Program.cs", Line: 20, Column: 30), SourceType: new TypeDescription("global::MyNamespace.MySourceClass", IsValueType: false, IsNullable: false, IsGenericParameter: false),
			PropertyType: new TypeDescription("global::MyNamespace.MyPropertyClass", IsValueType: false, IsNullable: false, IsGenericParameter: false),
			Path: new EquatableArray<IPathPart>([
				new MemberAccess("A", MaybeImplementsINPC: true),
				new MemberAccess("B", MaybeImplementsINPC: true),
				new MemberAccess("C", MaybeImplementsINPC: true),
			]),
			SetterOptions: new(IsWritable: true, AcceptsNullValue: false),
			NullableContextEnabled: true,
			MethodType: InterceptedMethodType.SetBinding));

		var code = codeBuilder.ToString();
		AssertExtensions.CodeIsEqual(
			$$"""
            {{BindingCodeWriter.GeneratedCodeAttribute}}
            [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, @"serializedData")]
            public static void SetBinding(
                this global::Microsoft.Maui.Controls.BindableObject bindableObject,
                global::Microsoft.Maui.Controls.BindableProperty bindableProperty,
                global::System.Func<global::MyNamespace.MySourceClass, global::MyNamespace.MyPropertyClass> getter,
                global::Microsoft.Maui.Controls.BindingMode mode = global::Microsoft.Maui.Controls.BindingMode.Default,
                global::Microsoft.Maui.Controls.IValueConverter? converter = null,
                object? converterParameter = null,
                string? stringFormat = null,
                object? source = null,
                object? fallbackValue = null,
                object? targetNullValue = null)
            {
                global::System.Action<global::MyNamespace.MySourceClass, global::MyNamespace.MyPropertyClass>? setter = null;
                if (ShouldUseSetter(mode, bindableProperty))
                {
                    setter = static (source, value) => 
                    {
                        source.A.B.C = value;
                    };
                }

                static global::System.Collections.Generic.IEnumerable<global::System.ValueTuple<global::System.ComponentModel.INotifyPropertyChanged?, string>> GetHandlers(global::MyNamespace.MySourceClass source)
                {
                    if (source is global::System.ComponentModel.INotifyPropertyChanged p0) yield return (p0, "A");
                    var p1 = source.A;
                    if (p1 is global::System.ComponentModel.INotifyPropertyChanged p2) yield return (p2, "B");
                    var p3 = p1.B;
                    if (p3 is global::System.ComponentModel.INotifyPropertyChanged p4) yield return (p4, "C");
                }

                var binding = new global::Microsoft.Maui.Controls.Internals.TypedBinding<global::MyNamespace.MySourceClass, global::MyNamespace.MyPropertyClass>(
                    getter: source => (getter(source), true),
                    setter,
                    handlersCount: 3,
                    GetHandlers)
                {
                    Mode = mode,
                    Converter = converter,
                    ConverterParameter = converterParameter,
                    StringFormat = stringFormat,
                    Source = source,
                    FallbackValue = fallbackValue,
                    TargetNullValue = targetNullValue,
                };

                bindableObject.SetBinding(bindableProperty, binding);
            }
            """,
			code);
	}

	[Fact]
	public void CorrectlyFormatsBindingWithoutSetter()
	{
		var codeBuilder = new BindingCodeWriter.BindingInterceptorCodeBuilder();
		codeBuilder.AppendBindingFactoryMethod(methodName: "SetBinding", binding: new BindingInvocationDescription(
			InterceptableLocation: new InterceptableLocationRecord(Version: 1, Data: "serializedData"),
			SimpleLocation: new SimpleLocation(FilePath: @"Path\To\Program.cs", Line: 20, Column: 30), SourceType: new TypeDescription("global::MyNamespace.MySourceClass", IsNullable: false, IsGenericParameter: false, IsValueType: false),
			PropertyType: new TypeDescription("global::MyNamespace.MyPropertyClass", IsNullable: false, IsGenericParameter: false, IsValueType: false),
			Path: new EquatableArray<IPathPart>([
				new MemberAccess("A", MaybeImplementsINPC: true),
				new MemberAccess("B", MaybeImplementsINPC: true),
				new MemberAccess("C", MaybeImplementsINPC: true),
			]),
			SetterOptions: new(IsWritable: false),
			NullableContextEnabled: true,
			MethodType: InterceptedMethodType.SetBinding));

		var code = codeBuilder.ToString();
		AssertExtensions.CodeIsEqual(
			$$"""
            {{BindingCodeWriter.GeneratedCodeAttribute}}
            [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, @"serializedData")]
            public static void SetBinding(
                this global::Microsoft.Maui.Controls.BindableObject bindableObject,
                global::Microsoft.Maui.Controls.BindableProperty bindableProperty,
                global::System.Func<global::MyNamespace.MySourceClass, global::MyNamespace.MyPropertyClass> getter,
                global::Microsoft.Maui.Controls.BindingMode mode = global::Microsoft.Maui.Controls.BindingMode.Default,
                global::Microsoft.Maui.Controls.IValueConverter? converter = null,
                object? converterParameter = null,
                string? stringFormat = null,
                object? source = null,
                object? fallbackValue = null,
                object? targetNullValue = null)
            {
                global::System.Action<global::MyNamespace.MySourceClass, global::MyNamespace.MyPropertyClass>? setter = null;
                if (ShouldUseSetter(mode, bindableProperty))
                {
                    setter = static (source, value) =>
                    {
                        throw new global::System.InvalidOperationException("Cannot set value on the source object.");
                    };
                }

                static global::System.Collections.Generic.IEnumerable<global::System.ValueTuple<global::System.ComponentModel.INotifyPropertyChanged?, string>> GetHandlers(global::MyNamespace.MySourceClass source)
                {
                    if (source is global::System.ComponentModel.INotifyPropertyChanged p0) yield return (p0, "A");
                    var p1 = source.A;
                    if (p1 is global::System.ComponentModel.INotifyPropertyChanged p2) yield return (p2, "B");
                    var p3 = p1.B;
                    if (p3 is global::System.ComponentModel.INotifyPropertyChanged p4) yield return (p4, "C");
                }

                var binding = new global::Microsoft.Maui.Controls.Internals.TypedBinding<global::MyNamespace.MySourceClass, global::MyNamespace.MyPropertyClass>(
                    getter: source => (getter(source), true),
                    setter,
                    handlersCount: 3,
                    GetHandlers)
                {
                    Mode = mode,
                    Converter = converter,
                    ConverterParameter = converterParameter,
                    StringFormat = stringFormat,
                    Source = source,
                    FallbackValue = fallbackValue,
                    TargetNullValue = targetNullValue,
                };

                bindableObject.SetBinding(bindableProperty, binding);
            }
            """,
			code);
	}

	[Fact]
	public void CorrectlyFormatsBindingWithIndexers()
	{
		var codeBuilder = new BindingCodeWriter.BindingInterceptorCodeBuilder();
		codeBuilder.AppendBindingFactoryMethod(methodName: "SetBinding", binding: new BindingInvocationDescription(
			InterceptableLocation: new InterceptableLocationRecord(Version: 1, Data: "serializedData"),
			SimpleLocation: new SimpleLocation(FilePath: @"Path\To\Program.cs", Line: 20, Column: 30), SourceType: new TypeDescription("global::MyNamespace.MySourceClass", IsNullable: false, IsGenericParameter: false),
			PropertyType: new TypeDescription("global::MyNamespace.MyPropertyClass", IsNullable: true, IsGenericParameter: false),
			Path: new EquatableArray<IPathPart>([
				new IndexAccess("Item", 12, MaybeImplementsINPC: true),
				new ConditionalAccess(new IndexAccess("Indexer", "Abc", MaybeImplementsINPC: true)),
				new IndexAccess("Item", 0, MaybeImplementsINPC: true),
			]),
			SetterOptions: new(IsWritable: true, AcceptsNullValue: false),
			NullableContextEnabled: true,
			MethodType: InterceptedMethodType.SetBinding));

		var code = codeBuilder.ToString();
		AssertExtensions.CodeIsEqual(
			$$"""
            {{BindingCodeWriter.GeneratedCodeAttribute}}
            [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, @"serializedData")]
            public static void SetBinding(
                this global::Microsoft.Maui.Controls.BindableObject bindableObject,
                global::Microsoft.Maui.Controls.BindableProperty bindableProperty,
                global::System.Func<global::MyNamespace.MySourceClass, global::MyNamespace.MyPropertyClass?> getter,
                global::Microsoft.Maui.Controls.BindingMode mode = global::Microsoft.Maui.Controls.BindingMode.Default,
                global::Microsoft.Maui.Controls.IValueConverter? converter = null,
                object? converterParameter = null,
                string? stringFormat = null,
                object? source = null,
                object? fallbackValue = null,
                object? targetNullValue = null)
            {
                global::System.Action<global::MyNamespace.MySourceClass, global::MyNamespace.MyPropertyClass?>? setter = null;
                if (ShouldUseSetter(mode, bindableProperty))
                {
                    setter = static (source, value) => 
                    {
                        if (value is null)
                        {
                            return;
                        }
                        
                        if (source[12] is {} p0)
                        {
                            p0["Abc"][0] = value;
                        }
                    };
                }

                static global::System.Collections.Generic.IEnumerable<global::System.ValueTuple<global::System.ComponentModel.INotifyPropertyChanged?, string>> GetHandlers(global::MyNamespace.MySourceClass source)
                {
                    if (source is global::System.ComponentModel.INotifyPropertyChanged p0) yield return (p0, "Item");
                    if (source is global::System.ComponentModel.INotifyPropertyChanged p1) yield return (p1, "Item[12]");
                    var p2 = source[12];
                    if (p2 is global::System.ComponentModel.INotifyPropertyChanged p3) yield return (p3, "Indexer");
                    if (p2 is global::System.ComponentModel.INotifyPropertyChanged p4) yield return (p4, "Indexer[Abc]");
                    var p5 = p2?["Abc"];
                    if (p5 is global::System.ComponentModel.INotifyPropertyChanged p6) yield return (p6, "Item");
                    if (p5 is global::System.ComponentModel.INotifyPropertyChanged p7) yield return (p7, "Item[0]");
                }

                var binding = new global::Microsoft.Maui.Controls.Internals.TypedBinding<global::MyNamespace.MySourceClass, global::MyNamespace.MyPropertyClass?>(
                    getter: source => (getter(source), true),
                    setter,
                    handlersCount: 6,
                    GetHandlers)
                {
                    Mode = mode,
                    Converter = converter,
                    ConverterParameter = converterParameter,
                    StringFormat = stringFormat,
                    Source = source,
                    FallbackValue = fallbackValue,
                    TargetNullValue = targetNullValue,
                };

                bindableObject.SetBinding(bindableProperty, binding);
            }
            """,
			code);
	}

	[Fact]
	public void CorrectlyFormatsBindingWithCasts()
	{
		var codeBuilder = new BindingCodeWriter.BindingInterceptorCodeBuilder();
		codeBuilder.AppendBindingFactoryMethod(methodName: "SetBinding", binding: new BindingInvocationDescription(
			InterceptableLocation: new InterceptableLocationRecord(Version: 1, Data: "serializedData"),
			SimpleLocation: new SimpleLocation(FilePath: @"Path\To\Program.cs", Line: 20, Column: 30), SourceType: new TypeDescription("global::MyNamespace.MySourceClass", IsNullable: false, IsGenericParameter: false),
			PropertyType: new TypeDescription("global::MyNamespace.MyPropertyClass", IsNullable: false, IsGenericParameter: false),
			Path: new EquatableArray<IPathPart>([
				new MemberAccess("A", MaybeImplementsINPC: true),
				new Cast(new TypeDescription("X", IsValueType: false, IsNullable: false, IsGenericParameter: false)),
				new ConditionalAccess(new MemberAccess("B", MaybeImplementsINPC: true)),
				new Cast(new TypeDescription("Y", IsValueType: false, IsNullable: false, IsGenericParameter: false)),
				new ConditionalAccess(new MemberAccess("C", MaybeImplementsINPC: true)),
				new Cast(new TypeDescription("Z", IsValueType: true, IsNullable: true, IsGenericParameter: false)),
				new ConditionalAccess(new MemberAccess("D", MaybeImplementsINPC: true)),
			]),
			SetterOptions: new(IsWritable: true, AcceptsNullValue: false),
			NullableContextEnabled: true,
			MethodType: InterceptedMethodType.SetBinding));

		var code = codeBuilder.ToString();

		AssertExtensions.CodeIsEqual(
			$$"""
            {{BindingCodeWriter.GeneratedCodeAttribute}}
            [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, @"serializedData")]
            public static void SetBinding(
                this global::Microsoft.Maui.Controls.BindableObject bindableObject,
                global::Microsoft.Maui.Controls.BindableProperty bindableProperty,
                global::System.Func<global::MyNamespace.MySourceClass, global::MyNamespace.MyPropertyClass> getter,
                global::Microsoft.Maui.Controls.BindingMode mode = global::Microsoft.Maui.Controls.BindingMode.Default,
                global::Microsoft.Maui.Controls.IValueConverter? converter = null,
                object? converterParameter = null,
                string? stringFormat = null,
                object? source = null,
                object? fallbackValue = null,
                object? targetNullValue = null)
            {
                global::System.Action<global::MyNamespace.MySourceClass, global::MyNamespace.MyPropertyClass>? setter = null;
                if (ShouldUseSetter(mode, bindableProperty))
                {
                    setter = static (source, value) => 
                    {
                        if (source.A is X p0
                            && p0.B is Y p1
                            && p1.C is Z p2)
                        {
                            p2.D = value;
                        }
                    };
                }

                static global::System.Collections.Generic.IEnumerable<global::System.ValueTuple<global::System.ComponentModel.INotifyPropertyChanged?, string>> GetHandlers(global::MyNamespace.MySourceClass source)
                {
                    if (source is global::System.ComponentModel.INotifyPropertyChanged p0) yield return (p0, "A");
                    var p1 = source.A;
                    var p2 = (p1 as X);
                    if (p2 is global::System.ComponentModel.INotifyPropertyChanged p3) yield return (p3, "B");
                    var p4 = p2?.B;
                    var p5 = (p4 as Y);
                    if (p5 is global::System.ComponentModel.INotifyPropertyChanged p6) yield return (p6, "C");
                    var p7 = p5?.C;
                    var p8 = (p7 as Z?);
                    if (p8 is global::System.ComponentModel.INotifyPropertyChanged p9) yield return (p9, "D");
                }

                var binding = new global::Microsoft.Maui.Controls.Internals.TypedBinding<global::MyNamespace.MySourceClass, global::MyNamespace.MyPropertyClass>(
                    getter: source => (getter(source), true),
                    setter,
                    handlersCount: 4,
                    GetHandlers)
                {
                    Mode = mode,
                    Converter = converter,
                    ConverterParameter = converterParameter,
                    StringFormat = stringFormat,
                    Source = source,
                    FallbackValue = fallbackValue,
                    TargetNullValue = targetNullValue,
                };

                bindableObject.SetBinding(bindableProperty, binding);
            }
            """,
			code);
	}
}
