using System.Linq;
using Microsoft.Maui.Controls.BindingSourceGen;
using Xunit;

namespace BindingSourceGen.UnitTests;

/// <summary>
/// Demonstrates migrating existing tests to use SnapshotAssert.
/// These tests are duplicates of tests in BindingCodeWriterTests.cs, but using the new SnapshotAssert utility.
/// </summary>
public class BindingCodeWriterTestsWithSnapshotAssert
{
	[Fact]
	public void BuildsCommonCode_UsingSnapshotAssert()
	{
		var code = BindingCodeWriter.GenerateCommonCode();
		
		// Using SnapshotAssert instead of AssertExtensions.CodeIsEqual
		// This provides better diff output and is more resilient to whitespace changes
		SnapshotAssert.Equal(
			$$"""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a .NET MAUI source generator.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            #nullable enable

            namespace Microsoft.Maui.Controls.Generated
            {
                {{BindingCodeWriter.GeneratedCodeAttribute}}
                internal static partial class GeneratedBindingInterceptors
                {
                    private static bool ShouldUseSetter(BindingMode mode, BindableProperty bindableProperty)
                        => mode == BindingMode.OneWayToSource
                            || mode == BindingMode.TwoWay
                            || (mode == BindingMode.Default
                                && (bindableProperty.DefaultBindingMode == BindingMode.OneWayToSource
                                    || bindableProperty.DefaultBindingMode == BindingMode.TwoWay));

                    private static bool ShouldUseSetter(BindingMode mode)
                        => mode == BindingMode.OneWayToSource
                            || mode == BindingMode.TwoWay
                            || mode == BindingMode.Default;
                }
            }
            """,
			code);
	}

	[Fact]
	public void CorrectlyFormatsSimpleBinding_UsingSnapshotAssert()
	{
		var codeBuilder = new BindingCodeWriter.BindingInterceptorCodeBuilder();
		codeBuilder.AppendBindingFactoryMethod(methodName: "SetBinding", binding: new BindingInvocationDescription(
			InterceptableLocation: new InterceptableLocationRecord(Version: 1, Data: "serializedData"),
			SimpleLocation: new SimpleLocation(FilePath: @"Path\To\Program.cs", Line: 20, Column: 30), 
			SourceType: new TypeDescription("global::MyNamespace.MySourceClass", IsValueType: false, IsNullable: false, IsGenericParameter: false),
			PropertyType: new TypeDescription("global::MyNamespace.MyPropertyClass", IsValueType: false, IsNullable: false, IsGenericParameter: false),
			Path: new EquatableArray<IPathPart>([
				new MemberAccess("A"),
				new ConditionalAccess(new MemberAccess("B")),
				new ConditionalAccess(new MemberAccess("C")),
			]),
			SetterOptions: new(IsWritable: true, AcceptsNullValue: false),
			NullableContextEnabled: true,
			MethodType: InterceptedMethodType.SetBinding));

		var code = codeBuilder.ToString();
		
		// Using SnapshotAssert for cleaner comparison
		SnapshotAssert.Equal(
			$$"""
            {{BindingCodeWriter.GeneratedCodeAttribute}}
            [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, @"serializedData")]
            public static void SetBinding(
                this global::Microsoft.Maui.Controls.BindableObject bindableObject,
                global::Microsoft.Maui.Controls.BindableProperty bindableProperty,
                global::System.Func<global::MyNamespace.MySourceClass, global::MyNamespace.MyPropertyClass> getter,
                global::Microsoft.Maui.Controls.BindingMode mode = global::Microsoft.Maui.Controls.BindingMode.Default,
                global::Microsoft.Maui.Controls.IValueConverter? converter = null,
                object? converterParameter = null,
                string? stringFormat = null,
                object? source = null,
                object? fallbackValue = null,
                object? targetNullValue = null)
            {
                global::System.Action<global::MyNamespace.MySourceClass, global::MyNamespace.MyPropertyClass>? setter = null;
                if (ShouldUseSetter(mode, bindableProperty))
                {
                    setter = static (source, value) => 
                    {
                        if (source.A is {} p0
                            && p0.B is {} p1)
                        {
                            p1.C = value;
                        }
                    };
                }

                var binding = new global::Microsoft.Maui.Controls.Internals.TypedBinding<global::MyNamespace.MySourceClass, global::MyNamespace.MyPropertyClass>(
                    getter: source => (getter(source), true),
                    setter,
                    handlers: new global::System.Tuple<global::System.Func<global::MyNamespace.MySourceClass, object?>, string>[]
                    {
                        new(static source => source, "A"),
                        new(static source => source.A, "B"),
                        new(static source => source.A?.B, "C"),
                    })
                    {
                    	Mode = mode,
                    	Converter = converter,
                    	ConverterParameter = converterParameter,
                    	StringFormat = stringFormat,
                    	Source = source,
                    	FallbackValue = fallbackValue,
                    	TargetNullValue = targetNullValue,
                    };

                bindableObject.SetBinding(bindableProperty, binding);
            }
            """,
			code);
	}
}
