<Project>
  <Target Name="_MauiPrepareForILLink" BeforeTargets="PrepareForILLink;_GenerateRuntimeConfigurationFilesInputCache;XamlC">
    <PropertyGroup Condition="'$(PublishAot)' == 'true' or '$(TrimMode)' == 'full'">
      <MauiHybridWebViewSupported>false</MauiHybridWebViewSupported>
    </PropertyGroup>
    <ItemGroup>
      <RuntimeHostConfigurationOption Include="Microsoft.Maui.RuntimeFeature.IsHybridWebViewSupported"
                                      Condition="'$(MauiHybridWebViewSupported)' != ''"
                                      Value="$(MauiHybridWebViewSupported)"
                                      Trim="true" />
    </ItemGroup>
  </Target>
</Project>
