#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Posts or updates the Copilot evaluate-pr-tests comment on a PR.

.DESCRIPTION
    Idempotent comment management: finds an existing bot comment with the
    evaluation marker and updates it, or creates a new one if none exists.
    This prevents comment spam on repeated runs.

.PARAMETER PrNumber
    The PR number to comment on.

.PARAMETER EvaluateResult
    The result of the evaluate job: 'success', 'failure', 'cancelled', 'skipped'.

.PARAMETER OutputFile
    Path to the Copilot CLI output text file.

.PARAMETER RunUrl
    URL to the GitHub Actions workflow run.
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$PrNumber,

    [Parameter(Mandatory = $true)]
    [string]$EvaluateResult,

    [Parameter(Mandatory = $false)]
    [string]$OutputFile = "",

    [Parameter(Mandatory = $true)]
    [string]$RunUrl
)

$ErrorActionPreference = "Stop"

# Marker used to identify our comment for idempotent updates
$CommentMarker = "<!-- copilot-evaluate-tests -->"

# Build comment body
if ($EvaluateResult -eq "success" -and $OutputFile -and (Test-Path $OutputFile)) {
    $content = Get-Content -Path $OutputFile -Raw -ErrorAction SilentlyContinue
    if ($content -and $content.Trim().Length -gt 0) {
        # Truncate if over 60k chars (GitHub comment limit is 65536)
        if ($content.Length -gt 60000) {
            $content = $content.Substring(0, 60000) + "`n`n> ⚠️ Output truncated (exceeded 60k character limit)"
        }
        $body = @"
$CommentMarker
<details>
<summary>🤖 AI Test Evaluation</summary>

$content

---
<sub>Generated by [Copilot CLI evaluate-pr-tests]($RunUrl) · $(Get-Date -Format "yyyy-MM-dd HH:mm") UTC</sub>
</details>
"@
    }
    else {
        $body = @"
$CommentMarker
<details>
<summary>🤖 AI Test Evaluation</summary>

⚠️ Copilot CLI completed but produced no output.

[View workflow run]($RunUrl)

---
<sub>Generated by Copilot CLI evaluate-pr-tests · $(Get-Date -Format "yyyy-MM-dd HH:mm") UTC</sub>
</details>
"@
    }
}
elseif ($EvaluateResult -eq "failure") {
    $body = @"
$CommentMarker
<details>
<summary>🤖 AI Test Evaluation</summary>

❌ Evaluation failed. [View workflow run]($RunUrl)

---
<sub>Generated by Copilot CLI evaluate-pr-tests · $(Get-Date -Format "yyyy-MM-dd HH:mm") UTC</sub>
</details>
"@
}
elseif ($EvaluateResult -eq "cancelled") {
    $body = @"
$CommentMarker
<details>
<summary>🤖 AI Test Evaluation</summary>

⏹️ Evaluation was cancelled. [View workflow run]($RunUrl)

---
<sub>Generated by Copilot CLI evaluate-pr-tests · $(Get-Date -Format "yyyy-MM-dd HH:mm") UTC</sub>
</details>
"@
}
else {
    $body = @"
$CommentMarker
<details>
<summary>🤖 AI Test Evaluation</summary>

⚠️ Evaluation did not complete (status: $EvaluateResult). [View workflow run]($RunUrl)

---
<sub>Generated by Copilot CLI evaluate-pr-tests · $(Get-Date -Format "yyyy-MM-dd HH:mm") UTC</sub>
</details>
"@
}

# Find existing comment with our marker
Write-Host "🔍 Searching for existing evaluation comment on PR #$PrNumber..."

$existingCommentId = $null
try {
    $comments = gh api "repos/$($env:GITHUB_REPOSITORY)/issues/$PrNumber/comments" `
        --jq ".[] | select(.body | contains(`"$CommentMarker`")) | .id" 2>$null

    if ($comments) {
        # Take the first match
        $existingCommentId = ($comments -split "`n" | Select-Object -First 1).Trim()
    }
}
catch {
    Write-Host "⚠️ Could not search for existing comments: $_"
}

# Write body to temp file for the API call (avoids shell escaping issues)
$bodyFile = [System.IO.Path]::GetTempFileName()
Set-Content -Path $bodyFile -Value $body -NoNewline

if ($existingCommentId -and $existingCommentId -ne "null") {
    Write-Host "📝 Updating existing comment $existingCommentId on PR #$PrNumber..."
    gh api "repos/$($env:GITHUB_REPOSITORY)/issues/comments/$existingCommentId" `
        -X PATCH -F "body=@$bodyFile"
}
else {
    Write-Host "💬 Creating new comment on PR #$PrNumber..."
    gh api "repos/$($env:GITHUB_REPOSITORY)/issues/$PrNumber/comments" `
        -X POST -F "body=@$bodyFile"
}

Remove-Item -Path $bodyFile -Force -ErrorAction SilentlyContinue
Write-Host "✅ Comment posted successfully"
