using System;
using System.CodeDom.Compiler;
using System.Globalization;
using System.IO;
using System.Runtime.InteropServices;
using Microsoft.CodeAnalysis;

namespace Microsoft.Maui.Controls.SourceGen;

/// <summary>
/// Generates a <c>[MetadataUpdateHandler]</c> partial class for a XAML page type.
/// The generated class is invoked by the .NET hot reload infrastructure after
/// <c>MetadataUpdater.ApplyUpdate</c> patches in an <c>UpdateComponent_vNtoM()</c> method.
/// It enumerates all live page instances via <see cref="XamlComponentRegistry"/>
/// and calls the right <c>UpdateComponent</c> method based on each instance's <c>__version</c> field.
/// </summary>
static class MetadataUpdateHandlerCodeWriter
{
	static readonly string NewLine = RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? "\r\n" : "\n";

	/// <summary>
	/// Generates the source for a <c>[MetadataUpdateHandler]</c> class for the given XAML page type.
	/// </summary>
	/// <param name="rootType">The page/view type (e.g. <c>MyNamespace.MyPage</c>).</param>
	/// <param name="generatedCodeAttr">The <c>[GeneratedCode]</c> attribute string from the IC writer.</param>
	/// <returns>Source text for a <c>*.handler.xsg.cs</c> file.</returns>
	public static string GenerateHandler(INamedTypeSymbol rootType, string generatedCodeAttr)
	{
		if (rootType is null)
			throw new ArgumentNullException(nameof(rootType));

		var ns = rootType.ContainingNamespace.IsGlobalNamespace
			? null
			: rootType.ContainingNamespace.ToString();
		var typeName = rootType.Name;
		var fqTypeName = rootType.ToFQDisplayString();
		var handlerClassName = $"{typeName}_XamlHotReloadHandler";

		using var writer = new IndentedTextWriter(new StringWriter(CultureInfo.InvariantCulture), "\t") { NewLine = NewLine };

		writer.WriteLine(GeneratorHelpers.AutoGeneratedHeaderText);
		writer.WriteLine("#nullable enable");
		writer.WriteLine();

		// Assembly-level MetadataUpdateHandler attribute
		if (ns != null)
			writer.WriteLine($"[assembly: global::System.Reflection.Metadata.MetadataUpdateHandler(typeof(global::{ns}.{handlerClassName}))]");
		else
			writer.WriteLine($"[assembly: global::System.Reflection.Metadata.MetadataUpdateHandler(typeof(global::{handlerClassName}))]");

		writer.WriteLine();

		// Open namespace (if any)
		bool hasNs = ns != null;
		if (hasNs)
		{
			writer.WriteLine($"namespace {ns}");
			writer.WriteLine("{");
			writer.Indent++;
		}

		writer.WriteLine(generatedCodeAttr);
		writer.WriteLine($"internal static class {handlerClassName}");
		writer.WriteLine("{");
		writer.Indent++;

		// Cache the __version FieldInfo at class initialisation to avoid repeated reflection
		writer.WriteLine($"static readonly global::System.Reflection.FieldInfo? s_versionField =");
		writer.Indent++;
		writer.WriteLine($"typeof({fqTypeName}).GetField(");
		writer.Indent++;
		writer.WriteLine("\"__version\",");
		writer.WriteLine("global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance);");
		writer.Indent--;
		writer.Indent--;
		writer.WriteLine();

		// ClearCache — required by MetadataUpdateHandler protocol; nothing to clear here
		writer.WriteLine("/// <summary>Called before a hot reload is applied. Nothing to clear for XAML components.</summary>");
		writer.WriteLine("public static void ClearCache(global::System.Type[]? _) { }");
		writer.WriteLine();

		// UpdateApplication — finds live instances and dispatches UpdateComponent
		writer.WriteLine("/// <summary>");
		writer.WriteLine("/// Called after <c>MetadataUpdater.ApplyUpdate</c> to push property changes to live instances.");
		writer.WriteLine("/// </summary>");
		writer.WriteLine("public static void UpdateApplication(global::System.Type[]? updatedTypes)");
		writer.WriteLine("{");
		writer.Indent++;

		writer.WriteLine("if (updatedTypes is null || s_versionField is null)");
		writer.Indent++;
		writer.WriteLine("return;");
		writer.Indent--;
		writer.WriteLine($"foreach (var t in updatedTypes)");
		writer.WriteLine("{");
		writer.Indent++;
		writer.WriteLine($"if (t != typeof({fqTypeName}))");
		writer.Indent++;
		writer.WriteLine("continue;");
		writer.Indent--;
		writer.WriteLine($"foreach (var instance in global::Microsoft.Maui.Controls.Xaml.XamlComponentRegistry.GetInstances(t))");
		writer.WriteLine("{");
		writer.Indent++;
		writer.WriteLine("var v = (int)(s_versionField.GetValue(instance) ?? 0);");
		writer.WriteLine("var methodName = string.Concat(\"UpdateComponent_v\", v.ToString(global::System.Globalization.CultureInfo.InvariantCulture), \"to\", (v + 1).ToString(global::System.Globalization.CultureInfo.InvariantCulture));");
		writer.WriteLine("var method = t.GetMethod(");
		writer.Indent++;
		writer.WriteLine("methodName,");
		writer.WriteLine("global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance);");
		writer.Indent--;
		writer.WriteLine("method?.Invoke(instance, null);");
		writer.Indent--;
		writer.WriteLine("}");
		writer.Indent--;
		writer.WriteLine("}");
		writer.Indent--;
		writer.WriteLine("}");

		writer.Indent--;
		writer.WriteLine("}");

		if (hasNs)
		{
			writer.Indent--;
			writer.WriteLine("}");
		}

		return ((StringWriter)writer.InnerWriter).ToString();
	}
}
