using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Runtime.InteropServices;
using Microsoft.CodeAnalysis;
using Microsoft.Maui.Controls.Xaml;

namespace Microsoft.Maui.Controls.SourceGen;

/// <summary>
/// Generates a single <c>UpdateComponent()</c> partial method containing accumulated
/// <c>if (__version == N)</c> patch blocks from successive XAML Hot Reload edits.
/// </summary>
/// <remarks>
/// <para>
/// Per the spec, the generated method chains sequential <c>if</c> blocks (not <c>else if</c>):
/// <code>
/// internal void UpdateComponent()
/// {
///     if (__version == 0) { /* v0→v1 patch */ __version = 1; }
///     if (__version == 1) { /* v1→v2 patch */ __version = 2; }
/// }
/// </code>
/// A v0 instance chains through ALL patches; a fresh instance (whose <c>InitializeComponent</c>
/// sets <c>__version</c> to the latest) skips them all.
/// </para>
/// <para>
/// Property value encoding strategy (in priority order):
/// <list type="bullet">
/// <item><c>string</c> — direct string literal.</item>
/// <item><c>bool</c> — <c>true</c> / <c>false</c> literal.</item>
/// <item><c>int</c>, <c>double</c>, <c>float</c>, <c>decimal</c> — numeric literal.</item>
/// <item>All other types — <c>TypeDescriptor.GetConverter(typeof(T)).ConvertFromInvariantString("value")</c>.</item>
/// <item>Property not found on type — goto fallback (conservative).</item>
/// </list>
/// </para>
/// </remarks>
static class UpdateComponentCodeWriter
{
	static readonly string NewLine = RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? "\r\n" : "\n";

	/// <summary>
	/// Generates the code for a single <c>if (__version == fromVersion) { ... __version = toVersion; }</c> block.
	/// Returns <see langword="null"/> when <paramref name="diff"/> contains no changes.
	/// </summary>
	public static string? GeneratePatchBody(
		XamlTreeDiff diff,
		int fromVersion,
		int toVersion,
		INamedTypeSymbol rootType,
		Compilation compilation,
		AssemblyAttributes xmlnsCache,
		IDictionary<XmlType, INamedTypeSymbol> typeCache)
	{
		if (diff.IsEmpty)
			return null;

		using var codeWriter = new IndentedTextWriter(new StringWriter(CultureInfo.InvariantCulture), "\t") { NewLine = NewLine };

		// Emit diff summary as a comment for diagnostics
		EmitDiffSummary(codeWriter, diff);

		// Emit child list changes FIRST (before property changes, since property diffs use post-change IDs)
		int changeIdx = 0;
		int addedCounter = 0;
		foreach (var change in diff.ChildListChanges)
		{
			EmitChildListChange(codeWriter, change, changeIdx++, ref addedCounter, compilation, xmlnsCache, typeCache);
			codeWriter.WriteLine();
		}

		int compIdx = 0;
		foreach (var nodeDiff in diff.NodeChanges)
		{
			bool isRoot = string.IsNullOrEmpty(nodeDiff.NodeId);

			if (isRoot)
			{
				INamedTypeSymbol? rootNodeType = null;
				if (nodeDiff.NodeXmlType is { } xmlTypeRoot)
					xmlTypeRoot.TryResolveTypeSymbol(null, compilation, xmlnsCache, typeCache, out rootNodeType);

				foreach (var propDiff in nodeDiff.PropertyChanges)
				{
					EmitRootPropertyChange(codeWriter, propDiff, rootNodeType ?? rootType);
				}
				codeWriter.WriteLine();
				continue;
			}

			var varName = $"__uc_{compIdx++}";
			codeWriter.WriteLine($"if (!global::Microsoft.Maui.Controls.Xaml.XamlComponentRegistry.TryGet(this, \"{nodeDiff.NodeId}\", out var {varName}))");
			codeWriter.Indent++;
			codeWriter.WriteLine("goto fallback;");
			codeWriter.Indent--;

			INamedTypeSymbol? nodeType = null;
			string castPrefix;
			if (nodeDiff.NodeXmlType is { } xmlType
				&& xmlType.TryResolveTypeSymbol(null, compilation, xmlnsCache, typeCache, out nodeType)
				&& nodeType != null)
			{
				var fqName = nodeType.ToFQDisplayString();
				castPrefix = $"(({fqName}){varName}!).";
			}
			else
			{
				castPrefix = $"({varName} as global::Microsoft.Maui.Controls.BindableObject)?.";
			}

			foreach (var propDiff in nodeDiff.PropertyChanges)
			{
				EmitPropertyChange(codeWriter, castPrefix, propDiff, nodeType, varName);
			}

			codeWriter.WriteLine();
		}

		codeWriter.WriteLine($"__version = {toVersion};");

		codeWriter.Flush();
		return codeWriter.InnerWriter.ToString();
	}

	/// <summary>
	/// Assembles a complete <c>UpdateComponent()</c> source file from accumulated patch bodies.
	/// Each patch body becomes an <c>if (__version == N) { ... }</c> block inside the single method.
	/// </summary>
	public static string? GenerateUpdateComponent(
		INamedTypeSymbol rootType,
		string accessModifier,
		List<string> allPatchBodies,
		int startVersion = 0)
	{
		if (allPatchBodies.Count == 0)
			return null;

		using var codeWriter = new IndentedTextWriter(new StringWriter(CultureInfo.InvariantCulture), "\t") { NewLine = NewLine };

		codeWriter.WriteLine(GeneratorHelpers.AutoGeneratedHeaderText);
		codeWriter.WriteLine("#nullable enable");
		codeWriter.WriteLine("#pragma warning disable CS0219 // Variable is assigned but its value is never used");
		codeWriter.WriteLine();
		codeWriter.WriteLine($"namespace {rootType.ContainingNamespace};");
		codeWriter.WriteLine();
		codeWriter.WriteLine(InitializeComponentCodeWriter.GeneratedCodeAttribute);
		codeWriter.WriteLine($"{accessModifier} partial class {rootType.Name}");

		using (PrePost.NewBlock(codeWriter))
		{
			codeWriter.WriteLine($"[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
			codeWriter.WriteLine($"internal void UpdateComponent()");

			using (PrePost.NewBlock(codeWriter))
			{
				// Emit each patch as a sequential if (__version == N) block
				for (int i = 0; i < allPatchBodies.Count; i++)
				{
					var body = allPatchBodies[i];
					var version = startVersion + i;
					codeWriter.WriteLine($"if (__version == {version})");
					using (PrePost.NewBlock(codeWriter))
					{
						WriteIndentedBody(codeWriter, body);
					}
				}

				codeWriter.WriteLine("return;");
				codeWriter.WriteLine();
				codeWriter.WriteLine("fallback:");
				codeWriter.WriteLine("__version = 0;");
				codeWriter.WriteLine("this.InitializeComponentRuntime();");
			}
		}

		codeWriter.Flush();
		return codeWriter.InnerWriter.ToString();
	}

	/// <summary>
	/// Backward-compatible overload: generates a single-patch UpdateComponent() from a diff.
	/// Used by unit tests that test a single diff.
	/// </summary>
	public static string? GenerateUpdateComponent(
		INamedTypeSymbol rootType,
		string accessModifier,
		XamlTreeDiff diff,
		int fromVersion,
		int toVersion,
		Compilation compilation,
		AssemblyAttributes xmlnsCache,
		IDictionary<XmlType, INamedTypeSymbol> typeCache)
	{
		var patchBody = GeneratePatchBody(diff, fromVersion, toVersion, rootType, compilation, xmlnsCache, typeCache);
		if (patchBody == null)
			return null;

		return GenerateUpdateComponent(rootType, accessModifier, new List<string> { patchBody }, startVersion: fromVersion);
	}

	static void WriteIndentedBody(IndentedTextWriter codeWriter, string body)
	{
		var lines = body.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None);
		foreach (var line in lines)
		{
			if (!string.IsNullOrWhiteSpace(line))
				codeWriter.WriteLine(line.TrimStart('\t'));
			else if (line.Length > 0)
				codeWriter.WriteLine();
		}
	}

	static void EmitChildListChange(
		IndentedTextWriter codeWriter,
		ChildListChangeDiff change,
		int changeIdx,
		ref int addedCounter,
		Compilation compilation,
		AssemblyAttributes xmlnsCache,
		IDictionary<XmlType, INamedTypeSymbol> typeCache)
	{
		bool isRoot = string.IsNullOrEmpty(change.ParentNodeId);

		if (isRoot)
		{
			codeWriter.WriteLine("// Root-level child list change not supported — fallback");
			codeWriter.WriteLine("goto fallback;");
			return;
		}

		// Look up parent from registry
		var parentVar = $"__rp_{changeIdx}";
		codeWriter.WriteLine($"if (!global::Microsoft.Maui.Controls.Xaml.XamlComponentRegistry.TryGet(this, \"{change.ParentNodeId}\", out var {parentVar}))");
		codeWriter.Indent++;
		codeWriter.WriteLine("goto fallback;");
		codeWriter.Indent--;

		// Cast to Layout to access Children
		var layoutVar = $"__rl_{changeIdx}";
		codeWriter.WriteLine($"var {layoutVar} = {parentVar} as global::Microsoft.Maui.Controls.Layout;");
		codeWriter.WriteLine($"if ({layoutVar} == null) goto fallback;");

		// Save references to all retained children by their old node IDs
		int retainedIdx = 0;
		for (int i = 0; i < change.NewChildren.Count; i++)
		{
			var entry = change.NewChildren[i];
			if (entry.Kind != ChildChangeKind.Retained)
				continue;
			var childVar = $"__rc_{changeIdx}_{retainedIdx++}";
			codeWriter.WriteLine($"if (!global::Microsoft.Maui.Controls.Xaml.XamlComponentRegistry.TryGet(this, \"{entry.OldNodeId}\", out var {childVar}))");
			codeWriter.Indent++;
			codeWriter.WriteLine("goto fallback;");
			codeWriter.Indent--;
		}

		// Clear children
		codeWriter.WriteLine($"{layoutVar}.Clear();");

		// Re-add retained children and create+add new children in new order
		retainedIdx = 0;
		for (int i = 0; i < change.NewChildren.Count; i++)
		{
			var entry = change.NewChildren[i];
			if (entry.Kind == ChildChangeKind.Retained)
			{
				var childVar = $"__rc_{changeIdx}_{retainedIdx++}";
				codeWriter.WriteLine($"{layoutVar}.Add((global::Microsoft.Maui.IView){childVar}!);");
			}
			else // Added
			{
				var newElement = entry.NewElement!;
				EmitNewElement(codeWriter, newElement, layoutVar, entry.NewNodeId, ref addedCounter, compilation, xmlnsCache, typeCache);
			}
		}

		// Re-register retained children whose IDs changed (reorder/position shift)
		retainedIdx = 0;
		for (int i = 0; i < change.NewChildren.Count; i++)
		{
			var entry = change.NewChildren[i];
			if (entry.Kind != ChildChangeKind.Retained)
				continue;
			if (!string.Equals(entry.OldNodeId, entry.NewNodeId, StringComparison.Ordinal))
			{
				codeWriter.WriteLine($"global::Microsoft.Maui.Controls.Xaml.XamlComponentRegistry.ReRoot(this, \"{entry.OldNodeId}\", \"{entry.NewNodeId}\");");
			}
			retainedIdx++;
		}

		// Unregister removed children and their subtrees
		foreach (var removedId in change.RemovedNodeIds)
		{
			codeWriter.WriteLine($"global::Microsoft.Maui.Controls.Xaml.XamlComponentRegistry.UnregisterSubtree(this, \"{removedId}\");");
		}
	}

	/// <summary>
	/// Emits code that creates a new element, sets its simple properties, recursively creates
	/// its children, adds them, and registers everything in the component registry.
	/// </summary>
	static void EmitNewElement(
		IndentedTextWriter codeWriter,
		ElementNode element,
		string parentLayoutVar,
		string nodeId,
		ref int addedCounter,
		Compilation compilation,
		AssemblyAttributes xmlnsCache,
		IDictionary<XmlType, INamedTypeSymbol> typeCache)
	{
		// Resolve XmlType → C# type
		if (!element.XmlType.TryResolveTypeSymbol(null, compilation, xmlnsCache, typeCache, out var typeSymbol)
			|| typeSymbol == null)
		{
			codeWriter.WriteLine($"// Cannot resolve type '{element.XmlType.Name}' — fallback");
			codeWriter.WriteLine("goto fallback;");
			return;
		}

		var fqName = typeSymbol.ToFQDisplayString();
		var idx = addedCounter++;
		var varName = $"__na_{idx}";

		// Create instance
		codeWriter.WriteLine($"var {varName} = new {fqName}();");

		// Set simple properties
		foreach (var kvp in element.Properties)
		{
			if (kvp.Key.NamespaceURI == "x")
				continue; // skip x:Name, x:Class, etc.
			if (kvp.Value is not ValueNode valueNode)
				continue; // skip complex properties (already validated by CanCreateIncrementally)

			var propName = kvp.Key.LocalName;
			var rawValue = valueNode.Value?.ToString() ?? string.Empty;
			var valueExpr = BuildValueExpression(rawValue, typeSymbol, propName);

			if (valueExpr != null)
				codeWriter.WriteLine($"{varName}.{propName} = {valueExpr};");
		}

		// Recursively create children
		if (element.CollectionItems.Count > 0)
		{
			var childLayoutVar = $"__nal_{idx}";
			codeWriter.WriteLine($"var {childLayoutVar} = (global::Microsoft.Maui.Controls.Layout){varName};");

			for (int i = 0; i < element.CollectionItems.Count; i++)
			{
				if (element.CollectionItems[i] is ElementNode childElement)
				{
					var childNodeId = string.IsNullOrEmpty(nodeId)
						? $"{childElement.XmlType.Name}_{i}"
						: $"{nodeId}/{childElement.XmlType.Name}_{i}";
					EmitNewElement(codeWriter, childElement, childLayoutVar, childNodeId, ref addedCounter, compilation, xmlnsCache, typeCache);
				}
			}
		}

		// Add to parent layout
		codeWriter.WriteLine($"{parentLayoutVar}.Add((global::Microsoft.Maui.IView){varName});");

		// Register in component registry
		codeWriter.WriteLine($"global::Microsoft.Maui.Controls.Xaml.XamlComponentRegistry.Register(this, \"{nodeId}\", {varName});");
	}

	static void EmitRootPropertyChange(
		IndentedTextWriter codeWriter,
		PropertyDiff propDiff,
		INamedTypeSymbol rootType)
	{
		var propName = propDiff.PropertyName.LocalName;

		if (propDiff.Kind == PropertyDiffKind.Clear)
		{
			var bpFieldName = $"{propName}Property";
			var bp = FindStaticField(rootType, bpFieldName);
			if (bp != null)
			{
				codeWriter.WriteLine($"this.ClearValue({rootType.ToFQDisplayString()}.{bpFieldName});");
				return;
			}
			codeWriter.WriteLine($"// Property '{propName}' cleared on root — fallback to runtime reload");
			codeWriter.WriteLine("goto fallback;");
			return;
		}

		var rawValue = propDiff.NewValue ?? string.Empty;
		if (propDiff.NewNode != null)
		{
			codeWriter.WriteLine($"// Complex root property '{propName}' ({propDiff.NewNode.GetType().Name}) — fallback to runtime reload");
			codeWriter.WriteLine("goto fallback;");
			return;
		}
		var valueExpr = BuildValueExpression(rawValue, rootType, propName);

		if (valueExpr == null)
		{
			codeWriter.WriteLine($"// Cannot encode root '{propName}' = \"{EscapeString(rawValue)}\" inline — fallback");
			codeWriter.WriteLine("goto fallback;");
			return;
		}

		codeWriter.WriteLine($"this.{propName} = {valueExpr};");
	}

	static void EmitPropertyChange(
		IndentedTextWriter codeWriter,
		string castPrefix,
		PropertyDiff propDiff,
		INamedTypeSymbol? nodeType,
		string varName)
	{
		var propName = propDiff.PropertyName.LocalName;

		if (propDiff.Kind == PropertyDiffKind.Clear)
		{
			// Use ClearValue via the BindableObject API when we know the bindable property field
			if (nodeType != null)
			{
				// Look for a static BindableProperty field named {PropName}Property
				var bpFieldName = $"{propName}Property";
				var bp = FindStaticField(nodeType, bpFieldName);
				if (bp != null)
				{
					codeWriter.WriteLine($"({varName} as global::Microsoft.Maui.Controls.BindableObject)?.ClearValue({nodeType.ToFQDisplayString()}.{bpFieldName});");
					return;
				}
			}
			// Fallback: set to default via property setter (won't cover all cases but avoids goto)
			codeWriter.WriteLine($"// Property '{propName}' cleared — fallback to runtime reload");
			codeWriter.WriteLine("goto fallback;");
			return;
		}

		// Kind == Set
		if (propDiff.NewNode != null)
		{
			// Complex property (markup extension, nested element, list) — codegen can't emit inline yet
			codeWriter.WriteLine($"// Complex property '{propName}' ({propDiff.NewNode.GetType().Name}) — fallback to runtime reload");
			codeWriter.WriteLine("goto fallback;");
			return;
		}
		var rawValue = propDiff.NewValue ?? string.Empty;
		var valueExpr = BuildValueExpression(rawValue, nodeType, propName);

		if (valueExpr == null)
		{
			// Cannot encode value inline — use runtime fallback
			codeWriter.WriteLine($"// Cannot encode '{propName}' = \"{EscapeString(rawValue)}\" inline — fallback to runtime reload");
			codeWriter.WriteLine("goto fallback;");
			return;
		}

		codeWriter.WriteLine($"{castPrefix}{propName} = {valueExpr};");
	}

	/// <summary>
	/// Returns a C# expression string for <paramref name="rawXamlValue"/>.
	/// Returns <see langword="null"/> when no inline encoding is possible.
	/// </summary>
	static string? BuildValueExpression(string rawXamlValue, INamedTypeSymbol? nodeType, string propertyName)
	{
		// Look up the C# property type
		ITypeSymbol? propType = null;
		if (nodeType != null)
		{
			var member = FindProperty(nodeType, propertyName);
			propType = member?.Type;
		}

		if (propType == null)
		{
			// Type is unresolvable — cannot generate safe code; fall through to goto fallback
			return null;
		}

		var fqName = propType.ToFQDisplayString();

		// Direct string
		if (fqName == "string" || fqName == "System.String" || fqName == "global::System.String")
			return $"\"{EscapeString(rawXamlValue)}\"";

		// bool
		if (fqName is "bool" or "global::System.Boolean")
		{
			if (rawXamlValue.Equals("true", StringComparison.OrdinalIgnoreCase)) return "true";
			if (rawXamlValue.Equals("false", StringComparison.OrdinalIgnoreCase)) return "false";
			return null;
		}

		// Integer types
		if (fqName is "int" or "global::System.Int32" or "long" or "global::System.Int64"
			or "short" or "global::System.Int16" or "byte" or "global::System.Byte")
		{
			var trimmed = rawXamlValue.Trim();
			if (long.TryParse(trimmed, NumberStyles.Integer, CultureInfo.InvariantCulture, out _))
				return trimmed;
			return null; // invalid numeric — fallback
		}

		// Float/double
		if (fqName is "float" or "global::System.Single")
		{
			var trimmed = rawXamlValue.Trim();
			if (double.TryParse(trimmed, NumberStyles.Float | NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture, out _))
				return $"{trimmed}f";
			return null;
		}
		if (fqName is "double" or "global::System.Double")
		{
			var trimmed = rawXamlValue.Trim();
			if (double.TryParse(trimmed, NumberStyles.Float | NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture, out _))
				return trimmed;
			return null;
		}
		if (fqName is "decimal" or "global::System.Decimal")
		{
			var trimmed = rawXamlValue.Trim();
			if (decimal.TryParse(trimmed, NumberStyles.Float | NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture, out _))
				return $"{trimmed}m";
			return null;
		}

		// All other types: use TypeDescriptor at runtime
		return BuildTypeDescriptorExpression(rawXamlValue, fqName);
	}

	static string BuildTypeDescriptorExpression(string rawValue, string? fqTypeName)
	{
		if (fqTypeName == null)
			return $"global::System.ComponentModel.TypeDescriptor.GetConverter(null)?.ConvertFromInvariantString(\"{EscapeString(rawValue)}\")";

		return $"({fqTypeName})global::System.ComponentModel.TypeDescriptor.GetConverter(typeof({fqTypeName})).ConvertFromInvariantString(\"{EscapeString(rawValue)}\")!";
	}

	static IPropertySymbol? FindProperty(INamedTypeSymbol type, string name)
	{
		var current = (ITypeSymbol)type;
		while (current != null)
		{
			foreach (var member in current.GetMembers(name))
			{
				if (member is IPropertySymbol prop)
					return prop;
			}
			current = current.BaseType!;
		}
		return null;
	}

	static IFieldSymbol? FindStaticField(INamedTypeSymbol type, string name)
	{
		var current = (ITypeSymbol)type;
		while (current != null)
		{
			foreach (var member in current.GetMembers(name))
			{
				if (member is IFieldSymbol field && field.IsStatic)
					return field;
			}
			current = current.BaseType!;
		}
		return null;
	}

	static string EscapeString(string value) =>
		value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");

	/// <summary>
	/// Emits the diff summary as a C# comment block at the top of the method body.
	/// This makes the diff visible when inspecting generated source files in the IDE.
	/// </summary>
	static void EmitDiffSummary(IndentedTextWriter codeWriter, XamlTreeDiff diff)
	{
		var summary = diff.ToDebugString();
		var lines = summary.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None);
		foreach (var line in lines)
		{
			codeWriter.WriteLine($"// {line}");
		}
		codeWriter.WriteLine();
	}
}
