using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Runtime.InteropServices;
using Microsoft.CodeAnalysis;
using Microsoft.Maui.Controls.Xaml;

namespace Microsoft.Maui.Controls.SourceGen;

/// <summary>
/// Generates an <c>UpdateComponent_v{from}to{to}()</c> partial method from a <see cref="XamlTreeDiff"/>.
/// The generated method applies property-only XAML changes (from a Hot Reload) to live instances
/// via <see cref="XamlComponentRegistry"/> without re-inflating the full page.
/// </summary>
/// <remarks>
/// <para>
/// When the method runs:
/// <list type="number">
/// <item>Guards: if <c>__version != fromVersion</c> the method returns immediately (stale instance).</item>
/// <item>For each changed node: looks up the live component from <see cref="XamlComponentRegistry"/>.</item>
/// <item>Applies each property change using direct C# assignment or <c>TypeDescriptor</c> conversion.</item>
/// <item>Sets <c>__version = toVersion</c> on success.</item>
/// </list>
/// If any component is missing or an unexpected exception occurs, the method jumps to
/// <c>fallback:</c> which calls <c>InitializeComponentRuntime()</c> for a safe full reload.
/// </para>
/// <para>
/// Property value encoding strategy (in priority order):
/// <list type="bullet">
/// <item><c>string</c> — direct string literal.</item>
/// <item><c>bool</c> — <c>true</c> / <c>false</c> literal.</item>
/// <item><c>int</c>, <c>double</c>, <c>float</c>, <c>decimal</c> — numeric literal.</item>
/// <item>All other types — <c>TypeDescriptor.GetConverter(typeof(T)).ConvertFromInvariantString("value")</c>.</item>
/// <item>Property not found on type — goto fallback (conservative).</item>
/// </list>
/// </para>
/// </remarks>
static class UpdateComponentCodeWriter
{
	static readonly string NewLine = RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? "\r\n" : "\n";

	/// <summary>
	/// Generates the source text of a partial class containing <c>UpdateComponent_v{fromVersion}to{toVersion}()</c>.
	/// Returns <see langword="null"/> when <paramref name="diff"/> contains no changes.
	/// </summary>
	public static string? GenerateUpdateComponent(
		INamedTypeSymbol rootType,
		string accessModifier,
		XamlTreeDiff diff,
		int fromVersion,
		int toVersion,
		Compilation compilation,
		AssemblyAttributes xmlnsCache,
		IDictionary<XmlType, INamedTypeSymbol> typeCache)
	{
		if (diff.IsEmpty)
			return null;

		using var codeWriter = new IndentedTextWriter(new StringWriter(CultureInfo.InvariantCulture), "\t") { NewLine = NewLine };

		codeWriter.WriteLine(GeneratorHelpers.AutoGeneratedHeaderText);
		codeWriter.WriteLine("#nullable enable");
		codeWriter.WriteLine("#pragma warning disable CS0219 // Variable is assigned but its value is never used");
		codeWriter.WriteLine();
		codeWriter.WriteLine($"namespace {rootType.ContainingNamespace};");
		codeWriter.WriteLine();
		codeWriter.WriteLine(InitializeComponentCodeWriter.GeneratedCodeAttribute);
		codeWriter.WriteLine($"{accessModifier} partial class {rootType.Name}");

		using (PrePost.NewBlock(codeWriter))
		{
			var methodName = $"UpdateComponent_v{fromVersion}to{toVersion}";
			codeWriter.WriteLine($"[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
			codeWriter.WriteLine($"internal void {methodName}()");

			using (PrePost.NewBlock(codeWriter))
			{
				// Version guard: if the instance is already at a different version, it's either stale
				// (missed an update) or ahead — in both cases we bail out.
				codeWriter.WriteLine($"if (__version != {fromVersion}) return;");
				codeWriter.WriteLine();

				int compIdx = 0;
				foreach (var nodeDiff in diff.NodeChanges)
				{
					if (string.IsNullOrEmpty(nodeDiff.NodeId))
						continue; // root node — not tracked in the registry

					var varName = $"__uc_{compIdx++}";
					codeWriter.WriteLine($"var {varName} = global::Microsoft.Maui.Controls.Xaml.XamlComponentRegistry.TryGet(this, \"{nodeDiff.NodeId}\");");
					codeWriter.WriteLine($"if ({varName} == null) goto fallback;");

					// Resolve C# type for the cast (best-effort; if unresolvable, go to fallback at runtime)
					INamedTypeSymbol? nodeType = null;
					string castPrefix;
					string castSuffix;
					if (nodeDiff.NodeXmlType is { } xmlType
						&& xmlType.TryResolveTypeSymbol(null, compilation, xmlnsCache, typeCache, out nodeType)
						&& nodeType != null)
					{
						var fqName = nodeType.ToFQDisplayString();
						castPrefix = $"(({fqName}){varName}).";
						castSuffix = string.Empty;
					}
					else
					{
						// Type unknown — use dynamic dispatch (slower but safe)
						castPrefix = $"(({varName} as global::Microsoft.Maui.Controls.BindableObject))?.";
						castSuffix = string.Empty;
					}

					foreach (var propDiff in nodeDiff.PropertyChanges)
					{
						EmitPropertyChange(codeWriter, castPrefix, propDiff, nodeType, varName);
					}

					codeWriter.WriteLine();
				}

				codeWriter.WriteLine($"__version = {toVersion};");
				codeWriter.WriteLine("return;");
				codeWriter.WriteLine();
				codeWriter.WriteLine("fallback:");
				codeWriter.WriteLine("__version = 0;");
				codeWriter.WriteLine("this.InitializeComponentRuntime();");
			}
		}

		codeWriter.Flush();
		return codeWriter.InnerWriter.ToString();
	}

	static void EmitPropertyChange(
		IndentedTextWriter codeWriter,
		string castPrefix,
		PropertyDiff propDiff,
		INamedTypeSymbol? nodeType,
		string varName)
	{
		var propName = propDiff.PropertyName.LocalName;

		if (propDiff.Kind == PropertyDiffKind.Clear)
		{
			// Use ClearValue via the BindableObject API when we know the bindable property field
			if (nodeType != null)
			{
				// Look for a static BindableProperty field named {PropName}Property
				var bpFieldName = $"{propName}Property";
				var bp = FindStaticField(nodeType, bpFieldName);
				if (bp != null)
				{
					codeWriter.WriteLine($"({varName} as global::Microsoft.Maui.Controls.BindableObject)?.ClearValue({nodeType.ToFQDisplayString()}.{bpFieldName});");
					return;
				}
			}
			// Fallback: set to default via property setter (won't cover all cases but avoids goto)
			codeWriter.WriteLine($"// Property '{propName}' cleared — fallback to runtime reload");
			codeWriter.WriteLine("goto fallback;");
			return;
		}

		// Kind == Set
		var rawValue = propDiff.NewValue ?? string.Empty;
		var valueExpr = BuildValueExpression(rawValue, nodeType, propName);

		if (valueExpr == null)
		{
			// Cannot encode value inline — use runtime fallback
			codeWriter.WriteLine($"// Cannot encode '{propName}' = \"{EscapeString(rawValue)}\" inline — fallback to runtime reload");
			codeWriter.WriteLine("goto fallback;");
			return;
		}

		codeWriter.WriteLine($"{castPrefix}{propName} = {valueExpr};");
	}

	/// <summary>
	/// Returns a C# expression string for <paramref name="rawXamlValue"/>.
	/// Returns <see langword="null"/> when no inline encoding is possible.
	/// </summary>
	static string? BuildValueExpression(string rawXamlValue, INamedTypeSymbol? nodeType, string propertyName)
	{
		// Look up the C# property type
		ITypeSymbol? propType = null;
		if (nodeType != null)
		{
			var member = FindProperty(nodeType, propertyName);
			propType = member?.Type;
		}

		if (propType == null)
		{
			// Unknown type — use TypeDescriptor at runtime (best effort)
			return BuildTypeDescriptorExpression(rawXamlValue, null);
		}

		var fqName = propType.ToFQDisplayString();

		// Direct string
		if (fqName == "string" || fqName == "System.String" || fqName == "global::System.String")
			return $"\"{EscapeString(rawXamlValue)}\"";

		// bool
		if (fqName is "bool" or "global::System.Boolean")
		{
			if (rawXamlValue.Equals("true", StringComparison.OrdinalIgnoreCase)) return "true";
			if (rawXamlValue.Equals("false", StringComparison.OrdinalIgnoreCase)) return "false";
			return null;
		}

		// Integer types
		if (fqName is "int" or "global::System.Int32" or "long" or "global::System.Int64"
			or "short" or "global::System.Int16" or "byte" or "global::System.Byte")
			return rawXamlValue; // emit as-is (numeric literal)

		// Float/double
		if (fqName is "float" or "global::System.Single")
			return $"{rawXamlValue}f";
		if (fqName is "double" or "global::System.Double")
			return rawXamlValue;
		if (fqName is "decimal" or "global::System.Decimal")
			return $"{rawXamlValue}m";

		// All other types: use TypeDescriptor at runtime
		return BuildTypeDescriptorExpression(rawXamlValue, fqName);
	}

	static string BuildTypeDescriptorExpression(string rawValue, string? fqTypeName)
	{
		if (fqTypeName == null)
			return $"global::System.ComponentModel.TypeDescriptor.GetConverter(null)?.ConvertFromInvariantString(\"{EscapeString(rawValue)}\")";

		return $"({fqTypeName})global::System.ComponentModel.TypeDescriptor.GetConverter(typeof({fqTypeName})).ConvertFromInvariantString(\"{EscapeString(rawValue)}\")!";
	}

	static IPropertySymbol? FindProperty(INamedTypeSymbol type, string name)
	{
		var current = (ITypeSymbol)type;
		while (current != null)
		{
			foreach (var member in current.GetMembers(name))
			{
				if (member is IPropertySymbol prop)
					return prop;
			}
			current = current.BaseType!;
		}
		return null;
	}

	static IFieldSymbol? FindStaticField(INamedTypeSymbol type, string name)
	{
		var current = (ITypeSymbol)type;
		while (current != null)
		{
			foreach (var member in current.GetMembers(name))
			{
				if (member is IFieldSymbol field && field.IsStatic)
					return field;
			}
			current = current.BaseType!;
		}
		return null;
	}

	static string EscapeString(string value) =>
		value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");
}
