// <auto-generated/>
// This file is part of the XAML Incremental HotReload feature.

#nullable enable
using System.Collections.Generic;

namespace Microsoft.Maui.Controls.SourceGen;

/// <summary>
/// In-process static cache that tracks the last-generated XAML text and version number per file,
/// enabling the incremental hot reload pipeline to compute diffs between XAML edits.
/// </summary>
/// <remarks>
/// This class uses mutable static state intentionally: Roslyn incremental generators run
/// in-process during a build session, so state persists across incremental builds.  Each entry
/// maps a <c>(AssemblyName, RelativePath)</c> pair to the XAML content and version counter used
/// the last time an <c>InitializeComponent</c> was generated for that file.
///
/// Keyed on assembly name to prevent cross-project cache bleeding when different projects
/// contain identically-named XAML files (e.g. both have a <c>MainPage.xaml</c>).
///
/// Thread-safety: the dictionary is protected by a lock. Generator output callbacks may run
/// on parallel threads in Roslyn's pipeline.
/// </remarks>
internal static class XamlHotReloadState
{
	static readonly object _lock = new();

	// Maps (assemblyName, relativePath) → (xamlText, version)
	static readonly Dictionary<(string AssemblyName, string RelativePath), (string XamlText, int Version)> _cache = new();

	/// <summary>
	/// Tries to retrieve the previously stored XAML text and version for the given file.
	/// Returns <see langword="false"/> when no entry exists (first run).
	/// </summary>
	public static bool TryGetPrevious(string assemblyName, string relativePath, out string previousXaml, out int previousVersion)
	{
		lock (_lock)
		{
			if (_cache.TryGetValue((assemblyName, relativePath), out var entry))
			{
				previousXaml = entry.XamlText;
				previousVersion = entry.Version;
				return true;
			}
		}
		previousXaml = string.Empty;
		previousVersion = 0;
		return false;
	}

	/// <summary>
	/// Stores (or replaces) the current XAML text and version for the given file.
	/// </summary>
	public static void Update(string assemblyName, string relativePath, string xamlText, int version)
	{
		lock (_lock)
		{
			_cache[(assemblyName, relativePath)] = (xamlText, version);
		}
	}

	/// <summary>
	/// Returns the current version for the given file, or 0 if not cached.
	/// </summary>
	public static int GetVersion(string assemblyName, string relativePath)
	{
		lock (_lock)
		{
			return _cache.TryGetValue((assemblyName, relativePath), out var entry) ? entry.Version : 0;
		}
	}

	/// <summary>
	/// Clears all cached entries.  Intended for use in tests that need to reset state between runs.
	/// </summary>
	public static void Reset()
	{
		lock (_lock)
		{
			_cache.Clear();
		}
	}
}
