// <auto-generated/>
// This file is part of the XAML Incremental HotReload feature.

#nullable enable
using System.Collections.Generic;
using Microsoft.Maui.Controls.Xaml;

namespace Microsoft.Maui.Controls.SourceGen;

/// <summary>
/// In-process static cache that tracks the last-generated XAML text, version number, and
/// accumulated patch bodies per file, enabling the incremental hot reload pipeline to
/// compute diffs between XAML edits and emit a single <c>UpdateComponent()</c> with all patches.
/// </summary>
/// <remarks>
/// This class uses mutable static state intentionally: Roslyn incremental generators run
/// in-process during a build session, so state persists across incremental builds.  Each entry
/// maps a <c>(AssemblyName, RelativePath)</c> pair to the XAML content, version counter, and
/// the list of accumulated patch bodies (each an <c>if (__version == N)</c> block).
///
/// Keyed on assembly name to prevent cross-project cache bleeding when different projects
/// contain identically-named XAML files (e.g. both have a <c>MainPage.xaml</c>).
///
/// Thread-safety: the dictionary is protected by a lock. Generator output callbacks may run
/// on parallel threads in Roslyn's pipeline.
/// </remarks>
internal static class XamlHotReloadState
{
	static readonly object _lock = new();

	// Maps (assemblyName, relativePath) → CacheEntry
	static readonly Dictionary<(string AssemblyName, string RelativePath), CacheEntry> _cache = new();

	internal sealed class CacheEntry
	{
		public string XamlText { get; set; } = string.Empty;
		/// <summary>
		/// The parsed node tree from the last successful generation. Cached so that subsequent
		/// diffs compare against the exact tree that produced the current <c>InitializeComponent</c>,
		/// rather than re-parsing the old XAML against a potentially different compilation.
		/// </summary>
		public SGRootNode? ParsedRoot { get; set; }
		/// <summary>
		/// Map from each <see cref="ElementNode"/> in <see cref="ParsedRoot"/> to its unique ID.
		/// These are the IDs that the runtime registry uses. Preserved across diffs so that
		/// matched nodes keep their identity even when reordered.
		/// </summary>
		public Dictionary<ElementNode, string>? NodeIds { get; set; }
		/// <summary>
		/// The next available node ID counter. New nodes (added children) start numbering here
		/// to avoid colliding with existing IDs.
		/// </summary>
		public int NextNodeId { get; set; }
		public int Version { get; set; }
		/// <summary>
		/// Accumulated patch bodies. Each entry is the code for one <c>if (__version == N) { ... }</c> block.
		/// On structural change, this list is cleared.
		/// </summary>
		public List<string> PatchBodies { get; } = new();
	}

	/// <summary>
	/// Tries to retrieve the previously stored XAML text, parsed root, and version for the given file.
	/// Returns <see langword="false"/> when no entry exists (first run).
	/// </summary>
	public static bool TryGetPrevious(string assemblyName, string relativePath, out string previousXaml, out SGRootNode? previousRoot, out Dictionary<ElementNode, string>? previousNodeIds, out int nextNodeId, out int previousVersion)
	{
		lock (_lock)
		{
			if (_cache.TryGetValue((assemblyName, relativePath), out var entry))
			{
				previousXaml = entry.XamlText;
				previousRoot = entry.ParsedRoot;
				// Return a defensive copy so callers cannot corrupt the cached dictionary
				previousNodeIds = entry.NodeIds != null ? new Dictionary<ElementNode, string>(entry.NodeIds) : null;
				nextNodeId = entry.NextNodeId;
				previousVersion = entry.Version;
				return true;
			}
		}
		previousXaml = string.Empty;
		previousRoot = null;
		previousNodeIds = null;
		nextNodeId = 0;
		previousVersion = 0;
		return false;
	}

	/// <summary>
	/// Stores (or replaces) the current XAML text, parsed root, and version for the given file,
	/// and appends a patch body if provided.
	/// </summary>
	public static void Update(string assemblyName, string relativePath, string xamlText, SGRootNode? parsedRoot, Dictionary<ElementNode, string>? nodeIds, int nextNodeId, int version, string? patchBody = null)
	{
		lock (_lock)
		{
			if (!_cache.TryGetValue((assemblyName, relativePath), out var entry))
			{
				entry = new CacheEntry();
				_cache[(assemblyName, relativePath)] = entry;
			}
			entry.XamlText = xamlText;
			entry.ParsedRoot = parsedRoot;
			entry.NodeIds = nodeIds;
			entry.NextNodeId = nextNodeId;
			entry.Version = version;
			if (patchBody != null)
				entry.PatchBodies.Add(patchBody);
		}
	}

	/// <summary>
	/// Stores the XAML text, parsed root, and version, and clears all accumulated patches (structural change).
	/// </summary>
	public static void UpdateAndClearPatches(string assemblyName, string relativePath, string xamlText, SGRootNode? parsedRoot, Dictionary<ElementNode, string>? nodeIds, int nextNodeId, int version)
	{
		lock (_lock)
		{
			if (!_cache.TryGetValue((assemblyName, relativePath), out var entry))
			{
				entry = new CacheEntry();
				_cache[(assemblyName, relativePath)] = entry;
			}
			entry.XamlText = xamlText;
			entry.ParsedRoot = parsedRoot;
			entry.NodeIds = nodeIds;
			entry.NextNodeId = nextNodeId;
			entry.Version = version;
			entry.PatchBodies.Clear();
		}
	}

	/// <summary>
	/// Returns the current version for the given file, or 0 if not cached.
	/// </summary>
	public static int GetVersion(string assemblyName, string relativePath)
	{
		lock (_lock)
		{
			return _cache.TryGetValue((assemblyName, relativePath), out var entry) ? entry.Version : 0;
		}
	}

	/// <summary>
	/// Returns the cached parsed root for the given file, or null if not cached.
	/// </summary>
	public static SGRootNode? GetParsedRoot(string assemblyName, string relativePath)
	{
		lock (_lock)
		{
			return _cache.TryGetValue((assemblyName, relativePath), out var entry) ? entry.ParsedRoot : null;
		}
	}

	/// <summary>
	/// Returns the cached node-ID dictionary for the given file, or null if not cached.
	/// </summary>
	public static Dictionary<ElementNode, string>? GetNodeIds(string assemblyName, string relativePath)
	{
		lock (_lock)
		{
			return _cache.TryGetValue((assemblyName, relativePath), out var entry) ? entry.NodeIds : null;
		}
	}

	/// <summary>
	/// Returns a copy of the accumulated patch bodies for the given file.
	/// </summary>
	public static List<string> GetPatchBodies(string assemblyName, string relativePath)
	{
		lock (_lock)
		{
			if (_cache.TryGetValue((assemblyName, relativePath), out var entry))
				return new List<string>(entry.PatchBodies);
			return new List<string>();
		}
	}

	/// <summary>
	/// Removes entries for files no longer present in the current compilation.
	/// Called during pipeline execution with the set of files being processed.
	/// </summary>
	public static void PruneStaleEntries(string assemblyName, HashSet<string> activeRelativePaths)
	{
		lock (_lock)
		{
			var keysToRemove = new List<(string, string)>();
			foreach (var key in _cache.Keys)
			{
				if (string.Equals(key.AssemblyName, assemblyName, System.StringComparison.Ordinal)
					&& !activeRelativePaths.Contains(key.RelativePath))
				{
					keysToRemove.Add(key);
				}
			}
			foreach (var key in keysToRemove)
				_cache.Remove(key);
		}
	}

	/// <summary>
	/// Clears all cached entries.  Intended for use in tests that need to reset state between runs.
	/// </summary>
	public static void Reset()
	{
		lock (_lock)
		{
			_cache.Clear();
		}
	}
}
