// <auto-generated/>
// This file is part of the XAML Incremental HotReload feature.

#nullable enable
using System.Collections.Generic;
using Microsoft.Maui.Controls.Xaml;

namespace Microsoft.Maui.Controls.SourceGen;

/// <summary>
/// In-process static cache that tracks the last-generated XAML text (and its parsed tree / node IDs)
/// per file, enabling the incremental hot reload pipeline to compute a diff between successive XAML
/// edits and emit a single previous→current <c>UpdateComponent()</c> patch.
/// </summary>
/// <remarks>
/// This class uses mutable static state intentionally: Roslyn incremental generators run in-process
/// during a build session, so state persists across incremental builds. Each entry maps a
/// <c>(AssemblyName, TargetFramework, RelativePath)</c> tuple to the cached XAML content and its
/// parsed tree.
///
/// <para>
/// IMPORTANT (XIHR determinism): the cache holds only what is needed to diff the PREVIOUS generation
/// against the CURRENT one. It deliberately does NOT accumulate a growing chain of patch bodies, and
/// generated output never embeds the <see cref="CacheEntry.Version"/> counter. This keeps the generator's
/// output a pure function of the current content: identical XAML always produces identical output, and
/// reverting an edit restores the earlier output. (Accumulating patches / embedding a monotonic counter
/// is exactly what made the generator non-deterministic and could leave reverted code uncompilable.)
/// </para>
///
/// Keyed on <c>(AssemblyName, TargetFramework, RelativePath)</c> to prevent:
/// <list type="bullet">
///   <item>Cross-project cache bleeding when different projects contain identically-named XAML files.</item>
///   <item>Cross-TFM cache contamination in multi-target builds where the same XAML file is
///         compiled once per target framework in the same generator host process.</item>
/// </list>
///
/// Thread-safety: the dictionary is protected by a lock. Generator output callbacks may run
/// on parallel threads in Roslyn's pipeline.
/// </remarks>
internal static class XamlHotReloadState
{
	static readonly object _lock = new();

	// Maps (assemblyName, targetFramework, relativePath) → CacheEntry
	static readonly Dictionary<(string AssemblyName, string TargetFramework, string RelativePath), CacheEntry> _cache = new();

	internal sealed class CacheEntry
	{
		public string XamlText { get; set; } = string.Empty;
		/// <summary>
		/// The parsed node tree from the last successful generation. Cached so that subsequent
		/// diffs compare against the exact tree that produced the current <c>InitializeComponent</c>,
		/// rather than re-parsing the old XAML against a potentially different compilation.
		/// </summary>
		public SGRootNode? ParsedRoot { get; set; }
		/// <summary>
		/// Map from each <see cref="ElementNode"/> in <see cref="ParsedRoot"/> to its unique ID.
		/// These are the IDs that the runtime registry uses. Preserved across diffs so that
		/// matched nodes keep their identity even when reordered.
		/// </summary>
		public Dictionary<ElementNode, string>? NodeIds { get; set; }
		/// <summary>
		/// The next available node ID counter. New nodes (added children) start numbering here
		/// to avoid colliding with existing IDs.
		/// </summary>
		public int NextNodeId { get; set; }
		/// <summary>
		/// A monotonic generation counter, kept purely for internal bookkeeping/diagnostics. It does
		/// NOT drive code generation and its value never leaks into generated output. Retained so tooling
		/// can tell how many times a file has been regenerated in the current build session.
		/// </summary>
		public int Version { get; set; }
		/// <summary>
		/// Names and declared XAML types of fields generated on the originally loaded type. This seed
		/// remains stable across edits because metadata updates cannot add or remove instance fields.
		/// </summary>
		public Dictionary<string, XmlType>? GeneratedFields { get; set; }
		/// <summary>
		/// Every field (name, declared C# type, access modifier) <see cref="CodeBehindCodeWriter"/> has
		/// ever emitted for this file during the current generator-host session. Unlike
		/// <see cref="GeneratedFields"/> (a one-time seed), this set only ever grows: once a field has
		/// been generated, it keeps being declared even if its x:Name is later renamed or removed, so a
		/// live Hot Reload edit never turns into a field deletion/rename at the generated-source level.
		/// Roslyn's EnC analyzer treats such deletions/renames as rude edits requiring a restart (see
		/// https://github.com/dotnet/maui/issues/38993), even though the user never touched a C# field.
		/// </summary>
		public Dictionary<string, (string Type, string AccessModifier)>? AccumulatedCodeBehindFields { get; set; }
		/// <summary>
		/// True once <see cref="Update"/> has run for this entry at least once (i.e. a real IC/UC
		/// generation has happened for this file). An entry can exist in <see cref="_cache"/> without
		/// this being set — e.g. <see cref="SetAccumulatedCodeBehindFields"/> lazily creates an entry
		/// purely to persist the CB field-additivity bookkeeping, which runs before the IC/UC pipeline
		/// stage even on the very first generation. <see cref="TryGetPrevious"/> must not treat such a
		/// bookkeeping-only entry as a real previous generation, or the UC diff logic will try to diff
		/// against an empty/absent baseline and spuriously fail.
		/// </summary>
		public bool HasGeneratedOutput { get; set; }
	}

	/// <summary>
	/// Tries to retrieve the previously stored XAML text, parsed root, and version for the given file.
	/// Returns <see langword="false"/> when no entry exists (first run).
	/// </summary>
	public static bool TryGetPrevious(string assemblyName, string targetFramework, string relativePath, out string previousXaml, out SGRootNode? previousRoot, out Dictionary<ElementNode, string>? previousNodeIds, out int nextNodeId, out int previousVersion)
	{
		lock (_lock)
		{
			if (_cache.TryGetValue((assemblyName, targetFramework, relativePath), out var entry) && entry.HasGeneratedOutput)
			{
				previousXaml = entry.XamlText;
				previousRoot = entry.ParsedRoot;
				// Return a defensive copy so callers cannot corrupt the cached dictionary
				previousNodeIds = entry.NodeIds != null ? new Dictionary<ElementNode, string>(entry.NodeIds) : null;
				nextNodeId = entry.NextNodeId;
				previousVersion = entry.Version;
				return true;
			}
		}
		previousXaml = string.Empty;
		previousRoot = null;
		previousNodeIds = null;
		nextNodeId = 0;
		previousVersion = 0;
		return false;
	}

	/// <summary>
	/// Stores (or replaces) the current XAML text, parsed root, node IDs, and version for the given
	/// file. This fully replaces the previous entry — the cache only ever holds the latest generation,
	/// never an accumulated history.
	/// </summary>
	public static void Update(string assemblyName, string targetFramework, string relativePath, string xamlText, SGRootNode? parsedRoot, Dictionary<ElementNode, string>? nodeIds, int nextNodeId, int version)
	{
		lock (_lock)
		{
			if (!_cache.TryGetValue((assemblyName, targetFramework, relativePath), out var entry))
			{
				entry = new CacheEntry
				{
					GeneratedFields = parsedRoot is null
						? null
						: XamlGeneratedFieldCollector.Collect(parsedRoot),
				};
				_cache[(assemblyName, targetFramework, relativePath)] = entry;
			}
			else if (entry.GeneratedFields is null && parsedRoot is not null)
			{
				entry.GeneratedFields = XamlGeneratedFieldCollector.Collect(parsedRoot);
			}
			entry.XamlText = xamlText;
			entry.ParsedRoot = parsedRoot;
			entry.NodeIds = nodeIds;
			entry.NextNodeId = nextNodeId;
			entry.Version = version;
			entry.HasGeneratedOutput = true;
		}
	}

	public static Dictionary<string, XmlType>? GetGeneratedFields(string assemblyName, string targetFramework, string relativePath)
	{
		lock (_lock)
		{
			if (_cache.TryGetValue((assemblyName, targetFramework, relativePath), out var entry)
				&& entry.GeneratedFields is not null)
			{
				return new Dictionary<string, XmlType>(entry.GeneratedFields, System.StringComparer.Ordinal);
			}

			return null;
		}
	}

	/// <summary>
	/// Returns a defensive copy of the fields <see cref="CodeBehindCodeWriter"/> has accumulated for
	/// this file so far (see <see cref="CacheEntry.AccumulatedCodeBehindFields"/>), or
	/// <see langword="null"/> if none have been recorded yet.
	/// </summary>
	public static Dictionary<string, (string Type, string AccessModifier)>? GetAccumulatedCodeBehindFields(string assemblyName, string targetFramework, string relativePath)
	{
		lock (_lock)
		{
			if (_cache.TryGetValue((assemblyName, targetFramework, relativePath), out var entry)
				&& entry.AccumulatedCodeBehindFields is not null)
			{
				return new Dictionary<string, (string, string)>(entry.AccumulatedCodeBehindFields, System.StringComparer.Ordinal);
			}

			return null;
		}
	}

	/// <summary>
	/// Replaces the accumulated code-behind field set for the given file. Callers are expected to pass
	/// the union of the previously accumulated fields and the fields parsed from the current XAML —
	/// this method does not merge on its own, it only stores whatever the caller computed.
	/// </summary>
	public static void SetAccumulatedCodeBehindFields(string assemblyName, string targetFramework, string relativePath, Dictionary<string, (string Type, string AccessModifier)> fields)
	{
		lock (_lock)
		{
			if (!_cache.TryGetValue((assemblyName, targetFramework, relativePath), out var entry))
			{
				entry = new CacheEntry();
				_cache[(assemblyName, targetFramework, relativePath)] = entry;
			}
			entry.AccumulatedCodeBehindFields = new Dictionary<string, (string, string)>(fields, System.StringComparer.Ordinal);
		}
	}

	/// <summary>
	/// Returns the cached parsed root for the given file, or null if not cached.
	/// </summary>
	public static SGRootNode? GetParsedRoot(string assemblyName, string targetFramework, string relativePath)
	{
		lock (_lock)
		{
			return _cache.TryGetValue((assemblyName, targetFramework, relativePath), out var entry) ? entry.ParsedRoot : null;
		}
	}

	/// <summary>
	/// Returns a defensive copy of the cached node-ID dictionary for the given file, or
	/// <see langword="null"/> if not cached. Mirrors <see cref="TryGetPrevious"/>'s contract —
	/// callers must never see the live <see cref="CacheEntry.NodeIds"/> reference.
	/// </summary>
	public static Dictionary<ElementNode, string>? GetNodeIds(string assemblyName, string targetFramework, string relativePath)
	{
		lock (_lock)
		{
			if (_cache.TryGetValue((assemblyName, targetFramework, relativePath), out var entry) && entry.NodeIds != null)
				return new Dictionary<ElementNode, string>(entry.NodeIds);
			return null;
		}
	}

	/// <summary>
	/// Clears all cached entries.  Intended for use in tests that need to reset state between runs.
	/// </summary>
	public static void Reset()
	{
		lock (_lock)
		{
			_cache.Clear();
		}
	}
}
