using System;
using System.IO;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.Maui.Controls.SourceGen;
using Xunit;

using static Microsoft.Maui.Controls.Xaml.UnitTests.SourceGen.SourceGeneratorDriver;

namespace Microsoft.Maui.Controls.Xaml.UnitTests.SourceGen;

public class Maui32758Tests : SourceGenTestsBase
{
	private record AdditionalXamlFile(string Path, string Content, string? RelativePath = null, string? TargetPath = null, string? ManifestResourceName = null, string? TargetFramework = null, string? NoWarn = null, string LineInfo = "enable")
		: AdditionalFile(Text: SourceGeneratorDriver.ToAdditionalText(Path, Content), Kind: "Xaml", RelativePath: RelativePath ?? Path, TargetPath: TargetPath, ManifestResourceName: ManifestResourceName, TargetFramework: TargetFramework, NoWarn: NoWarn, LineInfo: LineInfo);

	[Fact]
	public void StaticExtensionOnPickerItemsSourceShouldUseSetValue()
	{
		var viewModelCode =
"""
using System.Collections.Generic;

namespace Test
{
	public class MainPageViewModel
	{
		public static IReadOnlyList<string> PrimitiveValues => new List<string> { "first", "second", "third" };
	}
}
""";

		var xaml =
"""
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage
	xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
	xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
	xmlns:local="clr-namespace:Test"
	x:Class="Test.TestPage">
	<Picker ItemsSource="{x:Static local:MainPageViewModel.PrimitiveValues}" />
</ContentPage>
""";

		var codeBehind =
"""
using System;
using Microsoft.Maui.Controls;
using Microsoft.Maui.Controls.Xaml;

namespace Test;

[XamlProcessing(XamlInflator.SourceGen)]
public partial class TestPage : ContentPage
{
	public TestPage()
	{
		InitializeComponent();
	}
}
""";

		var compilation = CreateMauiCompilation();
		compilation = compilation.AddSyntaxTrees(
			CSharpSyntaxTree.ParseText(viewModelCode),
			CSharpSyntaxTree.ParseText(codeBehind)
		);

		var workingDirectory = Environment.CurrentDirectory;
		var xamlFile = new AdditionalXamlFile(
			Path.Combine(workingDirectory, "Test.xaml"), 
			xaml, 
			RelativePath: "Test.xaml",
			ManifestResourceName: $"{compilation.AssemblyName}.Test.xaml"
		);

		var result = RunGenerator<XamlGenerator>(compilation, xamlFile);

		var errors = result.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).ToList();
		Assert.False(errors.Any(), $"Found errors: {string.Join(", ", errors.Select(e => e.GetMessage()))}");

		var generatedSource = result.Results[0].GeneratedSources.FirstOrDefault(s => s.HintName.EndsWith(".xsg.cs", System.StringComparison.Ordinal));
		if (generatedSource.SourceText == null)
		{
			Assert.Fail("Could not find .xsg.cs file in generated sources");
			return;
		}
		
		var generatedCode = generatedSource.SourceText.ToString();

		var expected = 
"""
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a .NET MAUI source generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

namespace Test;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Maui.Controls.SourceGen, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null", "10.0.0.0")]
public partial class TestPage
{
	private partial void InitializeComponent()
	{
		// Fallback to Runtime inflation if the page was updated by HotReload
		static string? getPathForType(global::System.Type type)
		{
			var assembly = type.Assembly;
			foreach (var xria in global::System.Reflection.CustomAttributeExtensions.GetCustomAttributes<global::Microsoft.Maui.Controls.Xaml.XamlResourceIdAttribute>(assembly))
			{
				if (xria.Type == type)
					return xria.Path;
			}
			return null;
		}

		var rlr = global::Microsoft.Maui.Controls.Internals.ResourceLoader.ResourceProvider2?.Invoke(new global::Microsoft.Maui.Controls.Internals.ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(global::Test.TestPage).Assembly.GetName(),
			ResourcePath = getPathForType(typeof(global::Test.TestPage)),
			Instance = this,
		});

		if (rlr?.ResourceContent != null)
		{
			this.InitializeComponentRuntime();
			return;
		}

		var staticExtension = global::Test.MainPageViewModel.PrimitiveValues;
		global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(staticExtension!, new global::System.Uri(@"Test.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 7, 10);
		var picker = new global::Microsoft.Maui.Controls.Picker();
		global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(picker!, new global::System.Uri(@"Test.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 7, 3);
		var __root = this;
		global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(__root!, new global::System.Uri(@"Test.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 2, 2);
#if !_MAUIXAML_SG_NAMESCOPE_DISABLE
		global::Microsoft.Maui.Controls.Internals.INameScope iNameScope = global::Microsoft.Maui.Controls.Internals.NameScope.GetNameScope(__root) ?? new global::Microsoft.Maui.Controls.Internals.NameScope();
#endif
#if !_MAUIXAML_SG_NAMESCOPE_DISABLE
		global::Microsoft.Maui.Controls.Internals.NameScope.SetNameScope(__root, iNameScope);
#endif
#if !_MAUIXAML_SG_NAMESCOPE_DISABLE
		picker.transientNamescope = iNameScope;
#endif
#line 7 "/Users/sde/Projects/Microsoft/maui/artifacts/bin/SourceGen.UnitTests/Debug/net10.0/Test.xaml"
		picker.SetValue(global::Microsoft.Maui.Controls.Picker.ItemsSourceProperty, (global::System.Collections.IList)staticExtension);
#line default
#line 7 "/Users/sde/Projects/Microsoft/maui/artifacts/bin/SourceGen.UnitTests/Debug/net10.0/Test.xaml"
		__root.SetValue(global::Microsoft.Maui.Controls.ContentPage.ContentProperty, picker);
#line default
	}
}

""";
		
		Assert.Equal(expected, generatedCode);
	}

	[Fact]
	public void StaticExtensionOnListViewItemsSourceShouldUseSetValue()
	{
		var viewModelCode =
"""
using System.Collections.Generic;

namespace Test
{
	public class MainPageViewModel
	{
		public static IReadOnlyList<string> Items => new List<string> { "Item1", "Item2", "Item3" };
	}
}
""";

		var xaml =
"""
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage
	xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
	xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
	xmlns:local="clr-namespace:Test"
	x:Class="Test.TestPage">
	<ListView ItemsSource="{x:Static local:MainPageViewModel.Items}" />
</ContentPage>
""";

		var codeBehind =
"""
using System;
using Microsoft.Maui.Controls;
using Microsoft.Maui.Controls.Xaml;

namespace Test;

[XamlProcessing(XamlInflator.SourceGen)]
public partial class TestPage : ContentPage
{
	public TestPage()
	{
		InitializeComponent();
	}
}
""";

		var compilation = CreateMauiCompilation();
		compilation = compilation.AddSyntaxTrees(
			CSharpSyntaxTree.ParseText(viewModelCode),
			CSharpSyntaxTree.ParseText(codeBehind)
		);

		var workingDirectory = Environment.CurrentDirectory;
		var xamlFile = new AdditionalXamlFile(
			Path.Combine(workingDirectory, "Test.xaml"), 
			xaml, 
			RelativePath: "Test.xaml",
			ManifestResourceName: $"{compilation.AssemblyName}.Test.xaml"
		);

		var result = RunGenerator<XamlGenerator>(compilation, xamlFile);

		var errors = result.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).ToList();
		Assert.False(errors.Any(), $"Found errors: {string.Join(", ", errors.Select(e => e.GetMessage()))}");

		var generatedSource = result.Results[0].GeneratedSources.FirstOrDefault(s => s.HintName.EndsWith(".xsg.cs", System.StringComparison.Ordinal));
		if (generatedSource.SourceText == null)
		{
			Assert.Fail("Could not find .xsg.cs file in generated sources");
			return;
		}
		
		var generatedCode = generatedSource.SourceText.ToString();
		var expected = 
"""
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a .NET MAUI source generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

namespace Test;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Maui.Controls.SourceGen, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null", "10.0.0.0")]
public partial class TestPage
{
	private partial void InitializeComponent()
	{
		// Fallback to Runtime inflation if the page was updated by HotReload
		static string? getPathForType(global::System.Type type)
		{
			var assembly = type.Assembly;
			foreach (var xria in global::System.Reflection.CustomAttributeExtensions.GetCustomAttributes<global::Microsoft.Maui.Controls.Xaml.XamlResourceIdAttribute>(assembly))
			{
				if (xria.Type == type)
					return xria.Path;
			}
			return null;
		}

		var rlr = global::Microsoft.Maui.Controls.Internals.ResourceLoader.ResourceProvider2?.Invoke(new global::Microsoft.Maui.Controls.Internals.ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(global::Test.TestPage).Assembly.GetName(),
			ResourcePath = getPathForType(typeof(global::Test.TestPage)),
			Instance = this,
		});

		if (rlr?.ResourceContent != null)
		{
			this.InitializeComponentRuntime();
			return;
		}

		var staticExtension = global::Test.MainPageViewModel.Items;
		global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(staticExtension!, new global::System.Uri(@"Test.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 7, 12);
		var listView = new global::Microsoft.Maui.Controls.ListView();
		global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(listView!, new global::System.Uri(@"Test.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 7, 3);
		var __root = this;
		global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(__root!, new global::System.Uri(@"Test.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 2, 2);
#if !_MAUIXAML_SG_NAMESCOPE_DISABLE
		global::Microsoft.Maui.Controls.Internals.INameScope iNameScope = global::Microsoft.Maui.Controls.Internals.NameScope.GetNameScope(__root) ?? new global::Microsoft.Maui.Controls.Internals.NameScope();
#endif
#if !_MAUIXAML_SG_NAMESCOPE_DISABLE
		global::Microsoft.Maui.Controls.Internals.NameScope.SetNameScope(__root, iNameScope);
#endif
#if !_MAUIXAML_SG_NAMESCOPE_DISABLE
		listView.transientNamescope = iNameScope;
#endif
#line 7 "/Users/sde/Projects/Microsoft/maui/artifacts/bin/SourceGen.UnitTests/Debug/net10.0/Test.xaml"
		listView.SetValue(global::Microsoft.Maui.Controls.ItemsView<global::Microsoft.Maui.Controls.Cell>.ItemsSourceProperty, staticExtension);
#line default
#line 7 "/Users/sde/Projects/Microsoft/maui/artifacts/bin/SourceGen.UnitTests/Debug/net10.0/Test.xaml"
		__root.SetValue(global::Microsoft.Maui.Controls.ContentPage.ContentProperty, listView);
#line default
	}
}

""";
		
		Assert.Equal(expected, generatedCode);
	}
}

