using System;
using System.Linq;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Xunit;
using Xunit.Abstractions;

namespace Microsoft.Maui.Controls.SourceGen.UnitTests;

/// <summary>
/// Snapshot test to verify that the XAML source generator produces AOT-safe EventTrigger code.
/// Validates that generated code uses EventTrigger.Create factory methods with static lambdas.
/// </summary>
public class Maui33591SourceGenTests : SourceGenXamlInitializeComponentTestBase
{
	private readonly ITestOutputHelper _output;

	public Maui33591SourceGenTests(ITestOutputHelper output)
	{
		_output = output;
	}

	[Fact]
	public void EventTriggerGeneration_ProducesAOTSafeCode()
	{
		// Test verifying issue #33591: XAML source generator should produce AOT-safe EventTrigger instantiation
		// When EventTrigger.Event property is set, SetPropertyHelpers.SetEventTriggerEvent generates
		// code using EventTrigger.Create<T>() factory with static lambdas
		var xaml =
		"""
		<?xml version="1.0" encoding="UTF-8"?>
		<ContentPage
			xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
			xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
			xmlns:local="clr-namespace:Test"
			x:Class="Test.EventTriggerPage">
			<StackLayout Padding="10">
				<Button x:Name="TestButton" Text="Click Me">
					<Button.Triggers>
						<EventTrigger Event="Clicked">
							<local:TestTriggerAction />
						</EventTrigger>
					</Button.Triggers>
				</Button>
			</StackLayout>
		</ContentPage>
		""";

		var code =
		"""
		using Microsoft.Maui.Controls;
		using Microsoft.Maui.Controls.Xaml;

		namespace Test;

		public class TestTriggerAction : TriggerAction<VisualElement>
		{
			protected override void Invoke(VisualElement sender) { }
		}

		[XamlProcessing(XamlInflator.SourceGen)]
		public partial class EventTriggerPage : ContentPage
		{
			public EventTriggerPage()
			{
				InitializeComponent();
			}
		}
		""";

		// Expected generated code snapshot
		// This is the full generated InitializeComponent() method for EventTrigger XAML
		// Key patterns to verify:
		// 1. EventTrigger.Create<Button>() factory method (AOT-safe)
		// 2. Static lambdas for event subscription
		// 3. Event name passed to factory method
		// 4. NO new EventTrigger() - the factory method is used directly
		const string expected =
		"""
		//------------------------------------------------------------------------------
		// <auto-generated>
		//     This code was generated by a .NET MAUI source generator.
		//
		//     Changes to this file may cause incorrect behavior and will be lost if
		//     the code is regenerated.
		// </auto-generated>
		//------------------------------------------------------------------------------
		#nullable enable
		#pragma warning disable CS0219 // Variable is assigned but its value is never used

		namespace Test;

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Maui.Controls.SourceGen, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null", "10.0.0.0")]
		public partial class EventTriggerPage
		{
			private partial void InitializeComponent()
			{
				// Fallback to Runtime inflation if the page was updated by HotReload
				static string? getPathForType(global::System.Type type)
				{
					var assembly = type.Assembly;
					foreach (var xria in global::System.Reflection.CustomAttributeExtensions.GetCustomAttributes<global::Microsoft.Maui.Controls.Xaml.XamlResourceIdAttribute>(assembly))
					{
						if (xria.Type == type)
							return xria.Path;
					}
					return null;
				}

				var rlr = global::Microsoft.Maui.Controls.Internals.ResourceLoader.ResourceProvider2?.Invoke(new global::Microsoft.Maui.Controls.Internals.ResourceLoader.ResourceLoadingQuery
				{
					AssemblyName = typeof(global::Test.EventTriggerPage).Assembly.GetName(),
					ResourcePath = getPathForType(typeof(global::Test.EventTriggerPage)),
					Instance = this,
				});

				if (rlr?.ResourceContent != null)
				{
					this.InitializeComponentRuntime();
					return;
				}

				var testTriggerAction = new global::Test.TestTriggerAction();
				global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(testTriggerAction!, new global::System.Uri(@"Test.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 11, 7);
				var eventTrigger = global::Microsoft.Maui.Controls.EventTrigger.Create<global::Microsoft.Maui.Controls.Button>("Clicked", static (target, handler) => target.Clicked += handler, static (target, handler) => target.Clicked -= handler);
				var button = new global::Microsoft.Maui.Controls.Button();
				global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(button!, new global::System.Uri(@"Test.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 8, 4);
				var stackLayout = new global::Microsoft.Maui.Controls.StackLayout();
				global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(stackLayout!, new global::System.Uri(@"Test.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 7, 3);
				var __root = this;
				global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(__root!, new global::System.Uri(@"Test.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 2, 2);
		#if !_MAUIXAML_SG_NAMESCOPE_DISABLE
				global::Microsoft.Maui.Controls.Internals.INameScope iNameScope = global::Microsoft.Maui.Controls.Internals.NameScope.GetNameScope(__root) ?? new global::Microsoft.Maui.Controls.Internals.NameScope();
		#endif
		#if !_MAUIXAML_SG_NAMESCOPE_DISABLE
				global::Microsoft.Maui.Controls.Internals.NameScope.SetNameScope(__root, iNameScope);
		#endif
		#if !_MAUIXAML_SG_NAMESCOPE_DISABLE
				stackLayout.transientNamescope = iNameScope;
		#endif
		#if !_MAUIXAML_SG_NAMESCOPE_DISABLE
				button.transientNamescope = iNameScope;
		#endif
		#if !_MAUIXAML_SG_NAMESCOPE_DISABLE
				iNameScope.RegisterName("TestButton", button);
		#endif
				button.StyleId ??= "TestButton";
				this.TestButton = button;
		#line NORMALIZED_LINE_DIRECTIVE
				stackLayout.SetValue(global::Microsoft.Maui.Controls.Layout.PaddingProperty, new global::Microsoft.Maui.Thickness(10));
		#line default
		#line NORMALIZED_LINE_DIRECTIVE
				button.SetValue(global::Microsoft.Maui.Controls.Button.TextProperty, "Click Me");
		#line default
		#line NORMALIZED_LINE_DIRECTIVE
				((global::System.Collections.Generic.ICollection<global::Microsoft.Maui.Controls.TriggerAction>)eventTrigger.Actions).Add((global::Microsoft.Maui.Controls.TriggerAction)testTriggerAction);
		#line default
				var eventTrigger1 = eventTrigger;
				if (global::Microsoft.Maui.VisualDiagnostics.GetSourceInfo(eventTrigger1!) == null)
					global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(eventTrigger1!, new global::System.Uri(@"Test.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 10, 6);
		#line NORMALIZED_LINE_DIRECTIVE
				((global::System.Collections.Generic.ICollection<global::Microsoft.Maui.Controls.TriggerBase>)((global::System.Collections.Generic.IList<global::Microsoft.Maui.Controls.TriggerBase>)button.GetValue(global::Microsoft.Maui.Controls.VisualElement.TriggersProperty))).Add((global::Microsoft.Maui.Controls.TriggerBase)eventTrigger1);
		#line default
		#line NORMALIZED_LINE_DIRECTIVE
				((global::System.Collections.Generic.ICollection<global::Microsoft.Maui.IView>)stackLayout.Children).Add((global::Microsoft.Maui.IView)button);
		#line default
		#line NORMALIZED_LINE_DIRECTIVE
				__root.SetValue(global::Microsoft.Maui.Controls.ContentPage.ContentProperty, stackLayout);
		#line default
			}
		}
		""";

		var (result, generated) = RunGenerator(xaml, code);
		
		// Verify no generation errors
		Assert.False(result.Diagnostics.Any(d => d.Severity == DiagnosticSeverity.Error), 
			$"Expected no errors but got: {string.Join(", ", result.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).Select(d => d.GetMessage()))}");
		
		Assert.NotNull(generated);
		
		// Normalize the generated code by replacing #line directives with paths (they contain machine-specific paths)
		var normalizedGenerated = Regex.Replace(
			generated!,
			@"#line \d+ ""[^""]+""",
			@"#line NORMALIZED_LINE_DIRECTIVE");

		// Output the normalized generated code for review
		_output.WriteLine("=== GENERATED CODE ===");
		_output.WriteLine(normalizedGenerated);
		_output.WriteLine("=== END GENERATED CODE ===");

		Assert.Equal(expected.Trim(), normalizedGenerated.Trim(), ignoreLineEndingDifferences: true, ignoreWhiteSpaceDifferences: true);
	}
}

