namespace Maui.Controls.Sample;

public partial class ImageButtonOptionsPage : ContentPage
{
	private readonly ImageButtonViewModel _viewModel;
	public static string Base64EncodedImage = "iVBORw0KGgoAAAANSUhEUgAAA+gAAAPoCAYAAABNo9TkAAAYuUlEQVR4Xu3aQU7qUACF4cNLdwMDouxDwgpk4jYq23ACKyC4DzUdwHr6TEdOTaSFe78vuSvA9PS3d9b3faYFAAAA/Eu1AAAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAgCajY7O4rJMsUyaA7nien/IrYM8B7Dmzvu8zKmP+nGSfsgFsv0f9kEmBPQew5664Y8wB9kPAgD0vGGDPEejGHMCogz0HsOcCHWMOYNSx5wD2HIFuzAGMOthzAHsu0DHmAEYdew5gzxHoxhzAqIM9B7DnAh1jDmDUsecA2HOBbswBjDrYcwB7LtAx5gBGHXsOgD0X6MYcwKiDPQew5wIdYw5g1LHnANhzgW7MAYw62HMAey7QMeYARh17DoA9F+jGHMCogz0HsOcCHWMOYNSx5wDYc4FuzAGMOthzAHsu0DHmAEYdew6APRfoxhwAo449B7DnAh1jDmDUsecA2HOBbswBMOrYcwB7LtAx5gBGHXsOgD0X6MYcAKOOPQew5wIdYw5g1LHnANhzgW7MATDq2HMAey7QMeYARh17DoA9F+jGHACjjj0HsOcIdGMOYNSx5wDYc4FuzAEw6thzAOy5QDfmAEYdew6APRfo04/5urgxBzDq62DPAbDnAv3uLAOAZzv2vAAA9lygAwAAAAIdAAAABDoAAAAg0AEAAECgAwAAAAIdAAAABDoAAAAg0AEAAECgAwAAAAIdAAAABDoAAAAg0AEAAECgAwAAAAIdAAAABDoAAAAg0AEAAECgAwAAAAIdAAAABDoAAAAg0AEAAECgAwAAAAIdAAAABDoAAAAg0AEAAECgAwAAAAIdAAAABDoAAAAg0AEAAECgAwAAAAIdAAAAaFIjdikd0OYHwJ4D9hxf0AEAAACBDgAAAAIdAAAAEOgAAAAg0AEAAACBDgAAAAIdAAAAEOgAAAAg0AEAAACBDgAAAAIdAAAAEOgAAAAg0AEAAACBDgAAAAIdAAAAEOgAAAAg0AEAAACBDgAAAAIdAAAAEOgAAAAg0AEAAACBDgAAAAIdAAAAEOgAAAAg0AEAAACBDgAAAAIdAAAAEOgAAAAg0AEAAACBDgAAAAIdAAAAEOgAAAAg0AEAAACBDgAAAAIdAAAAEOgAAAAg0AEAAACBDgAAAAIdAAAAEOgAAAAg0AEAAACBDgAAAAIdAAAAEOgAAAAg0AEAAACBDgAAAAIdAAAAEOgAAACAQAcAAACBDgAAAAh0AAAAEOgAAACAQAcAAACBDgAAAAh0AAAAEOgAAACAQAcAAACBDgAAAAh0AAAAEOgAAACAQAcAAACBDgAAAAh0AAAAEOgAAACAQAcAAAg3CoEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAAECT6wFYJnnKeKDdLC5t6gBtpsB7ki6TAnxBBxDnAPA0bByAQAfEOQCIdECgA4hzABDpgEAHxDkAiHRAoAOIcwAQ6YBAB8Q5AIh0QKADiHMAEOmAQAfEOQCIdECgA4hzABDpgEAHxDkAiHRAoAOIcwAQ6YBAB8Q5AIh0QKADiHMAEOmAQAfEOQCIdECgA4hzABDpgEAHxDkAiHRAoAOIcwAQ6YBAB8Q5AIh0QKADiHMAEOmAQAfEOQCI9MoAAh0Q5wAg0gGBDohzAECkAwIdEOcAINIBgQ6IcwBApAMCHRDnACDSAYEOiHMAQKQDAh0Q5wAg0gGBDohzAECkAwIdEOcAINIBgQ6IcwBApAMCHSg7zgHAlgMCHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAQJNyAMBXko/UhFWSh9wUABDoAPCR5C1V4e4DHQBccQcAAACBDgAAAAh0AAAAEOgAAACAQAcAAACBDgAAAAh0AAAAEOgAAACAQAcAAACBDgAAAAh0AAAAEOgAAACAQAcAAACBDgAAAAh0AAAAEOgAAACAQAcAAACBDgAAAAh0AAAAEOgAAACAQAcAAACBDgAAAAh0AAAAEOgAAACAQAcAAACBDgAAAAh0AAAAEOgAAACAQAcAAACBDgAAAAh0AAAAEOgAAACAQAcAAACBDgAAAAh0AAAAEOgAAACAQAcAAACBDgAAAAh0AAAAEOgAAACAQAcAAACBDgAAAAh0AAAAEOgAAACAQAcAAACBDgAAAAh0AAAAEOgAAACAQAcAAACBDgAAAAh0AAAAEOgAAACAQAcAAACBDgAAAAh0AAAAEOgAAACAQAcAAACBDgAAAAh0AAAAEOgAAACAQAcAAACa1Ig2BQAA8A4H+IIOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAAQ6AAAACHQAAABAoHeZFgAAAFpNoB/P81OSbW4FAAAA26HVBHqVkX64mUgHAAAQ54f8mkAX6QAAAIhzgS7SAQAAxLlAF+kAAACIc4Eu0gEAAMS5QBfpAAAAiHOBLtIBAADEuUAX6QAAAIhzgS7SAQAAxLlAF+kAAACIc4Eu0gEAAMS5QEekAwAAiHOBLtIBAADEuUBHpAMAAIhzgS7SAQAAxLlAR6QDAACIc4Eu0gEAAMS5QEekAwAAiHOBLtIBAADEuUBHpAMAAIhzgS7SAQAAxLlAR6QDAACIc4Eu0gEAAMS5QEekAwAAiHOBLtIBAADEuUBHpAMAAIhzgS7SAQAAxLlAR6QDAACIc4Eu0gEAAMQ5s77vMy42i8s6yTLjgTZ1+krykZrwOZya8DicmrBK8pA67TIe6L7j/JQ/h0AH/xTqU6e34ZQEgJfh1Hkbc5YfAFfcAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOhL8AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAAKDJ6NgsLusky1wbsEpt+BxOTXgcDp7tdbxDvmY80B3P81NGxazv+4xKnD8n2ecaAHgbTk14Gc41ALD9jvRDJuWKO+IcAABgPzQMAl2cAwAAiHSBjjgHAAAQ6QJdnAMAAIh0gY44BwAAEOkCXZwDAACIdIGOOAcAABDpAl2cAwAAiHSBjjgHAAAQ6QJdnAMAAIh0gY44BwAAEOkCXZwDAACIdIGOOAcAABDpAl2cAwAAiHQEujgHAAAQ6QJdnAMAAIh0BLo4BwAAEOkCXZwDAACIdAS6OAcAABDpAl2cAwAAiHQEujgHAAAQ6QJdnAMAAIh0BLo4BwAAEOkCXZwDAAAg0gW6OAcAABDpAl2cAwAAINIFujgHAAAQ6QJdnAMAACDSBbo4BwAAEOkC/YbjfH1zcQ4AACDS1wK9PssUAAAAQKsJdAAAAECgAwAAgEAHAAAABDoAAAAIdAAAAECgAwAAgEAHAAAABDoAAAAIdAAAAECgAwAAgEAHAAAABDoAAAAIdAAAAECgAwAAgEAHAAAABDoAAAAIdAAAAECgAwAAgEAHAAAABDoAAAAIdAAAAECgAwAAgEAHAAAABDoAAAAIdAAAAECgAwAAgEAHAAAABDoAAAAIdAAAAECgAwAAAE1qxC61oc1tAgC8w+EdDl/QAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAQKADAAAAAh0AAAAEOgAAACDQAQAAgCblAIBVJoffHAAEOgA8DKdAAIAr7gAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAABAoAMAAIBABwAAAAQ6AAAACHQAAABAoAMAAIBABwAAAAQ6AAAACHQAAABAoAMAAIBABwAAAAQ6AAAACHQAAABAoAMAAIBABwAAAAQ68J7JAQC2HBDoQHfXww4A4rwLINABkQ4AiHNAoAMiHQDEOSDQAZEOAIhzQKADIh0AxDkg0AGRDgCIc0CgAyIdAMQ5INABkQ4AiHNAoAMiHQDEOSDQAZEOAIhzQKADIh0AxDkg0AFEOgCIc0CgAyIdAMQ5INABRDoAiHNAoAMi/XYBgDgHBDog0gFAnAMCHUCkA4A4BwQ6INIBQJwDAh1ApAOAOAcEOiDSAUCcAwIdQKQDgDgHBDog0gFAnAMCHUCkA4A4BwQ6INIBQJwDAh1ApAOAOAcEOiDSAUCcAwIdQKQDgDgHBDog0gFAnAMCHUCkA4A4BwQ6INIBQJwDNLkegG44U6BNnXbH8/w11WCzuLzW/PeeHwDwBR0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAAAh0AAAAQ6AAAACDQAQAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6AAAAIBABwAAAIEOAAAACHQAAAAQ6IQ7BQAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAA0qRFtCgAA9hwAX9ABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAINABAAAAgQ4AAAACHQAAABDoAAAAgEAHAAAAgQ4AAAAI9C7TAsCzHXsOgD0X6Mfz/JRkm1IAsB2e7dhzAOy5QL/LUT8UM+oAxvwgAOw5APZcoBt1AIw59hwAey7QjTqAMQd7DmDPBbpRB8CYY88BsOcC3agDGHOw5wD2XKAbdQCMOfYcAHsu0I06gDEHew5gzwW6UQfAmGPPAbDnAt2oAxhzsOcA9lygG3UAjDn2HAB7LtCNOoAxB3sOYM8FulEHwJhjzwGw5wLdqAMYc7DnAPZcoGPUAYw59hwAey7QjTqAMQd7DmDPBTpGHcCYY88BsOcC3agDGHOw5wD2XKBj1AGMOfYcAHsu0I06gDEHew5gzwU6Rh3AmGPPAbDnAt2oAxhzsOcA9lygY9QBjDn2vEYA9lygG3UAYw72HMCeC3SMOoAxB3sOYM8FulEHMOZgzwHsuUDHqAMYc7DnAPZcoBt1AGMO9hzAngt0jDqAMQd7DmDPBbpRBzDmYM8B7Dmzvu8zLjaLyzrJMmUC6L7H/JS7AfYcwJ4LdAAAAMAVdwAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAABDoAAAAgEAHAAAAgQ4AAAAIdAAAAOA/QHZ2FC6ZI88AAAAASUVORK5CYII=";

	public ImageButtonOptionsPage(ImageButtonViewModel viewModel)
	{
		InitializeComponent();
		_viewModel = viewModel;
		BindingContext = _viewModel;
	}

	private async void ApplyButton_Clicked(object sender, EventArgs e)
	{
		if (Navigation.NavigationStack.Count > 1)
		{
			await Navigation.PopAsync();
		}
	}
	private void AspectRadio_CheckedChanged(object sender, CheckedChangedEventArgs e)
	{
		if (!(sender is RadioButton rb) || !rb.IsChecked)
			return;
		switch (rb.Content?.ToString())
		{
			case "AspectFit":
				_viewModel.Aspect = Aspect.AspectFit;
				break;
			case "AspectFill":
				_viewModel.Aspect = Aspect.AspectFill;
				break;
			case "Fill":
				_viewModel.Aspect = Aspect.Fill;
				break;
			case "Center":
				_viewModel.Aspect = Aspect.Center;
				break;
		}
	}

	private void OpaqueRadio_CheckedChanged(object sender, CheckedChangedEventArgs e)
	{
		if (!(sender is RadioButton rb) || !rb.IsChecked)
			return;
		_viewModel.IsOpaque = rb.Content?.ToString() == "True";
	}

	private void SourceTypeRadio_CheckedChanged(object sender, CheckedChangedEventArgs e)
	{
		if (sender is RadioButton rb && rb.IsChecked)
		{
			string type = rb.Content?.ToString() ?? "";
			switch (type)
			{
				case "File":
					_viewModel.Source = new FileImageSource
					{
						File = "dotnet_bot.png"
					};
					break;
				case "Uri":
					_viewModel.Source = new UriImageSource
					{
						Uri = new Uri("https://aka.ms/campus.jpg"),
						CachingEnabled = true,
						CacheValidity = TimeSpan.MaxValue // Effectively infinite cache
					};
					break;

				case "Stream":
					var imageBytes = Convert.FromBase64String(Base64EncodedImage);
					_viewModel.Source = Microsoft.Maui.Controls.ImageSource.FromStream(() => new MemoryStream(imageBytes));
					break;
				case "FontImage":
					_viewModel.Source = new FontImageSource
					{
						FontFamily = "Ion",
						Glyph = "\uf30c",
						Color = Colors.Red,
						Size = 300
					};
					break;
			}
		}
	}

	private void BorderColorRadio_CheckedChanged(object sender, CheckedChangedEventArgs e)
	{
		if (!(sender is RadioButton rb) || !rb.IsChecked)
			return;
		switch (rb.Content?.ToString())
		{
			case "Red":
				_viewModel.BorderColor = Colors.Red;
				break;
			case "Green":
				_viewModel.BorderColor = Colors.Green;
				break;
		}
	}

	private void BorderWidthEntry_TextChanged(object sender, TextChangedEventArgs e)
	{
		if (double.TryParse(e.NewTextValue, out double width))
			_viewModel.BorderWidth = width;
	}


	private void IsEnabledRadio_CheckedChanged(object sender, CheckedChangedEventArgs e)
	{
		if (!(sender is RadioButton rb) || !rb.IsChecked)
			return;
		_viewModel.IsEnabled = rb.Content?.ToString() == "True";
	}

	private void PaddingSlider_ValueChanged(object sender, ValueChangedEventArgs e)
	{
		_viewModel.Padding = new Thickness(e.NewValue);
	}

	private void PaddingEntry_TextChanged(object sender, TextChangedEventArgs e)
	{
		if (double.TryParse(e.NewTextValue, out double padding))
			_viewModel.Padding = new Thickness(padding);
	}

	private void OnPaddingChanged(object sender, TextChangedEventArgs e)
	{
		if (string.IsNullOrWhiteSpace(PaddingEntry?.Text))
			return;
		try
		{
			string[] parts = PaddingEntry.Text.Split(',');
			if (parts.Length == 4 &&
				double.TryParse(parts[0], out double left) &&
				double.TryParse(parts[1], out double top) &&
				double.TryParse(parts[2], out double right) &&
				double.TryParse(parts[3], out double bottom))
			{
				_viewModel.Padding = new Thickness(left, top, right, bottom);
			}
		}
		catch { }
	}

	private void IsVisibleRadio_CheckedChanged(object sender, CheckedChangedEventArgs e)
	{
		if (!(sender is RadioButton rb) || !rb.IsChecked)
			return;
		_viewModel.IsVisible = rb.Content?.ToString() == "True";
	}

	private void ShadowRadio_CheckedChanged(object sender, CheckedChangedEventArgs e)
	{
		if (e.Value && BindingContext is ImageButtonViewModel vm)
		{
			var rb = sender as RadioButton;
			if (rb?.Content?.ToString() == "True")
			{
				vm.Shadow = new Shadow { Brush = Brush.Black, Offset = new Point(5, 5), Radius = 5, Opacity = 0.5f };
			}
			else if (rb?.Content?.ToString() == "False")
			{
				vm.Shadow = null!;
			}
		}
	}

	private void OnFlowDirectionChanged(object sender, EventArgs e)
	{
		_viewModel.FlowDirection = FlowDirectionLTR.IsChecked ? FlowDirection.LeftToRight : FlowDirection.RightToLeft;
	}

	private void OnCornerRadiusChanged(object sender, TextChangedEventArgs e)
	{
		if (string.IsNullOrWhiteSpace(CornerRadiusEntry?.Text))
			return;
		try
		{
			string[] parts = CornerRadiusEntry.Text.Split(',');
			if (parts.Length == 4 &&
				int.TryParse(parts[0], out int topLeft) &&
				int.TryParse(parts[1], out int topRight) &&
				int.TryParse(parts[2], out int bottomLeft) &&
				int.TryParse(parts[3], out int bottomRight))
			{
				_viewModel.CornerRadius = topLeft;
			}
			else if (parts.Length == 1 && int.TryParse(parts[0], out int uniform))
			{
				_viewModel.CornerRadius = uniform;
			}
		}
		catch { }
	}
}
