parameters:
  androidVmPool: $(macOSXVmPool)
  androidVmImage: $(macOSXVmImage)
  iosVmPool: $(macOSXVmPool)
  iosVmImage: $(macOSXVmImage)
  androidApiLevels: [ 30, 29, 21 ]
  iosVersions: [ '14.3' ]
  projects:
    - name: name
      desc: Human Description
      android: /optional/path/to/android.csproj
      ios: /optional/path/to/ios.csproj

stages:

  - stage: android_device_tests
    displayName: Android Device Tests
    dependsOn: []
    jobs:
      - ${{ each project in parameters.projects }}:
        - ${{ if ne(project.android, '') }}:
          - ${{ each api in parameters.androidApiLevels }}:
            - job: android_device_tests_${{ project.name }}_${{ api }}
              workspace:
                clean: all
              displayName: ${{ coalesce(project.desc, project.name) }} (API ${{ api }})
              pool:
                name: ${{ parameters.androidVmPool }}
                vmImage: ${{ parameters.androidVmImage }}
              variables:
                ANDROID_EMULATORS: "system-images;android-${{ api }};google_apis;x86"
              steps:
                - pwsh: 'gci env:*'
                - template: device-tests-steps.yml
                  parameters:
                    platform: android
                    path: ${{ project.android }}
                    device: android-emulator-32_${{ api }}

  - stage: ios_device_tests
    displayName: iOS Device Tests
    dependsOn: []
    jobs:
      - ${{ each project in parameters.projects }}:
        - ${{ if ne(project.ios, '') }}:
          - ${{ each version in parameters.iosVersions }}:
            - job: ios_device_tests_${{ project.name }}_${{ replace(version, '.', '_') }}
              workspace:
                clean: all
              displayName: ${{ coalesce(project.desc, project.name) }} (v${{ version }})
              pool:
                name: ${{ parameters.iosVmPool }}
                vmImage: ${{ parameters.iosVmImage }}
              variables:
                ANDROID_EMULATORS: "system-images;ios-${{ version }};google_apis;x86"
              steps:
                - template: device-tests-steps.yml
                  parameters:
                    platform: ios
                    path: ${{ project.ios }}
                    device: ios-simpulator-46_${{ version }}
