parameters:
  androidPool: { }
  iosPool: { }
  androidApiLevels: [ 30 ]
  iosVersions: [ '16.4' ]
  provisionatorChannel: 'latest'
  agentPoolAccessToken: ''
  projects:
    - name: name
      desc: Human Description
      android: /optional/path/to/android.csproj
      ios: /optional/path/to/ios.csproj

stages:

  - stage: android_device_tests
    displayName: Android Device Tests
    dependsOn: []
    jobs:
      - ${{ each project in parameters.projects }}:
        - ${{ if ne(project.android, '') }}:
          - ${{ each api in parameters.androidApiLevels }}:
            - ${{ if not(containsValue(project.androidApiLevelsExclude, api)) }}:
              - job: android_device_tests_${{ project.name }}_${{ api }}
                workspace:
                  clean: all
                displayName: ${{ coalesce(project.desc, project.name) }} (API ${{ api }})
                pool: ${{ parameters.androidPool }}
                variables:
                  ${{ if ge(api, 24) }}:
                    ANDROID_EMULATORS: "system-images;android-${{ api }};google_apis_playstore;x86"
                  ${{ if lt(api, 24) }}:
                    ANDROID_EMULATORS: "system-images;android-${{ api }};google_apis;x86"
                  REQUIRED_XCODE: $(DEVICETESTS_REQUIRED_XCODE)
                steps:
                  - template: device-tests-steps.yml
                    parameters:
                      platform: android
                      path: ${{ project.android }}
                      device: android-emulator-32_${{ api }}
                      windowsPackageId: android # Only needed for Windows, will be ignored
                      provisionatorChannel: ${{ parameters.provisionatorChannel }}
                      agentPoolAccessToken: ${{ parameters.agentPoolAccessToken }}

  - stage: ios_device_tests
    displayName: iOS Device Tests
    dependsOn: []
    jobs:
      - ${{ each project in parameters.projects }}:
        - ${{ if ne(project.ios, '') }}:
          - ${{ each version in parameters.iosVersions }}:
            - ${{ if not(containsValue(project.iosVersionsExclude, version)) }}:
              - job: ios_device_tests_${{ project.name }}_${{ replace(version, '.', '_') }}
                workspace:
                  clean: all
                displayName: ${{ coalesce(project.desc, project.name) }} (v${{ version }})
                pool: ${{ parameters.iosPool }}
                variables:
                  REQUIRED_XCODE: $(DEVICETESTS_REQUIRED_XCODE)
                steps:
                  - template: device-tests-steps.yml
                    parameters:
                      platform: ios
                      path: ${{ project.ios }}
                      ${{ if eq(version, 'latest') }}:
                        device: ios-simulator-64
                      ${{ if ne(version, 'latest') }}:
                        device: ios-simulator-64_${{ version }}
                      windowsPackageId: ios # Only needed for Windows, will be ignored
                      provisionatorChannel: ${{ parameters.provisionatorChannel }}
                      agentPoolAccessToken: ${{ parameters.agentPoolAccessToken }}

  - stage: windows_device_tests
    displayName: Windows Device Tests
    dependsOn: []
    jobs:
    - job: windows_device_tests
      workspace:
        clean: all
      displayName: "Windows device tests"
      pool:
        vmImage: windows-latest
      strategy:
        matrix:
          # create all the variables used for the matrix
          ${{ each project in parameters.projects }}:
            ${{ if ne(project.windows, '') }}:
              ${{ replace(coalesce(project.desc, project.name), ' ', '_') }}:
                PROJECT_PATH: ${{ project.windows }}
                PACKAGE_ID: ${{ project.windowsPackageId }}
      steps:
        - template: device-tests-steps.yml
          parameters:
            platform: windows
            path: $(PROJECT_PATH)
            windowsPackageId: $(PACKAGE_ID)
            device: windows
            provisionatorChannel: ${{ parameters.provisionatorChannel }}
            agentPoolAccessToken: ${{ parameters.agentPoolAccessToken }}
            artifactName: ${{ parameters.artifactName }}
            artifactItemPattern: ${{ parameters.artifactItemPattern }}
            checkoutDirectory: ${{ parameters.checkoutDirectory }}
            useArtifacts: ${{ parameters.useArtifacts }}
