parameters:
  poolName: VSEngSS-MicroBuild2022-1ES
  vmImage: ''
  os: windows
  dependsOn: []
  stageName: 'sdk_insertion'
  displayName: 'SDK Insertion'
  pushMauiPackagesToMaestro: false

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.displayName }}
    dependsOn: ${{ parameters.dependsOn }}
    condition: and(succeeded(), eq(variables.signingCondition, true))
    jobs:
    - template: /eng/pipelines/common/sdk-insertion.yml@self
      parameters:
        poolName: ${{ parameters.poolName }}
        vmImage: ${{ parameters.vmImage }}
        os: ${{ parameters.os }}
        pushMauiPackagesToMaestro: ${{ parameters.pushMauiPackagesToMaestro }}

