parameters:
  CeapexPat: $(dn-bot-ceapex-package-r) # PAT for the loc AzDO instance https://dev.azure.com/ceapex
  GithubPat: $(BotAccount-dotnet-bot-repo-PAT)

stages:
  - stage: localization
    displayName: Localization
    dependsOn: []
    condition: and(succeeded(), eq(variables.isLocHandoffBranch, true))

    jobs:
      - job : generate_lci
        displayName: 'Process outgoing strings'
        pool:  $(1ESPTPool)

        variables:
          - group: OneLocBuildVariables # Contains the CeapexPat and GithubPat

        steps:
          - task: OneLocBuild@2
            displayName: 'Localization Build'
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
            inputs:
              locProj: 'eng/automation/LocProject.json'
              outDir: '$(Build.ArtifactStagingDirectory)'
              packageSourceAuth: patAuth
              patVariable: ${{ parameters.CeapexPat }}
              isCreatePrSelected: true                            # Create the PR with the Localization changes if there are any
              isShouldReusePrSelected: true                       # Make sure to not keep creating new PRs if one is already open
              isAutoCompletePrSelected: false                     # Allow us to review the created PR instead of auto-merging it
              repoType: gitHub
              prSourceBranchPrefix: $(LocBranchPrefix)
              gitHubPatVariable: "${{ parameters.GithubPat }}"
              gitHubPrMergeMethod: merge

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'