parameters:
  CeapexPat: $(dn-bot-ceapex-package-r) # PAT for the loc AzDO instance https://dev.azure.com/ceapex
  GithubPat: $(BotAccount-dotnet-bot-repo-PAT)

stages:
  - stage: localization_handoff
    displayName: Localization Handoff
    dependsOn: []
    condition: and(succeeded(), eq(variables.isLocHandoffBranch, true))

    jobs:
      - job : generate_lci
        displayName: 'Process outgoing strings'
        pool:  $(HostedWinVS2019)

        variables:
          - group: OneLocBuildVariables # Contains the CeapexPat and GithubPat

        steps:
          - task: OneLocBuild@2
            displayName: 'Localization Build'
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken) 
            inputs:
              locProj: 'eng/automation/LocProject.json'
              outDir: '$(Build.ArtifactStagingDirectory)'
              packageSourceAuth: patAuth
              patVariable: ${{ parameters.CeapexPat }}

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'