parameters:
  CeapexPat: $(dn-bot-ceapex-package-r) # PAT for the loc AzDO instance https://dev.azure.com/ceapex
  GithubPat: $(BotAccount-dotnet-bot-repo-PAT)

stages:
  - stage: localization_handback
    displayName: Localization Handback
    dependsOn: []
    condition: eq(variables.isLocHandoffBranch, true)

    jobs:
      - job: generate_resx
        displayName: 'Process incoming translations'
        pool: $(HostedWinVS2019)

        variables:
          - group: OneLocBuildVariables # Contains the CeapexPat and GithubPat

        steps:
          - powershell: |
              $hasLclFiles = git diff --name-only HEAD~1 HEAD | Select-String '\.lcl$'
              if ($hasLclFiles) {
                Write-Host "##vso[task.setvariable variable=hasLclFiles]true"
                Write-Host "Result: Found .lcl files (true)"
              } else {
                Write-Host "##vso[task.setvariable variable=hasLclFiles]false"
                Write-Host "Result: No .lcl files found (false)"
              }
            displayName: 'Check for .lcl files'

          - task: OneLocBuild@2
            displayName: 'Localization Build'
            condition: eq(variables['hasLclFiles'], 'true')
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
            inputs:
              locProj: 'eng/automation/LocProject.json'
              outDir: '$(Build.ArtifactStagingDirectory)'
              packageSourceAuth: patAuth
              patVariable: ${{ parameters.CeapexPat }}
              isCreatePrSelected: true
              isAutoCompletePrSelected: false
              repoType: gitHub
              prSourceBranchPrefix: $(LocBranchPrefix)
              gitHubPatVariable: "${{ parameters.GithubPat }}"
              gitHubPrMergeMethod: merge
