parameters:
  poolName: Azure Pipelines
  vmImage: windows-latest 

jobs:
- job: create_artifact_statuses
  displayName: Create GitHub Artifact Status
  timeoutInMinutes: 60
  pool:
    name: ${{ parameters.poolName }}
    vmImage: ${{ parameters.vmImage }}
  steps:
  - checkout: self
  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: nuget
      downloadPath: $(Build.StagingDirectory)\nuget
      patterns: |
        **/signed/*.nupkg
        **/*.snupkg
        **/additional-assets.zip
  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: vs-msi-nugets
      downloadPath: $(Build.StagingDirectory)\nuget
  - template: templates\common\upload-vs-insertion-artifacts.yml@sdk-insertions
    parameters:
      githubToken: $(github--pat--vs-mobiletools-engineering-service2)
      githubContext: $(NupkgCommitStatusName)
      blobName: $(NupkgCommitStatusName)
      packagePrefix: maui
      artifactsPath: $(Build.StagingDirectory)\nuget
      yamlResourceName: yaml-templates
  - template: templates\common\upload-vs-insertion-artifacts.yml@sdk-insertions
    parameters:
      githubToken: $(github--pat--vs-mobiletools-engineering-service2)
      githubContext: $(VSDropCommitStatusName)
      blobName: $(VSDropCommitStatusName)
      packagePrefix: maui
      artifactsPath: $(Build.StagingDirectory)/$(VSDropCommitStatusName)
      yamlResourceName: yaml-templates
      downloadSteps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifactName: vsdrop-signed
          downloadPath: $(Build.StagingDirectory)/$(VSDropCommitStatusName)
  - template: templates\common\upload-vs-insertion-artifacts.yml@sdk-insertions
    parameters:
      githubToken: $(github--pat--vs-mobiletools-engineering-service2)
      githubContext: $(MultiTargetVSDropCommitStatusName)
      blobName: $(MultiTargetVSDropCommitStatusName)
      packagePrefix: maui
      artifactsPath: $(Build.StagingDirectory)/$(MultiTargetVSDropCommitStatusName)
      yamlResourceName: yaml-templates
      downloadSteps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifactName: vsdrop-multitarget-signed
          downloadPath: $(Build.StagingDirectory)/$(MultiTargetVSDropCommitStatusName)
