parameters:
  poolName: Azure Pipelines
  vmImage: windows-latest
  os: windows
  teamName: $(TeamName)
  signType: 'Real'
  dependsOn: []
  stageName: 'nuget_signing'
  displayName: 'Sign Nuget'


stages:
  - stage: ${{ parameters.stageName }}
    dependsOn: ${{ parameters.dependsOn }}
    displayName: ${{ parameters.displayName }}
    jobs:
      - template: sign-artifacts/jobs/v2.yml@yaml-templates
        parameters:
          signType: ${{ parameters.signType }}
          teamName: ${{ parameters.teamName }}
          condition: eq(variables.signingCondition, true)
          use1ESTemplate: true
          usePipelineArtifactTasks: true
          checkoutType : 'self'
        
      - template: nuget-msi-convert/job/v4.yml@yaml-templates
        parameters:
          yamlResourceName: yaml-templates
          artifactName: nuget-signed
          propsArtifactName:  nuget
          signType: ${{ parameters.signType }}
          use1ESTemplate: true
          postConvertSteps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: nuget
              downloadPath: $(Build.ArtifactStagingDirectory)\sign-verify
              patterns: |
                **/SignVerifyIgnore.txt

          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: nuget
              downloadPath: $(Build.SourcesDirectory)\eng\automation\guardian
              patterns: |
                **/tsaoptions-v2.json
                **/source.gdnsuppress

          - task: MicroBuildCodesignVerify@3
            displayName: verify signed msi content
            inputs:
              TargetFolders: |
                $(Build.ArtifactStagingDirectory)\bin\manifests
                $(Build.ArtifactStagingDirectory)\bin\manifests-packs
                $(Build.ArtifactStagingDirectory)\bin\msi-nupkgs
              ExcludeSNVerify: true
              ApprovalListPathForCerts: $(Build.ArtifactStagingDirectory)\sign-verify\SignVerifyIgnore.txt
