using Microsoft.Maui.Graphics;

namespace Microsoft.Maui.Controls
{
	[System.ComponentModel.TypeConverter(typeof(BrushTypeConverter))]
	public abstract partial class Brush : Element
	{
		public static Brush Default
		{
			get { return new SolidColorBrush(null); }
		}

		public static implicit operator Brush(Color color) => new SolidColorBrush(color);

		public abstract bool IsEmpty { get; }

		public static bool IsNullOrEmpty(Brush brush)
		{
			return brush == null || brush.IsEmpty;
		}

		static ImmutableBrush aliceBlue;
		public static SolidColorBrush AliceBlue => aliceBlue ??= new(Colors.AliceBlue);
		static ImmutableBrush antiqueWhite;
		public static SolidColorBrush AntiqueWhite => antiqueWhite ??= new(Colors.AntiqueWhite);
		static ImmutableBrush aqua;
		public static SolidColorBrush Aqua => aqua ??= new(Colors.Aqua);
		static ImmutableBrush aquamarine;
		public static SolidColorBrush Aquamarine => aquamarine ??= new(Colors.Aquamarine);
		static ImmutableBrush azure;
		public static SolidColorBrush Azure => azure ??= new(Colors.Azure);
		static ImmutableBrush beige;
		public static SolidColorBrush Beige => beige ??= new(Colors.Beige);
		static ImmutableBrush bisque;
		public static SolidColorBrush Bisque => bisque ??= new(Colors.Bisque);
		static ImmutableBrush black;
		public static SolidColorBrush Black => black ??= new(Colors.Black);
		static ImmutableBrush blanchedAlmond;
		public static SolidColorBrush BlanchedAlmond => blanchedAlmond ??= new(Colors.BlanchedAlmond);
		static ImmutableBrush blue;
		public static SolidColorBrush Blue => blue ??= new(Colors.Blue);
		static ImmutableBrush blueViolet;
		public static SolidColorBrush BlueViolet => blueViolet ??= new(Colors.BlueViolet);
		static ImmutableBrush brown;
		public static SolidColorBrush Brown => brown ??= new(Colors.Brown);
		static ImmutableBrush burlyWood;
		public static SolidColorBrush BurlyWood => burlyWood ??= new(Colors.BurlyWood);
		static ImmutableBrush cadetBlue;
		public static SolidColorBrush CadetBlue => cadetBlue ??= new(Colors.CadetBlue);
		static ImmutableBrush chartreuse;
		public static SolidColorBrush Chartreuse => chartreuse ??= new(Colors.Chartreuse);
		static ImmutableBrush chocolate;
		public static SolidColorBrush Chocolate => chocolate ??= new(Colors.Chocolate);
		static ImmutableBrush coral;
		public static SolidColorBrush Coral => coral ??= new(Colors.Coral);
		static ImmutableBrush cornflowerBlue;
		public static SolidColorBrush CornflowerBlue => cornflowerBlue ??= new(Colors.CornflowerBlue);
		static ImmutableBrush cornsilk;
		public static SolidColorBrush Cornsilk => cornsilk ??= new(Colors.Cornsilk);
		static ImmutableBrush crimson;
		public static SolidColorBrush Crimson => crimson ??= new(Colors.Crimson);
		static ImmutableBrush cyan;
		public static SolidColorBrush Cyan => cyan ??= new(Colors.Cyan);
		static ImmutableBrush darkBlue;
		public static SolidColorBrush DarkBlue => darkBlue ??= new(Colors.DarkBlue);
		static ImmutableBrush darkCyan;
		public static SolidColorBrush DarkCyan => darkCyan ??= new(Colors.DarkCyan);
		static ImmutableBrush darkGoldenrod;
		public static SolidColorBrush DarkGoldenrod => darkGoldenrod ??= new(Colors.DarkGoldenrod);
		static ImmutableBrush darkGray;
		public static SolidColorBrush DarkGray => darkGray ??= new(Colors.DarkGray);
		static ImmutableBrush darkGreen;
		public static SolidColorBrush DarkGreen => darkGreen ??= new(Colors.DarkGreen);
		static ImmutableBrush darkKhaki;
		public static SolidColorBrush DarkKhaki => darkKhaki ??= new(Colors.DarkKhaki);
		static ImmutableBrush darkMagenta;
		public static SolidColorBrush DarkMagenta => darkMagenta ??= new(Colors.DarkMagenta);
		static ImmutableBrush darkOliveGreen;
		public static SolidColorBrush DarkOliveGreen => darkOliveGreen ??= new(Colors.DarkOliveGreen);
		static ImmutableBrush darkOrange;
		public static SolidColorBrush DarkOrange => darkOrange ??= new(Colors.DarkOrange);
		static ImmutableBrush darkOrchid;
		public static SolidColorBrush DarkOrchid => darkOrchid ??= new(Colors.DarkOrchid);
		static ImmutableBrush darkRed;
		public static SolidColorBrush DarkRed => darkRed ??= new(Colors.DarkRed);
		static ImmutableBrush darkSalmon;
		public static SolidColorBrush DarkSalmon => darkSalmon ??= new(Colors.DarkSalmon);
		static ImmutableBrush darkSeaGreen;
		public static SolidColorBrush DarkSeaGreen => darkSeaGreen ??= new(Colors.DarkSeaGreen);
		static ImmutableBrush darkSlateBlue;
		public static SolidColorBrush DarkSlateBlue => darkSlateBlue ??= new(Colors.DarkSlateBlue);
		static ImmutableBrush darkSlateGray;
		public static SolidColorBrush DarkSlateGray => darkSlateGray ??= new(Colors.DarkSlateGray);
		static ImmutableBrush darkTurquoise;
		public static SolidColorBrush DarkTurquoise => darkTurquoise ??= new(Colors.DarkTurquoise);
		static ImmutableBrush darkViolet;
		public static SolidColorBrush DarkViolet => darkViolet ??= new(Colors.DarkViolet);
		static ImmutableBrush deepPink;
		public static SolidColorBrush DeepPink => deepPink ??= new(Colors.DeepPink);
		static ImmutableBrush deepSkyBlue;
		public static SolidColorBrush DeepSkyBlue => deepSkyBlue ??= new(Colors.DeepSkyBlue);
		static ImmutableBrush dimGray;
		public static SolidColorBrush DimGray => dimGray ??= new(Colors.DimGray);
		static ImmutableBrush dodgerBlue;
		public static SolidColorBrush DodgerBlue => dodgerBlue ??= new(Colors.DodgerBlue);
		static ImmutableBrush firebrick;
		public static SolidColorBrush Firebrick => firebrick ??= new(Colors.Firebrick);
		static ImmutableBrush floralWhite;
		public static SolidColorBrush FloralWhite => floralWhite ??= new(Colors.FloralWhite);
		static ImmutableBrush forestGreen;
		public static SolidColorBrush ForestGreen => forestGreen ??= new(Colors.ForestGreen);
		static ImmutableBrush fuschia;
		public static SolidColorBrush Fuchsia => fuschia ??= new(Colors.Fuchsia);
		static ImmutableBrush gainsboro;
		public static SolidColorBrush Gainsboro => gainsboro ??= new(Colors.Gainsboro);
		static ImmutableBrush ghostWhite;
		public static SolidColorBrush GhostWhite => ghostWhite ??= new(Colors.GhostWhite);
		static ImmutableBrush gold;
		public static SolidColorBrush Gold => gold ??= new(Colors.Gold);
		static ImmutableBrush goldenrod;
		public static SolidColorBrush Goldenrod => goldenrod ??= new(Colors.Goldenrod);
		static ImmutableBrush gray;
		public static SolidColorBrush Gray => gray ??= new(Colors.Gray);
		static ImmutableBrush green;
		public static SolidColorBrush Green => green ??= new(Colors.Green);
		static ImmutableBrush greenYellow;
		public static SolidColorBrush GreenYellow => greenYellow ??= new(Colors.GreenYellow);
		static ImmutableBrush honeydew;
		public static SolidColorBrush Honeydew => honeydew ??= new(Colors.Honeydew);
		static ImmutableBrush hotPink;
		public static SolidColorBrush HotPink => hotPink ??= new(Colors.HotPink);
		static ImmutableBrush indianRed;
		public static SolidColorBrush IndianRed => indianRed ??= new(Colors.IndianRed);
		static ImmutableBrush indigo;
		public static SolidColorBrush Indigo => indigo ??= new(Colors.Indigo);
		static ImmutableBrush ivory;
		public static SolidColorBrush Ivory => ivory ??= new(Colors.Ivory);
		static ImmutableBrush khaki;
		public static SolidColorBrush Khaki => khaki ??= new(Colors.Khaki);
		static ImmutableBrush lavender;
		public static SolidColorBrush Lavender => lavender ??= new(Colors.Lavender);
		static ImmutableBrush lavenderBlush;
		public static SolidColorBrush LavenderBlush => lavenderBlush ??= new(Colors.LavenderBlush);
		static ImmutableBrush lawnGreen;
		public static SolidColorBrush LawnGreen => lawnGreen ??= new(Colors.LawnGreen);
		static ImmutableBrush lemonChiffon;
		public static SolidColorBrush LemonChiffon => lemonChiffon ??= new(Colors.LemonChiffon);
		static ImmutableBrush lightBlue;
		public static SolidColorBrush LightBlue => lightBlue ??= new(Colors.LightBlue);
		static ImmutableBrush lightCoral;
		public static SolidColorBrush LightCoral => lightCoral ??= new(Colors.LightCoral);
		static ImmutableBrush lightCyan;
		public static SolidColorBrush LightCyan => lightCyan ??= new(Colors.LightCyan);
		static ImmutableBrush lightGoldenrodYellow;
		public static SolidColorBrush LightGoldenrodYellow => lightGoldenrodYellow ??= new(Colors.LightGoldenrodYellow);
		static ImmutableBrush lightGray;
		public static SolidColorBrush LightGray => lightGray ??= new(Colors.LightGray);
		static ImmutableBrush lightGreen;
		public static SolidColorBrush LightGreen => lightGreen ??= new(Colors.LightGreen);
		static ImmutableBrush lightPink;
		public static SolidColorBrush LightPink => lightPink ??= new(Colors.LightPink);
		static ImmutableBrush lightSalmon;
		public static SolidColorBrush LightSalmon => lightSalmon ??= new(Colors.LightSalmon);
		static ImmutableBrush lightSeaGreen;
		public static SolidColorBrush LightSeaGreen => lightSeaGreen ??= new(Colors.LightSeaGreen);
		static ImmutableBrush lightSkyBlue;
		public static SolidColorBrush LightSkyBlue => lightSkyBlue ??= new(Colors.LightSkyBlue);
		static ImmutableBrush lightSlateGray;
		public static SolidColorBrush LightSlateGray => lightSlateGray ??= new(Colors.LightSlateGray);
		static ImmutableBrush lightSteelBlue;
		public static SolidColorBrush LightSteelBlue => lightSteelBlue ??= new(Colors.LightSteelBlue);
		static ImmutableBrush lightYellow;
		public static SolidColorBrush LightYellow => lightYellow ??= new(Colors.LightYellow);
		static ImmutableBrush lime;
		public static SolidColorBrush Lime => lime ??= new(Colors.Lime);
		static ImmutableBrush limeGreen;
		public static SolidColorBrush LimeGreen => limeGreen ??= new(Colors.LimeGreen);
		static ImmutableBrush linen;
		public static SolidColorBrush Linen => linen ??= new(Colors.Linen);
		static ImmutableBrush magenta;
		public static SolidColorBrush Magenta => magenta ??= new(Colors.Magenta);
		static ImmutableBrush maroon;
		public static SolidColorBrush Maroon => maroon ??= new(Colors.Maroon);
		static ImmutableBrush mediumAquararine;
		public static SolidColorBrush MediumAquamarine => mediumAquararine ??= new(Colors.MediumAquamarine);
		static ImmutableBrush mediumBlue;
		public static SolidColorBrush MediumBlue => mediumBlue ??= new(Colors.MediumBlue);
		static ImmutableBrush mediumOrchid;
		public static SolidColorBrush MediumOrchid => mediumOrchid ??= new(Colors.MediumOrchid);
		static ImmutableBrush mediumPurple;
		public static SolidColorBrush MediumPurple => mediumPurple ??= new(Colors.MediumPurple);
		static ImmutableBrush mediumSeaGreen;
		public static SolidColorBrush MediumSeaGreen => mediumSeaGreen ??= new(Colors.MediumSeaGreen);
		static ImmutableBrush mediumSlateBlue;
		public static SolidColorBrush MediumSlateBlue => mediumSlateBlue ??= new(Colors.MediumSlateBlue);
		static ImmutableBrush mediumSpringGreen;
		public static SolidColorBrush MediumSpringGreen => mediumSpringGreen ??= new(Colors.MediumSpringGreen);
		static ImmutableBrush mediumTurquoise;
		public static SolidColorBrush MediumTurquoise => mediumTurquoise ??= new(Colors.MediumTurquoise);
		static ImmutableBrush mediumVioletRed;
		public static SolidColorBrush MediumVioletRed => mediumVioletRed ??= new(Colors.MediumVioletRed);
		static ImmutableBrush midnightBlue;
		public static SolidColorBrush MidnightBlue => midnightBlue ??= new(Colors.MidnightBlue);
		static ImmutableBrush mintCream;
		public static SolidColorBrush MintCream => mintCream ??= new(Colors.MintCream);
		static ImmutableBrush mistyRose;
		public static SolidColorBrush MistyRose => mistyRose ??= new(Colors.MistyRose);
		static ImmutableBrush moccasin;
		public static SolidColorBrush Moccasin => moccasin ??= new(Colors.Moccasin);
		static ImmutableBrush navajoWhite;
		public static SolidColorBrush NavajoWhite => navajoWhite ??= new(Colors.NavajoWhite);
		static ImmutableBrush navy;
		public static SolidColorBrush Navy => navy ??= new(Colors.Navy);
		static ImmutableBrush oldLace;
		public static SolidColorBrush OldLace => oldLace ??= new(Colors.OldLace);
		static ImmutableBrush olive;
		public static SolidColorBrush Olive => olive ??= new(Colors.Olive);
		static ImmutableBrush oliveDrab;
		public static SolidColorBrush OliveDrab => oliveDrab ??= new(Colors.OliveDrab);
		static ImmutableBrush orange;
		public static SolidColorBrush Orange => orange ??= new(Colors.Orange);
		static ImmutableBrush orangeRed;
		public static SolidColorBrush OrangeRed => orangeRed ??= new(Colors.OrangeRed);
		static ImmutableBrush orchid;
		public static SolidColorBrush Orchid => orchid ??= new(Colors.Orchid);
		static ImmutableBrush paleGoldenrod;
		public static SolidColorBrush PaleGoldenrod => paleGoldenrod ??= new(Colors.PaleGoldenrod);
		static ImmutableBrush paleGreen;
		public static SolidColorBrush PaleGreen => paleGreen ??= new(Colors.PaleGreen);
		static ImmutableBrush paleTurquoise;
		public static SolidColorBrush PaleTurquoise => paleTurquoise ??= new(Colors.PaleTurquoise);
		static ImmutableBrush paleVioletRed;
		public static SolidColorBrush PaleVioletRed => paleVioletRed ??= new(Colors.PaleVioletRed);
		static ImmutableBrush papayaWhip;
		public static SolidColorBrush PapayaWhip => papayaWhip ??= new(Colors.PapayaWhip);
		static ImmutableBrush peachPuff;
		public static SolidColorBrush PeachPuff => peachPuff ??= new(Colors.PeachPuff);
		static ImmutableBrush peru;
		public static SolidColorBrush Peru => peru ??= new(Colors.Peru);
		static ImmutableBrush pink;
		public static SolidColorBrush Pink => pink ??= new(Colors.Pink);
		static ImmutableBrush plum;
		public static SolidColorBrush Plum => plum ??= new(Colors.Plum);
		static ImmutableBrush powderBlue;
		public static SolidColorBrush PowderBlue => powderBlue ??= new(Colors.PowderBlue);
		static ImmutableBrush purple;
		public static SolidColorBrush Purple => purple ??= new(Colors.Purple);
		static ImmutableBrush red;
		public static SolidColorBrush Red => red ??= new(Colors.Red);
		static ImmutableBrush rosyBrown;
		public static SolidColorBrush RosyBrown => rosyBrown ??= new(Colors.RosyBrown);
		static ImmutableBrush royalBlue;
		public static SolidColorBrush RoyalBlue => royalBlue ??= new(Colors.RoyalBlue);
		static ImmutableBrush saddleBrown;
		public static SolidColorBrush SaddleBrown => saddleBrown ??= new(Colors.SaddleBrown);
		static ImmutableBrush salmon;
		public static SolidColorBrush Salmon => salmon ??= new(Colors.Salmon);
		static ImmutableBrush sandyBrown;
		public static SolidColorBrush SandyBrown => sandyBrown ??= new(Colors.SandyBrown);
		static ImmutableBrush seaGreen;
		public static SolidColorBrush SeaGreen => seaGreen ??= new(Colors.SeaGreen);
		static ImmutableBrush seaShell;
		public static SolidColorBrush SeaShell => seaShell ??= new(Colors.SeaShell);
		static ImmutableBrush sienna;
		public static SolidColorBrush Sienna => sienna ??= new(Colors.Sienna);
		static ImmutableBrush silver;
		public static SolidColorBrush Silver => silver ??= new(Colors.Silver);
		static ImmutableBrush skyBlue;
		public static SolidColorBrush SkyBlue => skyBlue ??= new(Colors.SkyBlue);
		static ImmutableBrush slateBlue;
		public static SolidColorBrush SlateBlue => slateBlue ??= new(Colors.SlateBlue);
		static ImmutableBrush slateGray;
		public static SolidColorBrush SlateGray => slateGray ??= new(Colors.SlateGray);
		static ImmutableBrush snow;
		public static SolidColorBrush Snow => snow ??= new(Colors.Snow);
		static ImmutableBrush springGreen;
		public static SolidColorBrush SpringGreen => springGreen ??= new(Colors.SpringGreen);
		static ImmutableBrush steelBlue;
		public static SolidColorBrush SteelBlue => steelBlue ??= new(Colors.SteelBlue);
		static ImmutableBrush tan;
		public static SolidColorBrush Tan => tan ??= new(Colors.Tan);
		static ImmutableBrush teal;
		public static SolidColorBrush Teal => teal ??= new(Colors.Teal);
		static ImmutableBrush thistle;
		public static SolidColorBrush Thistle => thistle ??= new(Colors.Thistle);
		static ImmutableBrush tomato;
		public static SolidColorBrush Tomato => tomato ??= new(Colors.Tomato);
		static ImmutableBrush transparent;
		public static SolidColorBrush Transparent => transparent ??= new(Colors.Transparent);
		static ImmutableBrush turquoise;
		public static SolidColorBrush Turquoise => turquoise ??= new(Colors.Turquoise);
		static ImmutableBrush violet;
		public static SolidColorBrush Violet => violet ??= new(Colors.Violet);
		static ImmutableBrush wheat;
		public static SolidColorBrush Wheat => wheat ??= new(Colors.Wheat);
		static ImmutableBrush white;
		public static SolidColorBrush White => white ??= new(Colors.White);
		static ImmutableBrush whiteSmoke;
		public static SolidColorBrush WhiteSmoke => whiteSmoke ??= new(Colors.WhiteSmoke);
		static ImmutableBrush yellow;
		public static SolidColorBrush Yellow => yellow ??= new(Colors.Yellow);
		static ImmutableBrush yellowGreen;
		public static SolidColorBrush YellowGreen => yellowGreen ??= new(Colors.YellowGreen);
	}
}