name: 'Triage Generate Prompt'
description: 'Generates a prompt file from a template using provided labels and parameters.'

inputs:
  token:
    description: 'GitHub token to use for authentication'
    required: false
    default: ${{ github.token }}
  template:
    description: 'Path to the prompt template file'
    required: true
  output:
    description: 'Path to the output prompt file'
    required: true
  # variable replacement inputs
  # TODO: make this be a multiline mapping input:
  #       NAME1=value1
  #       NAME2=value2
  label-prefix:
    description: 'Prefix for label search (e.g., platform/, area-, etc.)'
    required: false
    default: ''
  label:
    description: 'The label to apply to an issue'
    required: false
    default: ''

outputs:
  prompt:
    description: 'The generated prompt file path'
    value: ${{ steps.create-prompt.outputs.prompt }}

runs:
  using: 'composite'
  steps:

    - name: Create prompt file
      id: create-prompt
      shell: pwsh
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        "Create prompt file"
        echo "::group::Create prompt file"
        ${{ github.action_path }}/process-prompt-template.ps1 `
          -LabelPrefix "${{ inputs.label-prefix }}" `
          -Label "${{ inputs.label }}" `
          -Template "${{ inputs.template }}" `
          -Output "${{ inputs.output }}"
        "prompt=${{ inputs.output }}" >> $env:GITHUB_OUTPUT
        echo "::endgroup::"

    - name: Print prompt file
      shell: pwsh
      run: |
        "Print prompt file"
        echo "::group::Print prompt file"
        cat "${{ steps.create-prompt.outputs.prompt }}"
        echo "::endgroup::"
