<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <IsUnitTestProject>true</IsUnitTestProject>
    <RootNamespace>DotNet.Release.Maestro.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DotNet.Release.Maestro\DotNet.Release.Maestro.csproj" />
  </ItemGroup>

</Project>
