name: Bug Report
description: File a bug report
labels: ["t/bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please make sure to add as much detail as you can, preferably with a [reproduction](https://github.com/dotnet/maui/blob/main/.github/repro.md). This will help us diagnose the issue faster and thus resolve it quicker.
        
        If this is a bug in Xamarin.Forms, please [open the issue in the Xamarin.Forms repo](https://github.com/xamarin/Xamarin.Forms/issues/new?assignees=&labels=s%2Funverified%2C+t%2Fbug+%3Abug%3A&template=bug_report.md&title=[Bug]+).
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please give us a detailed description of the issue that you're seeing. You can add screenshots and videos as well.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to Reproduce
      description: Describe all the steps we need to take to show the behavior that you have observed. Also, include what you expected to happen and what did actually happen.
      placeholder: | 
        1. Create a File > New .NET MAUI App
        2. Add a `Button` like so: `<Button Text="this is a bug" />`
        3. Click the added button and observe the bug 🐞
        
        Expected outcome: a bug was added
        Actual outcome: a ladybug appeared
    validations:
      required: false
  - type: input
    id: repro-link
    attributes:
      label: Link to public reproduction project repository
      description: Add a link to a public [reproduction project](https://github.com/dotnet/maui/blob/main/.github/repro.md) repository. Attached zip files cannot be opened by us.
    validations:
      required: false
  - type: dropdown
    id: version-with-bug
    attributes:
      label: Version with bug
      description: In what version do you see this issue? Run `dotnet workload list` to find your version.
      options:
        - 
        - 9.0.0-preview.2.10293
        - 9.0.0-preview.1.9973
        - 8.0.20 SR4
        - 8.0.14 SR3.1
        - 8.0.10 SR3
        - 8.0.7 SR2
        - 8.0.6 SR1
        - 8.0.3 GA
        - 7.0.101
        - 7.0.100
        - 7.0.96
        - 7.0.92
        - 7.0.86
        - 7.0.81
        - 7.0.59
        - 7.0.58
        - 7.0.52
        - 7.0.49
        - Nightly / CI build (Please specify exact version)
        - Unknown/Other
    validations:
      required: true
  - type: dropdown
    id: is-regression
    attributes:
      label: Is this a regression from previous behavior? 
      description: In other words, did this work before an update or migration and now does not?
      multiple: true
      options:
        - Yes, this used to work in .NET MAUI
        - Yes, this used to work in Xamarin.Forms
        - No, this is something new
        - Not sure, did not test other versions
    validations:
      required: true
  - type: dropdown
    id: version-that-worked
    attributes:
      label: Last version that worked well
      description: If you answered yes, is there a version on which this _did_ work, which one? If no or unknown, please select `Unknown/Other`.  Run `dotnet workload list` to find your version.
      options:
        - 
        - Unknown/Other
        - 6.0
        - 7.0.49
        - 7.0.52
        - 7.0.58
        - 7.0.59
        - 7.0.81
        - 7.0.86
        - 7.0.92
        - 7.0.96
        - 7.0.100
        - 7.0.101
        - 8.0.0-preview.1.7762
        - 8.0.0-preview.2.7871
        - 8.0.0-preview.3.8149
        - 8.0.0-preview.4.8333
        - 8.0.0-preview.5.8529
        - 8.0.0-preview.6.8686
        - 8.0.0-preview.7.8842
        - 8.0.0-rc.1.9171
        - 8.0.0-rc.2.9373
        - 8.0.0-rc.2.9511
        - 8.0.3 GA
        - 8.0.6 SR1
        - 8.0.7 SR2        
        - 8.0.10 SR3
        - 8.0.14 SR3.1
        - 8.0.20 SR4
        - 9.0.0-preview.1.9973
        - 9.0.0-preview.2.10293
    validations:
      required: true
  - type: dropdown
    id: platforms-affected
    attributes:
      label: Affected platforms
      description: Select all or any platform that you see this issue on. This helps us determine if it's something platform-specific or in the core. If you were only able to test on 1 platform, please check the last option to inform us about that.
      multiple: true
      options:
        - iOS
        - Android
        - Windows
        - macOS
        - Other (Tizen, Linux, etc. not supported by Microsoft directly)
        - I was *not* able test on other platforms
    validations:
      required: true
  - type: input
    id: platform-versions
    attributes:
      label: Affected platform versions
      description: Please provide the version numbers of the platforms you see this issue on.
      placeholder: E.g. iOS 15, Android 11 and up, Windows SDK 10.0.17134.0, etc.
    validations:
      required: false
  - type: textarea
    id: workaround
    attributes:
      label: Did you find any workaround?
      description: Did you find any workaround for this issue? This can unblock other people while waiting for this issue to be resolved or even give us a hint on how to fix this.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Including a binary log or 'binlog' to your issue (see [Capturing Binary Logs](https://github.com/dotnet/maui/wiki/Capturing-Binary-Logs) for more info) is helpful in diagnosing your issue.  You can also paste any relevant log output below. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: markdown
    attributes:
      value: |
        By opening the issue you agree to follow this project's [Code of Conduct](https://github.com/dotnet/maui/blob/main/.github/CODE_OF_CONDUCT.md)
