using System;
using Microsoft.Maui.Graphics;
using Xunit;

// Simulates the attribute from CommunityToolkit.MAUI
namespace CommunityToolkit.Maui
{
	public class BindablePropertyAttribute : Attribute
	{
		public string PropertyName { get; set; }
	}
}

namespace Microsoft.Maui.Controls.Xaml.UnitTests
{

/// <summary>
/// Custom Label with a property that has [BindableProperty] attribute.
/// Simulates the scenario where CommunityToolkit.MAUI generates the BindableProperty field.
/// In this test we manually define the BindableProperty to simulate the runtime behavior.
/// </summary>
public class Maui33835Label : Label
{
	[CommunityToolkit.Maui.BindableProperty]
	public Color MyColor
	{
		get => (Color)GetValue(MyColorProperty);
		set => SetValue(MyColorProperty, value);
	}

	// This would normally be generated by CommunityToolkit.MAUI SG
	// We define it manually so the test can run at runtime
	public static readonly BindableProperty MyColorProperty =
		BindableProperty.Create(nameof(MyColor), typeof(Color), typeof(Maui33835Label), default(Color));
}

public partial class Maui33835 : ContentPage
{
	public Maui33835()
	{
		InitializeComponent();
	}

	[Collection("Issue")]
	public class Tests
	{
		[Theory]
		[XamlInflatorData]
		internal void StyleSetterSetsValueOnPropertyWithBindablePropertyAttribute(XamlInflator inflator)
		{
			var page = new Maui33835(inflator);

			Assert.NotNull(page);
			Assert.NotNull(page.testLabel);

			// Verify the Style Setter actually set the MyColor property to Red
			Assert.Equal(Colors.Red, page.testLabel.MyColor);
		}
	}
}

}
