using System;
using System.Collections.Generic;
using CommunityToolkit.Mvvm.ComponentModel;
using Microsoft.Maui.Controls.Internals;
using Microsoft.Maui.Dispatching;
using Microsoft.Maui.UnitTests;
using Xunit;

#nullable enable

namespace Microsoft.Maui.Controls.Xaml.UnitTests;

/// <summary>
/// Test model for Maui33826
/// </summary>
public class Maui33826Project
{
	public int Id { get; set; }
	public string Name { get; set; } = string.Empty;
}

/// <summary>
/// ViewModel using CommunityToolkit.Mvvm's [ObservableProperty] attribute.
/// The SelectedProject property is generated by the CommunityToolkit source generator.
/// MAUI's SourceGen should detect this and generate a setter for typed bindings.
/// </summary>
public partial class Maui33826ViewModel : ObservableObject
{
	[ObservableProperty]
	private List<Maui33826Project> _projects = [];

	[ObservableProperty]
	private Maui33826Project? _selectedProject;
}

public partial class Maui33826 : ContentPage
{
	public Maui33826()
	{
		InitializeComponent();
	}

	[Collection("Xaml Inflation")]
	public class Tests : IDisposable
	{
		public Tests() => DispatcherProvider.SetCurrent(new DispatcherProviderStub());
		public void Dispose() => DispatcherProvider.SetCurrent(null);

		[Theory]
		[XamlInflatorData]
		internal void SelectedItemBindingHasSetter(XamlInflator inflator)
		{
			// Arrange
			var project1 = new Maui33826Project { Id = 1, Name = "Project 1" };
			var project2 = new Maui33826Project { Id = 2, Name = "Project 2" };
			
			var vm = new Maui33826ViewModel
			{
				Projects = [project1, project2]
			};

			var page = new Maui33826(inflator)
			{
				BindingContext = vm
			};

			// Act - Simulate selecting an item in the CollectionView
			// This should update vm.SelectedProject via the TwoWay binding
			page.collectionView.SelectedItem = project1;

			// Assert - The binding should have updated the ViewModel property
			// If SourceGen doesn't generate a setter, SelectedProject will remain null
			Assert.NotNull(vm.SelectedProject);
			Assert.Equal(project1.Id, vm.SelectedProject.Id);
			Assert.Equal("Project 1", vm.SelectedProject.Name);
		}

		[Theory]
		[XamlInflatorData]
		internal void SelectedItemBindingUpdatesFromViewModel(XamlInflator inflator)
		{
			// Arrange
			var project1 = new Maui33826Project { Id = 1, Name = "Project 1" };
			var project2 = new Maui33826Project { Id = 2, Name = "Project 2" };
			
			var vm = new Maui33826ViewModel
			{
				Projects = [project1, project2],
				SelectedProject = project1
			};

			var page = new Maui33826(inflator)
			{
				BindingContext = vm
			};

			// Assert - The CollectionView should reflect the ViewModel's SelectedProject
			Assert.Equal(project1, page.collectionView.SelectedItem);

			// Act - Update ViewModel
			vm.SelectedProject = project2;

			// Assert - CollectionView should update (OneWay direction - getter works)
			Assert.Equal(project2, page.collectionView.SelectedItem);
		}
	}
}
