#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Posts or updates a write-tests comment on a GitHub Issue or Pull Request.

.DESCRIPTION
    Creates ONE comment documenting tests created for an issue.
    Uses HTML marker <!-- WRITE-TESTS-COMMENT --> for identification.
    
    If an existing write-tests comment exists, it will be EDITED.
    Otherwise, a new comment will be created.
    
    Format:
    ## 🧪 UI Tests Created for Issue #XXXXX
    <!-- WRITE-TESTS-COMMENT -->
    
    ### Test Details
    ... test information ...

.PARAMETER IssueNumber
    The issue number to post comment on (required)

.PARAMETER TestDescription
    Brief description of what the test verifies (required)

.PARAMETER HostAppFile
    Path to the HostApp test page file (required)

.PARAMETER TestFile
    Path to the NUnit test file (required)

.PARAMETER TestMethod
    Name of the test method (required)

.PARAMETER Category
    UITestCategories category used (required)

.PARAMETER VerificationStatus
    Status: "Verified" (tests fail without fix), "Unverified" (not yet run), "Inconclusive" (required)

.PARAMETER Platforms
    Platforms the test runs on (e.g., "All", "iOS, Android") (optional)

.PARAMETER Notes
    Additional notes about the test (optional)

.PARAMETER DryRun
    Print comment instead of posting

.EXAMPLE
    ./post-write-tests-comment.ps1 -IssueNumber 33331 `
        -TestDescription "Verifies Picker.IsOpen property changes correctly when picker opens/closes" `
        -HostAppFile "src/Controls/tests/TestCases.HostApp/Issues/Issue33331.cs" `
        -TestFile "src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue33331.cs" `
        -TestMethod "PickerIsOpenPropertyChanges" `
        -Category "Picker" `
        -VerificationStatus "Verified"
#>

param(
    [Parameter(Mandatory=$true)]
    [int]$IssueNumber,

    [Parameter(Mandatory=$true)]
    [string]$TestDescription,

    [Parameter(Mandatory=$true)]
    [string]$HostAppFile,

    [Parameter(Mandatory=$true)]
    [string]$TestFile,

    [Parameter(Mandatory=$true)]
    [string]$TestMethod,

    [Parameter(Mandatory=$true)]
    [string]$Category,

    [Parameter(Mandatory=$true)]
    [ValidateSet("Verified", "Unverified", "Inconclusive")]
    [string]$VerificationStatus,

    [Parameter(Mandatory=$false)]
    [string]$Platforms = "All",

    [Parameter(Mandatory=$false)]
    [string]$Notes,

    [Parameter(Mandatory=$false)]
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

Write-Host "╔═══════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║  Write-Tests Comment (Post/Update)                        ║" -ForegroundColor Cyan
Write-Host "╚═══════════════════════════════════════════════════════════╝" -ForegroundColor Cyan

# Status emoji mapping
$statusEmoji = switch ($VerificationStatus) {
    "Verified" { "✅ Verified - Tests fail without fix" }
    "Unverified" { "⏳ Unverified - Tests not yet run" }
    "Inconclusive" { "⚠️ Inconclusive - See notes" }
    default { $VerificationStatus }
}

# Build the comment body
$commentBody = @"
## 🧪 UI Tests Created for Issue #$IssueNumber

<!-- WRITE-TESTS-COMMENT -->

### Test Details

| Property | Value |
|----------|-------|
| **Description** | $TestDescription |
| **Test Method** | ``$TestMethod`` |
| **Category** | ``UITestCategories.$Category`` |
| **Platforms** | $Platforms |
| **Status** | $statusEmoji |

### Files Created

| File | Purpose |
|------|---------|
| ``$HostAppFile`` | HostApp page (UI reproduction) |
| ``$TestFile`` | NUnit test (Appium automation) |

"@

if (-not [string]::IsNullOrWhiteSpace($Notes)) {
    $commentBody += @"
### Notes

$Notes

"@
}

$commentBody += @"
---
<sub>🤖 Generated by Copilot CLI write-tests skill</sub>
"@

# Check for existing write-tests comment on the issue
Write-Host "`nChecking for existing write-tests comment on issue #$IssueNumber..." -ForegroundColor Yellow
$existingCommentId = $null

try {
    # Get all comments and find one with our marker
    $commentsJson = gh api "repos/dotnet/maui/issues/$IssueNumber/comments" 2>$null
    $comments = $commentsJson | ConvertFrom-Json
    
    foreach ($comment in $comments) {
        if ($comment.body -match "<!-- WRITE-TESTS-COMMENT -->") {
            $existingCommentId = $comment.id
            Write-Host "✓ Found existing write-tests comment (ID: $existingCommentId)" -ForegroundColor Green
            break
        }
    }
    
    if (-not $existingCommentId) {
        Write-Host "✓ No existing write-tests comment found - will create new" -ForegroundColor Yellow
    }
} catch {
    Write-Host "✓ No existing write-tests comment found - will create new" -ForegroundColor Yellow
}

if ($DryRun) {
    Write-Host "`n=== COMMENT PREVIEW ===" -ForegroundColor Yellow
    Write-Host $commentBody
    Write-Host "`n=== END PREVIEW ===" -ForegroundColor Yellow
    exit 0
}

# Write to temp file to avoid shell escaping issues
$tempFile = [System.IO.Path]::GetTempFileName()
@{ body = $commentBody } | ConvertTo-Json -Depth 10 | Set-Content -Path $tempFile -Encoding UTF8

if ($existingCommentId) {
    Write-Host "Updating comment ID $existingCommentId..." -ForegroundColor Yellow
    $result = gh api --method PATCH "repos/dotnet/maui/issues/comments/$existingCommentId" --input $tempFile --jq '.html_url'
    Write-Host "✅ Comment updated: $result" -ForegroundColor Green
} else {
    Write-Host "Posting new comment to issue #$IssueNumber..." -ForegroundColor Yellow
    $result = gh api --method POST "repos/dotnet/maui/issues/$IssueNumber/comments" --input $tempFile --jq '.html_url'
    Write-Host "✅ Comment posted: $result" -ForegroundColor Green
}

Remove-Item $tempFile
