using System;
using System.IO;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.Maui.Controls.Xaml.UnitTests.SourceGen;
using Xunit;
using Xunit.Abstractions;

using static Microsoft.Maui.Controls.Xaml.UnitTests.SourceGen.SourceGeneratorDriver;

namespace Microsoft.Maui.Controls.SourceGen.UnitTests;

/// <summary>
/// Tests for Style Setter targeting partial properties (C# 13).
/// 
/// Bug: XSG throws "The method or operation is not implemented" (MAUIG1001) when:
/// - A partial property is declared with [BindableProperty] attribute (CommunityToolkit.MAUI pattern)
/// - The BindableProperty field is generated by another source generator (not visible to XSG)
/// - A Style Setter targets that property using a markup extension like {StaticResource}
/// 
/// Root cause: XSG can't find the BindableProperty field, GetBindableProperty() returns null,
/// and ToFQDisplayString(null) throws NotImplementedException.
/// </summary>
public class PartialPropertyInStyleSetterTests : SourceGenXamlInitializeComponentTestBase
{
	private readonly ITestOutputHelper _output;

	public PartialPropertyInStyleSetterTests(ITestOutputHelper output)
	{
		_output = output;
	}

	/// <summary>
	/// Reproduces the bug: Style Setter with markup extension on a partial property
	/// where the BindableProperty field is not visible to XSG.
	/// 
	/// This simulates the real-world scenario where CommunityToolkit.MAUI generates
	/// the BindableProperty field, but XSG runs in parallel and can't see it.
	/// XSG should detect the [BindableProperty] attribute via heuristic and generate
	/// appropriate SetValue code.
	/// </summary>
	[Fact]
	public void StyleSetterWithMarkupExtension_OnPartialPropertyWithoutVisibleBindablePropertyField_ShouldCompile()
	{
		var xaml =
"""
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="MauiAppTestXamlSG.MainPage"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiAppTestXamlSG">

    <ContentPage.Resources>
        <ResourceDictionary>
            <Color x:Key="TestColor">Red</Color>
            <Style x:Key="MyLabelStyle" TargetType="local:MyLabel">
                <Setter Property="MyColor" Value="{StaticResource TestColor}" />
            </Style>
        </ResourceDictionary>
    </ContentPage.Resources>

    <VerticalStackLayout>
        <local:MyLabel Style="{StaticResource MyLabelStyle}" />
    </VerticalStackLayout>

</ContentPage>
""";

		// User's source code with [BindableProperty] attribute
		// The BindableProperty field and property implementation are NOT included
		// This simulates what XSG sees when CommunityToolkit.MAUI SG hasn't run yet
		// XSG should detect the attribute via heuristic
		var userCode =
"""
#nullable enable
using System;

namespace CommunityToolkit.Maui
{
    // Simulates the attribute from CommunityToolkit.MAUI
    public class BindablePropertyAttribute : Attribute
    {
        public string? PropertyName { get; set; }
    }
}

namespace MauiAppTestXamlSG;

public partial class MainPage : Microsoft.Maui.Controls.ContentPage
{
    public MainPage()
    {
        InitializeComponent();
    }
}

public partial class MyLabel : Microsoft.Maui.Controls.Label
{
    // Partial property with [BindableProperty] attribute
    // XSG doesn't see MyColorProperty field because source generators are isolated
    // But XSG should detect the attribute and use heuristic
    [CommunityToolkit.Maui.BindableProperty]
    public partial Microsoft.Maui.Graphics.Color MyColor { get; set; }
}
""";

		var compilation = CreateMauiCompilation("MauiAppTestXamlSG");
		compilation = compilation.AddSyntaxTrees(CSharpSyntaxTree.ParseText(userCode));

		var workingDirectory = Environment.CurrentDirectory;
		var xamlFile = new AdditionalXamlFile(
			Path.Combine(workingDirectory, "MainPage.xaml"), 
			xaml, 
			RelativePath: "MainPage.xaml", 
			ManifestResourceName: $"MauiAppTestXamlSG.MainPage.xaml");

		var result = RunGenerator<XamlGenerator>(compilation, xamlFile, assertNoCompilationErrors: false);
		var generated = result.Results.SingleOrDefault().GeneratedSources.SingleOrDefault(gs => gs.HintName.EndsWith(".xsg.cs")).SourceText?.ToString();

		// Output diagnostics for debugging
		foreach (var diagnostic in result.Diagnostics)
		{
			_output.WriteLine($"Diagnostic: {diagnostic.Id} {diagnostic.Severity}: {diagnostic.GetMessage()}");
		}
		_output.WriteLine($"Generated .xsg.cs: {(generated != null ? "yes" : "no")}");

		// Should not produce any errors - XSG should handle missing BindableProperty gracefully
		var errors = result.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).ToList();
		Assert.Empty(errors);

		// Should generate the InitializeComponent method
		Assert.NotNull(generated);
		Assert.Contains("InitializeComponent", generated, StringComparison.Ordinal);
	}

	/// <summary>
	/// Control test: Same scenario but WITH the BindableProperty field visible.
	/// This should always compile successfully.
	/// </summary>
	[Fact]
	public void StyleSetterWithMarkupExtension_OnPartialPropertyWithVisibleBindablePropertyField_ShouldCompile()
	{
		var xaml =
"""
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="MauiAppTestXamlSG.MainPage"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiAppTestXamlSG">

    <ContentPage.Resources>
        <ResourceDictionary>
            <Color x:Key="TestColor">Red</Color>
            <Style x:Key="MyLabelStyle" TargetType="local:MyLabel">
                <Setter Property="MyColor" Value="{StaticResource TestColor}" />
            </Style>
        </ResourceDictionary>
    </ContentPage.Resources>

    <VerticalStackLayout>
        <local:MyLabel Style="{StaticResource MyLabelStyle}" />
    </VerticalStackLayout>

</ContentPage>
""";

		// Complete code WITH the BindableProperty field visible
		var code =
"""
#nullable enable
namespace MauiAppTestXamlSG;

public partial class MainPage : Microsoft.Maui.Controls.ContentPage
{
    public MainPage()
    {
        InitializeComponent();
    }
}

public partial class MyLabel : Microsoft.Maui.Controls.Label
{
    // BindableProperty field is visible
    public static readonly Microsoft.Maui.Controls.BindableProperty MyColorProperty = 
        Microsoft.Maui.Controls.BindableProperty.Create(
            nameof(MyColor), typeof(Microsoft.Maui.Graphics.Color), typeof(MyLabel), null);

    public partial Microsoft.Maui.Graphics.Color MyColor { get; set; }
}

public partial class MyLabel
{
    public partial Microsoft.Maui.Graphics.Color MyColor
    {
        get => (Microsoft.Maui.Graphics.Color)GetValue(MyColorProperty);
        set => SetValue(MyColorProperty, value);
    }
}
""";

		var compilation = CreateMauiCompilation("MauiAppTestXamlSG");
		compilation = compilation.AddSyntaxTrees(CSharpSyntaxTree.ParseText(code));

		var workingDirectory = Environment.CurrentDirectory;
		var xamlFile = new AdditionalXamlFile(
			Path.Combine(workingDirectory, "MainPage.xaml"), 
			xaml, 
			RelativePath: "MainPage.xaml", 
			ManifestResourceName: $"MauiAppTestXamlSG.MainPage.xaml");

		var result = RunGenerator<XamlGenerator>(compilation, xamlFile, assertNoCompilationErrors: false);
		var generated = result.Results.SingleOrDefault().GeneratedSources.SingleOrDefault(gs => gs.HintName.EndsWith(".xsg.cs")).SourceText?.ToString();

		// Output for debugging
		foreach (var diagnostic in result.Diagnostics)
		{
			_output.WriteLine($"Diagnostic: {diagnostic.Id} {diagnostic.Severity}: {diagnostic.GetMessage()}");
		}

		// Should not produce any errors
		Assert.Empty(result.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error));

		// Should generate the InitializeComponent method
		Assert.NotNull(generated);
		Assert.Contains("InitializeComponent", generated, StringComparison.Ordinal);
	}

	/// <summary>
	/// Style Setter with simple value (no markup extension) on a partial property.
	/// This should work even without BindableProperty visible because SetterValueProvider
	/// has a different code path for simple values.
	/// </summary>
	[Fact]
	public void StyleSetterWithSimpleValue_OnPartialProperty_ShouldCompile()
	{
		var xaml =
"""
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="TestApp.TestPage"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:TestApp">

    <ContentPage.Resources>
        <ResourceDictionary>
            <Style x:Key="MyLabelStyle" TargetType="local:MyLabel">
                <Setter Property="MyText" Value="Hello from Style" />
            </Style>
        </ResourceDictionary>
    </ContentPage.Resources>

    <VerticalStackLayout>
        <local:MyLabel Text="Hello" Style="{StaticResource MyLabelStyle}" />
    </VerticalStackLayout>

</ContentPage>
""";

		var code =
"""
using Microsoft.Maui.Controls;

namespace TestApp
{
    public partial class TestPage : ContentPage
    {
        public TestPage()
        {
            InitializeComponent();
        }
    }

    public partial class MyLabel : Label
    {
        public static readonly BindableProperty MyTextProperty = BindableProperty.Create(
            nameof(MyText), typeof(string), typeof(MyLabel), null);

        public partial string MyText { get; set; }
    }

    public partial class MyLabel
    {
        public partial string MyText
        {
            get => (string)GetValue(MyTextProperty);
            set => SetValue(MyTextProperty, value);
        }
    }
}
""";

		var (result, generated) = RunGenerator(xaml, code);

		// Should not produce any errors
		Assert.Empty(result.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error));

		// Should generate the InitializeComponent method
		Assert.NotNull(generated);
		Assert.Contains("InitializeComponent", generated, StringComparison.Ordinal);
	}
}
