using System;
using System.IO;
using System.Linq;
using Xunit;

namespace Microsoft.Maui.Controls.SourceGen.UnitTests;

public class ResourceDictionary : SourceGenXamlInitializeComponentTestBase
{
	[Fact]
	public void ResourceDictionaryWithoutXClass()
    {
        var xaml =
"""
<?xml version="1.0" encoding="utf-8" ?>
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="using:Microsoft.Maui.Controls.Xaml.UnitTests"> 
  <Color x:Key="AccentColor">#FF4B14</Color>
</ResourceDictionary>
""";
		var expected =
"""
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a .NET MAUI source generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#pragma warning disable CS0219 // Variable is assigned but its value is never used

namespace __XamlGeneratedCode__;

public partial class __TypeDBD64C1C77CDA760
{
	private partial void InitializeComponent()
	{
		// Fallback to Runtime inflation if the page was updated by HotReload
		static string? getPathForType(global::System.Type type)
		{
			var assembly = type.Assembly;
			foreach (var xria in global::System.Reflection.CustomAttributeExtensions.GetCustomAttributes<global::Microsoft.Maui.Controls.Xaml.XamlResourceIdAttribute>(assembly))
			{
				if (xria.Type == type)
					return xria.Path;
			}
			return null;
		}

		var rlr = global::Microsoft.Maui.Controls.Internals.ResourceLoader.ResourceProvider2?.Invoke(new global::Microsoft.Maui.Controls.Internals.ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(global::__XamlGeneratedCode__.__TypeDBD64C1C77CDA760).Assembly.GetName(),
			ResourcePath = getPathForType(typeof(global::__XamlGeneratedCode__.__TypeDBD64C1C77CDA760)),
			Instance = this,
		});

		if (rlr?.ResourceContent != null)
		{
			this.InitializeComponentRuntime();
			return;
		}

		var color = new global::Microsoft.Maui.Graphics.Color(1f, 0.29411766f, 0.078431375f, 1f) /* #FF4B14 */;
		global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(color!, new global::System.Uri(@"Styles.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 6, 4);
		var __root = this;
		global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(__root!, new global::System.Uri(@"Styles.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 2, 2);
#if !_MAUIXAML_SG_NAMESCOPE_DISABLE
		global::Microsoft.Maui.Controls.Internals.INameScope iNameScope = new global::Microsoft.Maui.Controls.Internals.NameScope();
#endif
		__root["AccentColor"] = color;
	}
}

""";

		var (result, generated) = RunGenerator(xaml, "", path: "Styles.xaml");
		Assert.False(result.Diagnostics.Any());

		Assert.Equal(expected, generated, ignoreLineEndingDifferences: true);
		
    }

	[Fact]
	public void StaticResourcesAndConversion()
    {
        var xaml =
"""
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:Microsoft.Maui.Controls.Xaml.UnitTests"
             xmlns:System="clr-namespace:System;assembly=mscorlib" 
             x:Class="Microsoft.Maui.Controls.Xaml.UnitTests.Maui20244">
    <ContentPage.Resources>
        <x:String x:Key="GridRowDef">*, *, *, *, *, auto</x:String>
    </ContentPage.Resources>

            
	<Grid x:Name="grid" RowDefinitions="{StaticResource GridRowDef}" />
</ContentPage>
""";
		var code =
"""
using System;
using Microsoft.Maui.Controls;
using Microsoft.Maui.Controls.Xaml;

namespace Test;

[XamlProcessing(XamlInflator.SourceGen)]
public partial class TestPage : ContentPage
{
	public TestPage()
	{
		InitializeComponent();
	}
}

public class EventToCommandBehavior : Behavior
{
	public static readonly BindableProperty EventNameProperty;

    // Key here is that this is a nullable string property, this was causing issues
	public string? EventName { get; set; }
}
""";
		var testXamlFilePath = Path.Combine(Environment.CurrentDirectory, "Test.xaml");

		var expected =
$$"""
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a .NET MAUI source generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#pragma warning disable CS0219 // Variable is assigned but its value is never used

namespace Microsoft.Maui.Controls.Xaml.UnitTests;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Maui.Controls.SourceGen, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null", "10.0.0.0")]
public partial class Maui20244
{
	private partial void InitializeComponent()
	{
		// Fallback to Runtime inflation if the page was updated by HotReload
		static string? getPathForType(global::System.Type type)
		{
			var assembly = type.Assembly;
			foreach (var xria in global::System.Reflection.CustomAttributeExtensions.GetCustomAttributes<global::Microsoft.Maui.Controls.Xaml.XamlResourceIdAttribute>(assembly))
			{
				if (xria.Type == type)
					return xria.Path;
			}
			return null;
		}

		var rlr = global::Microsoft.Maui.Controls.Internals.ResourceLoader.ResourceProvider2?.Invoke(new global::Microsoft.Maui.Controls.Internals.ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(global::Microsoft.Maui.Controls.Xaml.UnitTests.Maui20244).Assembly.GetName(),
			ResourcePath = getPathForType(typeof(global::Microsoft.Maui.Controls.Xaml.UnitTests.Maui20244)),
			Instance = this,
		});

		if (rlr?.ResourceContent != null)
		{
			this.InitializeComponentRuntime();
			return;
		}

		string string0 = "*, *, *, *, *, auto";
		global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(string0!, new global::System.Uri(@"Test.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 8, 10);
		var staticResourceExtension = new global::Microsoft.Maui.Controls.Xaml.StaticResourceExtension();
		global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(staticResourceExtension!, new global::System.Uri(@"Test.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 12, 22);
		var grid = new global::Microsoft.Maui.Controls.Grid();
		global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(grid!, new global::System.Uri(@"Test.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 12, 3);
		var __root = this;
		global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(__root!, new global::System.Uri(@"Test.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 2, 2);
#if !_MAUIXAML_SG_NAMESCOPE_DISABLE
		global::Microsoft.Maui.Controls.Internals.INameScope iNameScope = global::Microsoft.Maui.Controls.Internals.NameScope.GetNameScope(__root) ?? new global::Microsoft.Maui.Controls.Internals.NameScope();
#endif
#if !_MAUIXAML_SG_NAMESCOPE_DISABLE
		global::Microsoft.Maui.Controls.Internals.NameScope.SetNameScope(__root, iNameScope);
#endif
#if !_MAUIXAML_SG_NAMESCOPE_DISABLE
		grid.transientNamescope = iNameScope;
#endif
#if !_MAUIXAML_SG_NAMESCOPE_DISABLE
		iNameScope.RegisterName("grid", grid);
#endif
		grid.StyleId ??= "grid";
		this.grid = grid;
		__root.Resources["GridRowDef"] = string0;
#line 12 "{{testXamlFilePath}}"
		staticResourceExtension.Key = "GridRowDef";
#line default
		var rowDefinitionCollection = new global::Microsoft.Maui.Controls.RowDefinitionCollection([new global::Microsoft.Maui.Controls.RowDefinition(global::Microsoft.Maui.GridLength.Star), new global::Microsoft.Maui.Controls.RowDefinition(global::Microsoft.Maui.GridLength.Star), new global::Microsoft.Maui.Controls.RowDefinition(global::Microsoft.Maui.GridLength.Star), new global::Microsoft.Maui.Controls.RowDefinition(global::Microsoft.Maui.GridLength.Star), new global::Microsoft.Maui.Controls.RowDefinition(global::Microsoft.Maui.GridLength.Star), new global::Microsoft.Maui.Controls.RowDefinition(global::Microsoft.Maui.GridLength.Auto)]);
		if (global::Microsoft.Maui.VisualDiagnostics.GetSourceInfo(rowDefinitionCollection!) == null)
			global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(rowDefinitionCollection!, new global::System.Uri(@"Test.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 12, 22);
#line 12 "{{testXamlFilePath}}"
		grid.SetValue(global::Microsoft.Maui.Controls.Grid.RowDefinitionsProperty, rowDefinitionCollection);
#line default
#line 12 "{{testXamlFilePath}}"
		__root.SetValue(global::Microsoft.Maui.Controls.ContentPage.ContentProperty, grid);
#line default
	}
}

""";

		var (result, generated) = RunGenerator(xaml, code);
		Assert.False(result.Diagnostics.Any());
		Assert.Equal(expected, generated, ignoreLineEndingDifferences: true);
	}
}
