using System;
using System.IO;
using System.Linq;
using Xunit;

namespace Microsoft.Maui.Controls.SourceGen.UnitTests;

public class UnresolvedType : SourceGenXamlInitializeComponentTestBase
{
	[Fact]
	public void UnresolvedWithClrNamespace()
	{
		var xaml =
"""
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:components="clr-namespace:mauiblazor.Components"
			 x:Class="Test.TestPage">
    <BlazorWebView x:Name="blazorWebView" HostPage="wwwroot/index.html">
        <BlazorWebView.RootComponents>
            <RootComponent Selector="#app" ComponentType="{x:Type components:Routes}" />
        </BlazorWebView.RootComponents>
    </BlazorWebView>
</ContentPage>
""";

		var code =
"""
using System;
using Microsoft.Maui.Controls;
using Microsoft.Maui.Controls.Xaml;

namespace Test;

[XamlProcessing(XamlInflator.SourceGen)]
partial class TestPage : ContentPage
{
	public TestPage()
	{
		InitializeComponent();
	}
}
""";

		var testXamlFilePath = Path.Combine(Environment.CurrentDirectory, "Test.xaml");
		var expected =
$$"""
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a .NET MAUI source generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#pragma warning disable CS0219 // Variable is assigned but its value is never used

namespace Test;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Maui.Controls.SourceGen, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null", "10.0.0.0")]
public partial class TestPage
{
	private partial void InitializeComponent()
	{
		// Fallback to Runtime inflation if the page was updated by HotReload
		static string? getPathForType(global::System.Type type)
		{
			var assembly = type.Assembly;
			foreach (var xria in global::System.Reflection.CustomAttributeExtensions.GetCustomAttributes<global::Microsoft.Maui.Controls.Xaml.XamlResourceIdAttribute>(assembly))
			{
				if (xria.Type == type)
					return xria.Path;
			}
			return null;
		}

		var rlr = global::Microsoft.Maui.Controls.Internals.ResourceLoader.ResourceProvider2?.Invoke(new global::Microsoft.Maui.Controls.Internals.ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(global::Test.TestPage).Assembly.GetName(),
			ResourcePath = getPathForType(typeof(global::Test.TestPage)),
			Instance = this,
		});

		if (rlr?.ResourceContent != null)
		{
			this.InitializeComponentRuntime();
			return;
		}

		var typeExtension = typeof(global::mauiblazor.Components.Routes);
		global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(typeExtension!, new global::System.Uri(@"Test.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 8, 44);
		var rootComponent = new global::Microsoft.AspNetCore.Components.WebView.Maui.RootComponent();
		global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(rootComponent!, new global::System.Uri(@"Test.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 8, 14);
		var blazorWebView = new global::Microsoft.AspNetCore.Components.WebView.Maui.BlazorWebView();
		global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(blazorWebView!, new global::System.Uri(@"Test.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 6, 6);
		var __root = this;
		global::Microsoft.Maui.VisualDiagnostics.RegisterSourceInfo(__root!, new global::System.Uri(@"Test.xaml;assembly=SourceGeneratorDriver.Generated", global::System.UriKind.Relative), 2, 2);
#if !_MAUIXAML_SG_NAMESCOPE_DISABLE
		global::Microsoft.Maui.Controls.Internals.INameScope iNameScope = global::Microsoft.Maui.Controls.Internals.NameScope.GetNameScope(__root) ?? new global::Microsoft.Maui.Controls.Internals.NameScope();
#endif
#if !_MAUIXAML_SG_NAMESCOPE_DISABLE
		global::Microsoft.Maui.Controls.Internals.NameScope.SetNameScope(__root, iNameScope);
#endif
#if !_MAUIXAML_SG_NAMESCOPE_DISABLE
		blazorWebView.transientNamescope = iNameScope;
#endif
#if !_MAUIXAML_SG_NAMESCOPE_DISABLE
		iNameScope.RegisterName("blazorWebView", blazorWebView);
#endif
		blazorWebView.StyleId ??= "blazorWebView";
		this.blazorWebView = blazorWebView;
#line 6 "{{testXamlFilePath}}"
		blazorWebView.HostPage = "wwwroot/index.html";
#line default
#line 8 "{{testXamlFilePath}}"
		rootComponent.Selector = "#app";
#line default
#line 8 "{{testXamlFilePath}}"
		rootComponent.ComponentType = (global::System.Type)typeExtension;
#line default
#line 8 "{{testXamlFilePath}}"
		((global::System.Collections.ObjectModel.Collection<global::Microsoft.AspNetCore.Components.WebView.Maui.RootComponent>)blazorWebView.RootComponents).Add((global::Microsoft.AspNetCore.Components.WebView.Maui.RootComponent)rootComponent);
#line default
#line 6 "{{testXamlFilePath}}"
		__root.SetValue(global::Microsoft.Maui.Controls.ContentPage.ContentProperty, blazorWebView);
#line default
	}
}

""";

		var (result, generated) = RunGenerator(xaml, code, assertNoCompilationErrors: false);
		Assert.False(result.Diagnostics.Any());
		Assert.Equal(expected, generated, ignoreLineEndingDifferences: true);
	}
}