name: 'Triage Labels Action'

description: 'Process issues and apply labels using AI inference'

inputs:
  issue:
    description: 'The issue number to triage'
    required: false
    default: ''
  token:
    description: 'GitHub token to use for authentication'
    required: true

outputs:
  labels:
    description: 'The labels to apply to the issue'
    value: ${{ steps.inference.outputs.response }}
  labels-file:
    description: 'The file taht contains the labels to apply to the issue'
    value: ${{ steps.inference.outputs.response-file }}

runs:
  using: 'composite'
  steps:

    - name: Get Issue Data
      id: issue-data
      uses: actions/github-script@v7
      with:
        script: |
          const issueNumber = '${{ inputs.issue }}' || github.event.issue.number;
          const issue = await github.rest.issues.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber
          });

          const data = issue.data;
          const json = JSON.stringify(data, null, 2);

          const fs = require('fs');
          io.mkdirP('${{ runner.temp }}/apply-label');
          fs.writeFileSync('${{ runner.temp }}/apply-label/issue.json', json);

          return data;

    - name: Set Current Repo
      shell: pwsh
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        cd ${{ runner.temp }}/apply-label
        gh repo set-default ${{ github.repository }}
      
    - name: Create User Prompt
      id: create-user-prompt
      shell: pwsh
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        ${{ github.action_path }}/process-prompt-template.ps1 `
          -Template "${{ github.action_path }}/user-prompt-template.md" `
          -Output "${{ runner.temp }}/apply-label/user-prompt.md"
      
    - name: Create System Prompt
      id: create-system-prompt
      shell: pwsh
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        ${{ github.action_path }}/process-prompt-template.ps1 `
          -Template "${{ github.action_path }}/system-prompt-template.md" `
          -Output "${{ runner.temp }}/apply-label/system-prompt.md"

    - name: Run AI Inference
      id: inference
      uses: actions/ai-inference@main
      with:
        prompt-file: "${{ runner.temp }}/apply-label/user-prompt.md"
        system-prompt-file: "${{ runner.temp }}/apply-label/system-prompt.md"
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Log AI Analysis
      shell: pwsh
      run: cat "${{ steps.inference.outputs.response-file }}"
