using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Xml;
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;
using Microsoft.Maui.Resizetizer.Resources;
using SkiaSharp;

namespace Microsoft.Maui.Resizetizer
{
	/// <summary>
	/// Generates files relating to the Android splash screen:
	///  - Resources/values/maui_colors.xml
	///  - Resources/drawable/maui_splash_image.xml
	///  - Resources/drawable-v31/maui_splash_image.xml
	///  - Resources/[drawable]/[splash].png
	/// </summary>
	public class GenerateSplashAndroidResources : Task, ILogger
	{
		[Required]
		public string IntermediateOutputPath { get; set; }

		[Required]
		public ITaskItem[] MauiSplashScreen { get; set; }

		public string InputsFile { get; set; }

		public override bool Execute()
		{
			Log.LogMessage(MessageImportance.Low, $"Splash Screen: Intermediate Path " + IntermediateOutputPath);

			var splash = MauiSplashScreen?.FirstOrDefault();
			if (splash is null)
			{
				Log.LogMessage(MessageImportance.Low, $"Splash Screen: No images found.");
				return true;
			}

			try
			{
				var info = ResizeImageInfo.Parse(splash);

				var resizer = new Resizer(info, IntermediateOutputPath, this);
				Resizer darkResizer = null;
				if (info.HasDarkMode)
				{
					var darkInfo = info.CreateDarkVariant(info.OutputName + info.OutputExtension);
					if (darkInfo.BaseSize is null && !string.IsNullOrWhiteSpace(info.DarkFilename))
						darkInfo.BaseSize = resizer.BaseSize ?? resizer.GetOriginalSize();
					darkResizer = new Resizer(darkInfo, IntermediateOutputPath, this);
				}

				WriteImages(resizer);
				if (darkResizer is not null)
					WriteImages(darkResizer, dark: true);
				else
					CleanNightResources();

				WriteColors(resizer, darkResizer);
				WriteDrawable(resizer, dark: false);
				WriteDrawable_v31(resizer, dark: false);

				if (darkResizer is not null)
				{
					WriteDrawable(darkResizer, dark: true);
					WriteDrawable_v31(darkResizer, dark: true);
				}

				return !Log.HasLoggedErrors;
			}
			catch (Exception ex)
			{
				Log.LogError(ErrorMessages.AndroidResourceProcessing, ErrorCodes.AndroidResourceProcessingCode, null, null, 0, 0, 0, 0, string.Format(ErrorMessages.AndroidResourceProcessingError, ex.ToString()));
				return false;
			}
		}

		static readonly XmlWriterSettings Settings = new XmlWriterSettings { Indent = true };
		const string Namespace = "http://schemas.android.com/apk/res/android";
		const string Comment = "This file was auto-generated by .NET MAUI.";
		const float PreferredImageSize = 108f;

		private void WriteImages(Resizer resizer, bool dark = false)
		{
			if (resizer.Info.Resize)
			{
				foreach (var dpi in dark ? DpiPath.Android.ImageNight : DpiPath.Android.Image)
				{
					Log.LogMessage(MessageImportance.Low, $"Splash Screen Resize: " + dpi);
					resizer.Resize(dpi, InputsFile);
				}
			}
			else
			{
				var dpi = dark ? DpiPath.Android.OriginalNight : DpiPath.Android.Original;

				Log.LogMessage(MessageImportance.Low, $"Splash Screen Copy: " + dpi);
				resizer.CopyFile(dpi, InputsFile);
			}
		}

		void WriteColors(Resizer resizer, Resizer darkResizer)
		{
			WriteColors(resizer.Info.Color, "values");

			if (darkResizer?.Info.Color is not null)
				WriteColors(darkResizer.Info.Color, "values-night");
			else if (darkResizer is not null)
				DeleteNightColors();
		}

		void WriteColors(SKColor? color, string directory)
		{
			var dir = Path.Combine(IntermediateOutputPath, directory);
			Directory.CreateDirectory(dir);

			var colorsFile = Path.Combine(dir, "maui_colors.xml");

			Log.LogMessage(MessageImportance.Low, $"Splash Screen Colors: " + colorsFile);

			using var writer = XmlWriter.Create(colorsFile, Settings);
			writer.WriteComment(Comment);
			writer.WriteStartElement("resources");

			if (color is not null)
			{
				writer.WriteStartElement("color");
				writer.WriteAttributeString("name", "maui_splash_color");
				writer.WriteString(color.ToString());
				writer.WriteEndElement();
			}

			writer.WriteEndDocument();
		}

		void WriteDrawable(Resizer resizer, bool dark)
		{
			var dir = Path.Combine(IntermediateOutputPath, dark ? "drawable-night" : "drawable");
			Directory.CreateDirectory(dir);

			var drawableFile = Path.Combine(dir, "maui_splash_image.xml");

			Log.LogMessage(MessageImportance.Low, $"Splash Screen Drawable{(dark ? " (night)" : "")}: " + drawableFile);

			using var writer = XmlWriter.Create(drawableFile, Settings);
			writer.WriteComment(Comment);
			writer.WriteStartElement("layer-list");
			writer.WriteAttributeString("xmlns", "android", ns: null, value: Namespace);

			writer.WriteStartElement("item");

			writer.WriteStartElement("bitmap");
			writer.WriteAttributeString("android", "gravity", Namespace, "center");
			writer.WriteAttributeString("android", "src", Namespace, "@drawable/" + resizer.Info.OutputName);
			writer.WriteAttributeString("android", "mipMap", Namespace, "true");

			writer.WriteEndDocument();
		}

		void WriteDrawable_v31(Resizer resizer, bool dark)
		{
			var size = CalculateScaledSize(resizer);

			var dir = Path.Combine(IntermediateOutputPath, dark ? "drawable-night-v31" : "drawable-v31");
			Directory.CreateDirectory(dir);

			var drawableFile = Path.Combine(dir, "maui_splash_image.xml");

			Log.LogMessage(MessageImportance.Low, $"Splash Screen Drawable ({(dark ? "night " : "")}v31): " + drawableFile);

			using var writer = XmlWriter.Create(drawableFile, Settings);
			writer.WriteComment(Comment);
			writer.WriteStartElement("layer-list");
			writer.WriteAttributeString("xmlns", "android", ns: null, value: Namespace);

			writer.WriteStartElement("item");
			writer.WriteAttributeString("android", "width", Namespace, size.Width.ToString("0", CultureInfo.InvariantCulture) + "dp");
			writer.WriteAttributeString("android", "height", Namespace, size.Height.ToString("0", CultureInfo.InvariantCulture) + "dp");
			writer.WriteAttributeString("android", "gravity", Namespace, "center");

			writer.WriteStartElement("bitmap");
			writer.WriteAttributeString("android", "gravity", Namespace, "fill");
			writer.WriteAttributeString("android", "src", Namespace, "@drawable/" + resizer.Info.OutputName);
			writer.WriteAttributeString("android", "mipMap", Namespace, "true");

			writer.WriteEndDocument();
		}

		void ILogger.Log(string message)
		{
			Log?.LogMessage(message);
		}

		void CleanNightResources()
		{
			foreach (var directory in new[]
			{
				"values-night",
				"drawable-night",
				"drawable-night-v31",
				"drawable-night-mdpi",
				"drawable-night-hdpi",
				"drawable-night-xhdpi",
				"drawable-night-xxhdpi",
				"drawable-night-xxxhdpi",
			})
			{
				var path = Path.Combine(IntermediateOutputPath, directory);
				if (Directory.Exists(path))
					Directory.Delete(path, recursive: true);
			}
		}

		void DeleteNightColors()
		{
			var colorsFile = Path.Combine(IntermediateOutputPath, "values-night", "maui_colors.xml");
			if (File.Exists(colorsFile))
				File.Delete(colorsFile);
		}

		static SKSize CalculateScaledSize(Resizer resizer)
		{
			var size = resizer.BaseSize ?? resizer.GetOriginalSize();

			var width = PreferredImageSize;
			var height = PreferredImageSize;

			if (size.Width > size.Height)
				height = size.Height / size.Width * width;
			else
				width = size.Width / size.Height * height;

			return new SKSize(width, height);
		}
	}
}
