<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(MauiSamplePlatforms)</TargetFrameworks>
    <TargetFrameworks Condition=" '$(UseMaui)' != 'true' and '$(IncludePreviousTfms)' == 'true' ">$(TargetFrameworks);$(MauiSamplePreviousPlatforms)</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <SingleProject>true</SingleProject>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <RootNamespace>Wordzzle</RootNamespace>
    <AssemblyName>Wordzzle</AssemblyName>
    <RuntimeIdentifier Condition="$(TargetFramework.Contains('-maccatalyst'))">maccatalyst-x64</RuntimeIdentifier>
    <RuntimeIdentifier Condition="$(TargetFramework.Contains('-maccatalyst')) and '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'arm64'">maccatalyst-arm64</RuntimeIdentifier>
    <UseMaterial3>false</UseMaterial3>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationTitle>Wordzzle</ApplicationTitle>
    <ApplicationId>com.kubaflo.wordzzle</ApplicationId>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <WindowsPackageType>None</WindowsPackageType>
  </PropertyGroup>

  <ItemGroup Condition=" '$(UseMaui)' != 'true' ">
    <ProjectReference Include="..\..\..\Core\src\Core.csproj" />
    <ProjectReference Include="..\..\..\Essentials\src\Essentials.csproj" />
    <ProjectReference Include="..\..\..\Controls\src\Xaml\Controls.Xaml.csproj" />
    <ProjectReference Include="..\..\..\Controls\src\Core\Controls.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <MauiIcon Include="Resources\AppIcon\appicon.svg" />
    <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#F5F4EF" BaseSize="128,128" />
  </ItemGroup>

  <Import Project="$(MauiSrcDirectory)Maui.InTree.props" Condition=" '$(UseMaui)' != 'true' " />

</Project>
