using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Microsoft.Maui.Essentials.DeviceTests")]
[assembly: InternalsVisibleTo("Microsoft.Maui.Essentials.UnitTests")]
[assembly: InternalsVisibleTo("EssentialsTests")]
[assembly: InternalsVisibleTo("EssentialsDeviceTestsAndroid")]
[assembly: InternalsVisibleTo("EssentialsDeviceTestsUWP")]
[assembly: InternalsVisibleTo("EssentialsDeviceTestsShared")]
[assembly: InternalsVisibleTo("EssentialsDeviceTestsiOS")]
[assembly: InternalsVisibleTo("Microsoft.Maui.Controls.Core.UnitTests")]
[assembly: InternalsVisibleTo("Microsoft.Maui.Controls.Xaml.UnitTests")]
[assembly: InternalsVisibleTo("Microsoft.Maui.Compatibility.Core.UnitTests")]
[assembly: InternalsVisibleTo("Microsoft.Maui.TestUtils")]
[assembly: InternalsVisibleTo("Microsoft.Maui.TestUtils.DeviceTests")]
[assembly: InternalsVisibleTo("Microsoft.Maui.TestUtils.DeviceTests.Runners")]
