trigger:
  branches:
    include:
    - main
    - net9.0
    - release/*
  tags:
    include:
    - '*'
  paths:
    include:
    - '*'
    exclude:
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

schedules:
- cron: "0 5 * * *"
  displayName: Run daily at 5:00 UTC
  branches:
    include:
    - main
    - net9.0
    
variables:
  - template: /eng/common/templates/variables/pool-providers.yml@self 
  - template: /eng/pipelines/common/variables.yml@self
  - template: /eng/pipelines/arcade/variables.yml@self
  - group: DotNetBuilds storage account read tokens
  - group: AzureDevOps-Artifact-Feeds-Pats

parameters:
  - name: VM_IMAGE_HOST
    type: object
    default:
      name: NetCore1ESPool-Internal
      image: 1es-windows-2022
      os: windows

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  ${{ else }}:
    template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool: ${{ parameters.VM_IMAGE_HOST }}
    sdl:
      binskim:
        scanOutputDirectoryOnly: true
      codeql:
        runSourceLanguagesInSourceAnalysis: true
      policheck:
        enabled: true
      spotBugs:
        enabled: false
        justification: 'Failing with "Could not successfully find the java tool launcher"'
      sourceRepositoriesToScan:
        exclude:
        - repository: yaml-templates
      suppression:
        suppressionFile: $(Build.SourcesDirectory)\eng\automation\guardian\source.gdnsuppress
    stages:
    - template: /eng/pipelines/arcade/stage-pack.yml@self
      parameters:
        pool: ${{ parameters.VM_IMAGE_HOST }}
        enableSourceIndex: true
        sourceIndexParams:
          sourceIndexBuildCommand: build.cmd -restore -build -ci /bl:$(Build.Arcade.LogsPath)sourceIndexBuild.binlog /p:OfficialBuildId=$(_BuildOfficalId) /p:_SkipUpdateBuildNumber=true
          binlogPath: $(Build.Arcade.LogsPath)sourceIndexBuild.binlog

      # Publish and validation steps. Only run in official builds
    - template: /eng/common/templates-official/post-build/post-build.yml@self
      parameters:
        publishingInfraVersion: 3
        enableSymbolValidation: true
        enableSigningValidation: false
        # Disable for now as we test the new signing process
        enableSourceLinkValidation: false
        validateDependsOn:
        - Pack
        publishDependsOn:
        - Validate
        # This is to enable SDL runs part of Post-Build Validation Stage
        SDLValidationParameters:
          enable: false

    - template: /eng/pipelines/arcade/stage-unit-tests.yml@self
      parameters:
        jobMatrix:
        - name: win_unit_tests
          displayName: Windows Unit Tests
          pool:
            name: Azure Pipelines
            vmImage: $(HostedWindowsImage)
            os: windows
          timeout: 120
          testOS: Windows
        - name: mac_unit_tests
          displayName: macOS Unit Tests
          pool:
            name: Azure Pipelines
            vmImage: $(HostedMacImage)
            os: macOS
          timeout: 120
          testOS: macOS

    - template: /eng/pipelines/arcade/stage-integration-tests.yml@self
      parameters:
        stageDependsOn: Pack
        jobMatrix:
        - name: win_sample_tests
          pool:
            name: Azure Pipelines
            vmImage: $(HostedWindowsImage)
            os: windows
          timeout: 120
          testCategory: Samples

        - name: mac_sample_tests
          pool:
            name: Azure Pipelines
            vmImage: $(HostedMacImage)
            os: macOS
          timeout: 120
          testCategory: Samples

        - name: win_wintemplate_tests
          pool:
            name: Azure Pipelines
            vmImage: $(HostedWindowsImage)
            os: windows
          timeout: 120
          testCategory: WindowsTemplates

        - name: mac_wintemplate_tests
          pool:
            name: Azure Pipelines
            vmImage: $(HostedMacImage)
            os: macOS
          timeout: 120
          testCategory: WindowsTemplates

        - name: win_buildtemplate_tests
          pool:
            name: Azure Pipelines
            vmImage: $(HostedWindowsImage)
            os: windows
          timeout: 120
          testCategory: Build

        - name: mac_buildtemplate_tests
          pool:
            name: Azure Pipelines
            vmImage: $(HostedMacImage)
            os: macOS
          timeout: 120
          testCategory: Build

        - name: win_blazortemplate_tests
          pool:
            name: Azure Pipelines
            vmImage: $(HostedWindowsImage)
            os: windows
          timeout: 120
          testCategory: Blazor

        - name: mac_blazortemplate_tests
          pool:
            name: Azure Pipelines
            vmImage: $(HostedMacImage)
            os: macOS
          timeout: 120
          testCategory: Blazor

        - name: win_multitemplate_tests
          pool:
            name: Azure Pipelines
            vmImage: $(HostedWindowsImage)
            os: windows
          timeout: 120
          testCategory: MultiProject

        - name: mac_multitemplate_tests
          pool:
            name: Azure Pipelines
            vmImage: $(HostedMacImage)
            os: macOS
          timeout: 120
          testCategory: MultiProject

        # TODO: macOSTemplates and AOT template categories

        - name: mac_runandroid_tests
          pool:
            name: Azure Pipelines
            vmImage: $(HostedMacImage)
            os: macOS
          timeout: 120
          testCategory: RunOnAndroid

        - name: mac_runios_tests
          pool:
            name: Azure Pipelines
            vmImage: $(HostedMacImage)
            os: macOS
          timeout: 120
          testCategory: RunOniOS
