trigger:
  branches:
    include:
    - main
    - release/*
    - net*.0
    - inflight/*
  tags:
    include:
    - '*'
  paths:
    include:
    - '*'
    exclude:
    - .github/**
    - docs/*
    - src/Templates/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - THIRD-PARTY-NOTICES.TXT

pr:
  branches:
    include:
    - main
    - release/*
    - net*.0
    - inflight/*
  paths:
    include:
    - '*'
    exclude:
    - .github/**
    - docs/*
    - src/Templates/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - THIRD-PARTY-NOTICES.TXT

variables:
- template: /eng/common/templates/variables/pool-providers.yml@self
- template: /eng/pipelines/common/variables.yml@self
- template: /eng/pipelines/arcade/variables.yml@self
# Include Helix access token for internal builds
- ${{ if eq(variables['System.TeamProject'], 'internal') }}:
  - group: DotNet-HelixApi-Access

parameters:

# Internal pools (dnceng)
- name: windowsPoolInternal
  type: object
  default:
    name: NetCore1ESPool-Internal
    demands:
        - ImageOverride -equals 1es-windows-2022
    image: 1es-windows-2022
    os: Windows

- name: macOSTestPoolInternal
  type: object
  default:
    name: Azure Pipelines
    vmImage: macOS-15-arm64

- name: macOSPoolInternal
  type: object
  default:
    name: Azure Pipelines
    vmImage: macOS-15-arm64

# Public pools (dnceng-public)
- name: windowsPoolPublic
  type: object
  default:
    name: NetCore-Public
    demands:
        - ImageOverride -equals 1es-windows-2022-open
    image: 1es-windows-2022-open
    os: Windows

- name: macOSTestPoolPublic
  type: object
  default:
    name: AcesShared
    demands:
      - ImageOverride -equals ACES_VM_SharedPool_Tahoe

- name: macOSPoolPublic
  type: object
  default:
    name: AcesShared
    demands:
      - ImageOverride -equals ACES_VM_SharedPool_Tahoe

- name: targetFrameworkVersions
  type: object
  default:
  - tfm: net11.0

stages:
- ${{ each targetFrameworkVersion in parameters.targetFrameworkVersions }}:

  # Use Helix for iOS / Android / MacCatalyst / Windows Device Tests
  - template: /eng/pipelines/arcade/stage-device-tests.yml@self
    parameters:
      # Select pools based on pipeline - internal vs public
      ${{ if eq(variables['System.TeamProject'], 'internal') }}:
        buildPool: ${{ parameters.macOSPoolInternal }}
        testPool: ${{ parameters.windowsPoolInternal }}
        windowsBuildPool: ${{ parameters.windowsPoolInternal }}
        windowsTestPool: ${{ parameters.windowsPoolInternal }}
        runAsPublic: false
        HelixAccessToken: $(HelixApiAccessToken)
        HelixInternal: true
      ${{ else }}:
        buildPool: ${{ parameters.macOSPoolPublic }}
        testPool: ${{ parameters.windowsPoolPublic }}
        windowsBuildPool: ${{ parameters.windowsPoolPublic }}
        windowsTestPool: ${{ parameters.windowsPoolPublic }}
        runAsPublic: true
      runWindowsTests: true
      TargetFrameworkVersion: ${{ targetFrameworkVersion.tfm }}
      prepareSteps:
      - template: /eng/pipelines/common/provision.yml@self
        parameters:
          checkoutDirectory: '$(System.DefaultWorkingDirectory)'
          skipJdk: false
          skipAndroidCommonSdks: false
          skipAndroidPlatformApis: false
          onlyAndroidPlatformDefaultApis: true
          skipAndroidEmulatorImages: true
          skipAndroidCreateAvds: true
          skipProvisioning: true
          skipXcode: false
          skipSimulatorSetup: false

