trigger:
  branches:
    include:
    - main
    - release/*
    - net*.0
    - inflight/*
  tags:
    include:
    - '*'
  paths:
    include:
    - '*'
    exclude:
    - .github/**
    - docs/*
    - src/Templates/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - THIRD-PARTY-NOTICES.TXT

pr:
  branches:
    include:
    - main
    - release/*
    - net*.0
    - inflight/*
  paths:
    include:
    - '*'
    exclude:
    - .github/**
    - docs/*
    - src/Templates/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - THIRD-PARTY-NOTICES.TXT

variables:
- template: /eng/common/templates/variables/pool-providers.yml@self
- template: /eng/pipelines/common/variables.yml@self
- template: /eng/pipelines/arcade/variables.yml@self

parameters:

- name: windowsPool
  type: object
  default:
    name: NetCore-Public
    demands:
        - ImageOverride -equals 1es-windows-2022-open
    image: 1es-windows-2022-open
    os: Windows

- name: macOSTestPool
  type: object
  default:
    name: Azure Pipelines
    vmImage: macOS-15

- name: macOSPool
  type: object
  default:
    name: MAUI
    vmImage: MAUI

- name: targetFrameworkVersions
  type: object
  default:
  - tfm: net10.0

stages:
- ${{ each targetFrameworkVersion in parameters.targetFrameworkVersions }}:

  # Use Helix for iOS / Android / MacCatalyst / Windows Device Tests
  - template: /eng/pipelines/arcade/stage-device-tests.yml@self
    parameters:
      buildPool: ${{ parameters.macOSPool }}
      testPool: ${{ parameters.windowsPool }}
      windowsBuildPool: ${{ parameters.windowsPool }}
      windowsTestPool: ${{ parameters.windowsPool }}
      runAsPublic: true
      runWindowsTests: true
      TargetFrameworkVersion: ${{ targetFrameworkVersion.tfm }}
      prepareSteps:
      - template: /eng/pipelines/common/provision.yml@self
        parameters:
          checkoutDirectory: '$(System.DefaultWorkingDirectory)'
          skipJdk: false
          skipAndroidCommonSdks: false
          skipAndroidPlatformApis: false
          onlyAndroidPlatformDefaultApis: true
          skipAndroidEmulatorImages: true
          skipAndroidCreateAvds: true
          skipProvisioning: true
          skipXcode: false
          skipSimulatorSetup: false
