trigger:
  branches:
    include:
    - main
    - net*.0
    - release/*
    - internal/release/*
  tags:
    include:
    - '*'
  paths:
    include:
    - '*'
    exclude:
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - THIRD-PARTY-NOTICES.TXT

schedules:
- cron: "0 5 * * *"
  displayName: Run daily at 5:00 UTC
  branches:
    include:
    - main
    - net*.0
    - inflight/current
  always: true

variables:
- template: /eng/common/templates/variables/pool-providers.yml@self
- template: /eng/pipelines/common/variables.yml@self
- template: /eng/pipelines/arcade/variables.yml@self
- group: AzureDevOps-Artifact-Feeds-Pats

parameters:
- name: VM_IMAGE_HOST
  type: object
  default:
    name: NetCore1ESPool-Internal
    image: 1es-windows-2022
    os: windows

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  ${{ else }}:
    template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool: ${{ parameters.VM_IMAGE_HOST }}
    sdl:
      binskim:
        scanOutputDirectoryOnly: true
      codeql:
        runSourceLanguagesInSourceAnalysis: true
      policheck:
        enabled: true
      spotBugs:
        enabled: false
        justification: 'Failing with "Could not successfully find the java tool launcher"'
      sourceRepositoriesToScan:
        exclude:
        - repository: yaml-templates
      suppression:
        suppressionFile: $(Build.SourcesDirectory)\eng\automation\guardian\source.gdnsuppress
    stages:

    - template: /eng/pipelines/arcade/stage-pack.yml@self
      parameters:
        pool: ${{ parameters.VM_IMAGE_HOST }}
        enableSourceIndex: false
        runAsPublic: false
        enableMicrobuild: true
        publishAssets: true
        sourceIndexParams:
          sourceIndexBuildCommand: build.cmd -restore -build -ci /bl:$(Build.Arcade.LogsPath)sourceIndexBuild.binlog /p:OfficialBuildId=$(_BuildOfficalId) /p:_SkipUpdateBuildNumber=true
          binlogPath: $(Build.Arcade.LogsPath)sourceIndexBuild.binlog
        prepareSteps:
        - template: /eng/pipelines/common/provision.yml@self
          parameters:
            checkoutDirectory: '$(System.DefaultWorkingDirectory)'
            skipJdk: false
            skipAndroidCommonSdks: false
            skipAndroidPlatformApis: false
            onlyAndroidPlatformDefaultApis: true
            skipAndroidEmulatorImages: true
            skipAndroidCreateAvds: true
            skipProvisioning: true
            skipXcode: true
            base64Encode: true
            outputVariableName: dotnetbuilds-internal-container-read-token-base64

    - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), and(startsWith(variables['Build.SourceBranch'], 'refs/heads/net'), endsWith(variables['Build.SourceBranch'], '.0')), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')) }}:
      - template: /eng/pipelines/arcade/stage-api-scan.yml@self
        parameters:
          pool: ${{ parameters.VM_IMAGE_HOST }}
          dependsOnStage: Pack

    # Publish and validation steps. Only run in official builds
    - template: /eng/common/templates-official/post-build/post-build.yml@self
      parameters:
        publishingInfraVersion: 3
        enableSymbolValidation: true
        enableSigningValidation: false
        # Disable for now as we test the new signing process
        enableSourceLinkValidation: false
        validateDependsOn:
        - Pack
        publishDependsOn:
        - Validate
        # This is to enable SDL runs part of Post-Build Validation Stage
        SDLValidationParameters:
          enable: false