trigger:
  branches:
    include:
    - main
    - release/*
    - net*.0
    - inflight/*
  tags:
    include:
    - '*'
  paths:
    include:
    - '*'
    exclude:
    - .github/**
    - docs/*
    - src/Templates/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - THIRD-PARTY-NOTICES.TXT

pr:
  branches:
    include:
    - main
    - release/*
    - net*.0
    - inflight/*
  paths:
    include:
    - '*'
    exclude:
    - .github/**
    - docs/*
    - src/Templates/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - THIRD-PARTY-NOTICES.TXT

variables:
  - template: /eng/pipelines/common/variables.yml@self

parameters:

  - name: BuildEverything
    type: boolean
    default: false

  - name: BuildNativeAOT
    displayName: 'Build NativeAOT artifacts'
    type: boolean
    default: false

  - name: RunNativeAOT
    displayName: 'Run NativeAOT UI Tests'
    type: boolean
    default: false

  # Internal pools (dnceng)
  - name: androidPoolInternal
    type: object
    default:
      name: Azure Pipelines
      vmImage: macOS-15-arm64
  
  - name: androidPoolLinuxInternal
    type: object
    default:
      name: NetCore1ESPool-Internal
      demands:
        - ImageOverride -equals 1es-ubuntu2204

  - name: iosPoolInternal
    type: object
    default:
      name: Azure Pipelines
      vmImage: macOS-15-arm64
  
  - name: windowsBuildPoolInternal
    type: object
    default:
      name: NetCore1ESPool-Internal
      demands:
        - ImageOverride -equals 1es-windows-2022
    
  - name: windowsPoolInternal
    type: object
    default:
      name: NetCore1ESPool-Internal
      demands:
        - ImageOverride -equals 1es-windows-2022

  - name: macosPoolInternal
    type: object
    default:
      name: Azure Pipelines
      vmImage: macOS-14

  # Public pools (dnceng-public)
  - name: androidPoolPublic
    type: object
    default:
      name: MAUI
      vmImage: MAUI
  
  - name: androidPoolLinuxPublic
    type: object
    default:
      name: MAUI-DNCENG
      demands:
        - ImageOverride -equals 1ESPT-Ubuntu22.04

  - name: iosPoolPublic
    type: object
    default:
      name: MAUI
      vmImage: MAUI      
      demands:
        - Agent.OSArchitecture -equals ARM64
  
  - name: windowsBuildPoolPublic
    type: object
    default:
      name: NetCore-Public
      demands:
        - ImageOverride -equals 1es-windows-2022-open
    
  - name: windowsPoolPublic
    type: object
    default:
      name: NetCore-Public
      demands:
        - ImageOverride -equals 1es-windows-2022-open

  - name: macosPoolPublic
    type: object
    default:
      name: Azure Pipelines
      vmImage: macOS-14

stages:

  - template: common/ui-tests.yml
    parameters:
      # Select pools based on pipeline - internal vs public
      ${{ if eq(variables['System.TeamProject'], 'internal') }}:
        androidPool: ${{ parameters.androidPoolInternal }}
        androidLinuxPool: ${{ parameters.androidPoolLinuxInternal }}
        iosPool: ${{ parameters.iosPoolInternal }}
        windowsPool: ${{ parameters.windowsPoolInternal }}
        windowsBuildPool: ${{ parameters.windowsBuildPoolInternal }}
        macosPool: ${{ parameters.macosPoolInternal }}
      ${{ else }}:
        androidPool: ${{ parameters.androidPoolPublic }}
        androidLinuxPool: ${{ parameters.androidPoolLinuxPublic }}
        iosPool: ${{ parameters.iosPoolPublic }}
        windowsPool: ${{ parameters.windowsPoolPublic }}
        windowsBuildPool: ${{ parameters.windowsBuildPoolPublic }}
        macosPool: ${{ parameters.macosPoolPublic }}
      # BuildNativeAOT is false by default, but true in devdiv environment
      BuildNativeAOT: ${{ or(parameters.BuildNativeAOT, and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['System.TeamProject'], 'devdiv'))) }}
      RunNativeAOT: ${{ parameters.RunNativeAOT }}
      ${{ if or(parameters.BuildEverything, and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['System.TeamProject'], 'devdiv'))) }}:
        androidApiLevels: [ 30 ]
        iosVersions: [ '18.4' ]
      ${{ else }}:
        androidApiLevels: [ 30 ]
        iosVersions: [ '18.4' ]
      projects:
        - name: controls
          desc: Controls
          androidApiLevelsExclude: [25] # Ignore for now API25 since the runs's are not stable
          android: $(System.DefaultWorkingDirectory)/src/Controls/tests/TestCases.Android.Tests/Controls.TestCases.Android.Tests.csproj
          app: $(Pipeline.Workspace)/Controls.TestCases.HostApp/
          iosVersionsExclude: [ '12.4'] # Ignore iOS 12.4 while we can't make it work on CI
          ios: $(System.DefaultWorkingDirectory)/src/Controls/tests/TestCases.iOS.Tests/Controls.TestCases.iOS.Tests.csproj
          winui: $(System.DefaultWorkingDirectory)/src/Controls/tests/TestCases.WinUI.Tests/Controls.TestCases.WinUI.Tests.csproj
          mac: $(System.DefaultWorkingDirectory)/src/Controls/tests/TestCases.Mac.Tests/Controls.TestCases.Mac.Tests.csproj


