trigger:
  branches:
    include:
    - main
    - net9.0
    - release/*
  tags:
    include:
    - '*'
  paths:
    include:
    - '*'
    exclude:
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - THIRD-PARTY-NOTICES.TXT

schedules:
- cron: "0 5 * * *"
  displayName: Run daily at 5:00 UTC
  branches:
    include:
    - main

variables:
  - template: /eng/pipelines/common/variables.yml@self

parameters:
  - name: VM_IMAGE_HOST
    type: object
    default:
      name: MAUI-1ESPT
      image: 1ESPT-Windows2022
      os: windows

  - name: PackPlatform
    type: object
    default:
      name: Windows
      artifact: nuget
      binariesArtifact: pack-binaries
      metadataArtifact: metadata
      logsArtifact: logs
      docsArtifact: xml-docs

  - name: Skip1ESComplianceTasks
    type: boolean
    default: false

  - name: PushMauiPackagesToMaestro
    type: boolean
    default: true

resources:
  repositories:
    - repository: yaml-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
      ref: refs/heads/main
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool: ${{ parameters.VM_IMAGE_HOST }}
    sdl:
      ${{ if eq('${{ parameters.Skip1ESComplianceTasks }}', 'true') }}:
        enableAllTools: false
      binskim:
        scanOutputDirectoryOnly: true
      codeql:
        runSourceLanguagesInSourceAnalysis: true
      policheck:
        enabled: true
      spotBugs:
        enabled: false
        justification: 'Failing with "Could not successfully find the java tool launcher"'
      sourceRepositoriesToScan:
        exclude:
        - repository: yaml-templates
      suppression:
        suppressionFile: $(Build.SourcesDirectory)\eng\automation\guardian\source.gdnsuppress
      tsa:
        enabled: true
        configFile: '$(Build.SourcesDirectory)\eng\automation\guardian\tsaoptions-v2.json'
    stages:
      - stage: pack_net
        displayName: Pack .NET MAUI
        dependsOn: []
        jobs:
          - job: pack_net_${{ parameters.PackPlatform.name }}
            workspace:
              clean: all
            displayName: ${{ parameters.PackPlatform.name }}
            timeoutInMinutes: 240
           
            pool: ${{ parameters.VM_IMAGE_HOST }}
              
            templateContext:
              outputs:
                - output: pipelineArtifact
                  displayName: 'Publish the ${{ parameters.PackPlatform.artifact }} artifacts'
                  artifactName: ${{ parameters.PackPlatform.artifact }}
                  targetPath: '$(Build.ArtifactStagingDirectory)/nuget'
                
                - output: pipelineArtifact
                  displayName: 'Publish the ${{ parameters.PackPlatform.binariesArtifact }} artifacts'
                  artifactName: ${{ parameters.PackPlatform.binariesArtifact }}
                  targetPath: '$(System.DefaultWorkingDirectory)/artifacts/binaries'

                - output: pipelineArtifact
                  displayName: 'Publish the ${{ parameters.PackPlatform.docsArtifact }} artifacts'
                  artifactName: ${{ parameters.PackPlatform.docsArtifact }}
                  targetPath: '$(System.DefaultWorkingDirectory)/artifacts/docs-packs'

                - output: pipelineArtifact
                  displayName: 'Publish the ${{ parameters.PackPlatform.metadataArtifact }} artifacts'
                  artifactName: ${{ parameters.PackPlatform.metadataArtifact }}
                  targetPath: '$(Build.ArtifactStagingDirectory)/metadata'

                - output: pipelineArtifact
                  displayName: 'Publish the ${{ parameters.PackPlatform.logsArtifact }} artifacts'
                  artifactName: ${{ parameters.PackPlatform.logsArtifact }}
                  targetPath: '$(Build.ArtifactStagingDirectory)/logs'
            
            variables:
              - name: _buildScript
                value: $(Build.SourcesDirectory)/build.cmd -ci
              - name: _BuildConfig
                value: Release

            steps:
              - template: /eng/pipelines/common/pack.yml@self
                parameters:
                  publishArtifacts: false
                  platform: ${{ parameters.PackPlatform.name }}
                  artifact: ${{ parameters.PackPlatform.artifact }}
                  artifactBinaries: ${{ parameters.PackPlatform.binariesArtifact }}
                  artifactsPath: '$(Build.ArtifactStagingDirectory)'
                  buildConfiguration: $(_BuildConfig)
                  dotnetScript: $(Build.SourcesDirectory)/dotnet.cmd
                  buildScript: $(_buildScript)
                  repoArtifactsPath: $(Build.Arcade.ArtifactsPath)
                  repoLogPath: $(Build.Arcade.LogsPath)
                  repoTestResultsPath: $(Build.Arcade.TestResultsPath)
                  officialBuildId: $(_BuildOfficalId)
                  prepareSteps:
                    - template: /eng/pipelines/common/provision.yml@self
                      parameters:
                        checkoutDirectory: '$(System.DefaultWorkingDirectory)'
                        # gitHubToken: $(github--pat--vs-mobiletools-engineering-service2)
                        skipAndroidImages: true
                        skipAndroidSdks: true
                        installDefaultAndroidApi: true
                        skipProvisioning: true
                        skipXcode: true

      - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:                           # Sign only using the private server   
        - template: /eng/pipelines/common/sign.yml@self                                 
          parameters:
            dependsOn: ['pack_net']
            stageName: 'nuget_signing'
            poolName: ${{ parameters.VM_IMAGE_HOST.name }}
            vmImage: ${{ parameters.VM_IMAGE_HOST.image }}
            os: ${{ parameters.VM_IMAGE_HOST.os }}                                   
        
        - template: /eng/pipelines/common/insertion.yml@self                                # Insert on VS and SDK
          parameters:
            dependsOn: ['nuget_signing']
            stageName: 'sdk_insertion'
            poolName: ${{ parameters.VM_IMAGE_HOST.name }}
            vmImage: ${{ parameters.VM_IMAGE_HOST.image }}
            os: ${{ parameters.VM_IMAGE_HOST.os }}
            pushMauiPackagesToMaestro: ${{ parameters.PushMauiPackagesToMaestro }}

        - template: /eng/pipelines/common/apiscan.yml@self                                  # ApiScan
          parameters:
            dependsOn: ['pack_net']
            poolName: ${{ parameters.VM_IMAGE_HOST.name }}
            vmImage: ${{ parameters.VM_IMAGE_HOST.image }}
            os: ${{ parameters.VM_IMAGE_HOST.os }}     
            tsaUploadEnabled: true
            tsaConfigFile: '$(Build.SourcesDirectory)\eng\automation\guardian\tsaoptions-v2.json'
            scanArtifacts: ['${{ parameters.PackPlatform.binariesArtifact }}']
            softwareVersion: 9.0

        - ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
          - template: /eng/pipelines/common/push-nightly.yml@self
            parameters:
              dependsOn: ['sdk_insertion']
              stageName: 'nightly'
              displayName: 'Push Nightly'
              poolName: ${{ parameters.VM_IMAGE_HOST.name }}
              vmImage: ${{ parameters.VM_IMAGE_HOST.image }}
              os: ${{ parameters.VM_IMAGE_HOST.os }}  
