name: Setup Build Environment
description: 'Reusable action to setup .NET MAUI build environment'

inputs:
  os:
    description: 'Operating system (Windows, macOS, Linux)'
    required: true
    type: string
  dotnet-version:
    description: 'Dotnet version to install (use "global.json" to read from global.json)'
    required: false
    type: string
    default: 'global.json'
  enable-caching:
    description: 'Enable NuGet package caching'
    required: false
    type: boolean
    default: true

runs:
  using: composite
  steps:
    - name: Setup .NET using Arcade (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        chmod +x ./eng/common/dotnet-install.sh
        if [ "${{ inputs.dotnet-version }}" == "global.json" ]; then
          version=$(jq -r '.tools.dotnet' global.json)
        else
          version="${{ inputs.dotnet-version }}"
        fi
        ./eng/common/dotnet-install.sh --version $version --install-dir ./bin/dotnet
        echo "${{ github.workspace }}/bin/dotnet" >> $GITHUB_PATH
        echo "DOTNET_ROOT=${{ github.workspace }}/bin/dotnet" >> $GITHUB_ENV
    
    - name: Setup .NET using Arcade (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        if ("${{ inputs.dotnet-version }}" -eq "global.json") {
          $version = (Get-Content global.json | ConvertFrom-Json).tools.dotnet
        } else {
          $version = "${{ inputs.dotnet-version }}"
        }
        ./eng/common/dotnet-install.ps1 -Version $version -InstallDir ./bin/dotnet
        echo "${{ github.workspace }}\bin\dotnet" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "DOTNET_ROOT=${{ github.workspace }}\bin\dotnet" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    
    - name: Verify .NET version
      shell: bash
      run: dotnet --version
    
    - name: Install MAUI workload
      shell: bash
      run: dotnet workload install maui --skip-manifest-update
      continue-on-error: true
    
    - name: Setup MSBuild (Windows)
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v2
    
    - name: Setup Xcode (macOS)
      if: runner.os == 'macOS'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Cache NuGet packages
      if: inputs.enable-caching == 'true'
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/Directory.Build.props', '**/Versions.props') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    
    - name: Restore tools
      shell: bash
      run: dotnet tool restore
    
    - name: Build prerequisites
      shell: bash
      run: dotnet build ./Microsoft.Maui.BuildTasks.slnf --configuration Release