#!/bin/bash
# =============================================================================
# MAUI DevTools CLI — Interactive Install Demo
# Shows the interactive Spectre.Console prompts for Android setup
# =============================================================================

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║          MAUI DevTools CLI — Interactive Install Demo       ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "This demo shows the interactive experiences in the MAUI CLI."
echo ""
echo "━━━ Interactive Emulator Creation ━━━"
echo ""
echo "  'maui android emulator create' (no arguments) walks through:"
echo "    1. 🔍 Spinner — fetching installed system images"
echo "    2. 📋 Selection prompt — pick a system image"
echo "    3. 📱 Selection prompt — pick a device profile (Pixel 6/8/9, Fold...)"
echo "    4. ✏️  Text prompt — enter an AVD name (smart default: MAUI_android_35)"
echo "    5. ⏳ Spinner — creating the emulator"
echo ""
echo "━━━ Interactive Emulator Start ━━━"
echo ""
echo "  'maui android emulator start' (no arguments) walks through:"
echo "    1. 🔍 Spinner — finding existing emulators"
echo "    2. 📋 Selection prompt — pick which emulator to boot"
echo "    3. ⏳ Spinner — starting the emulator"
echo ""
echo "━━━ Interactive Android Install ━━━"
echo ""
echo "  'maui android install' (no --packages) walks through:"
echo "    1. ⏳ Spinner — fetching available SDK packages"
echo "    2. 📋 Platform selector — Android 36, 35, 34... (shows install status)"
echo "    3. 📋 Install scope picker:"
echo "       • Platform only"
echo "       • Platform + Build Tools"
echo "       • Full Development Setup (Platform, Build Tools, System Image, Emulator)"
echo "    4. 📊 Progress bars for each installation step"
echo ""
echo "━━━ Non-Interactive / CI Mode ━━━"
echo ""
echo "  All commands accept explicit flags to skip prompts:"
echo "    maui android emulator create my-avd --package '...' --device pixel_9"
echo "    maui android emulator start my-avd"
echo "    maui android install --packages 'platforms;android-36,build-tools;36.0.0'"
echo "    maui android install --ci --accept-licenses"
echo ""
echo "━━━ Dry Run ━━━"
echo ""
maui android install --dry-run --packages "platforms;android-36"
echo ""
echo "━━━ Try It! ━━━"
echo ""
echo "  maui android emulator create   # Full interactive wizard"
echo "  maui android emulator start    # Pick and boot an emulator"
echo "  maui android install           # Interactive SDK setup"
