#!/bin/bash
# =============================================================================
# MAUI DevTools CLI — Interactive Install Demo
# Shows the interactive Spectre.Console prompts for Android setup
# =============================================================================

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║          MAUI DevTools CLI — Interactive Install Demo       ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "This demo shows the interactive Android install experience."
echo ""
echo "When you run 'maui android install' without --packages, you get:"
echo "  1. A spinner fetching available SDK packages"
echo "  2. An interactive platform selector (Android 36, 35, 34...)"
echo "     showing install status (Installed/Not installed)"
echo "  3. An install scope picker:"
echo "     • Platform only"
echo "     • Platform + Build Tools"
echo "     • Full Development Setup (Platform, Build Tools, System Image, Emulator)"
echo "  4. Progress bars for each installation step:"
echo "     • JDK installation"
echo "     • SDK Tools installation"
echo "     • License acceptance"
echo "     • Package installation (per-package progress)"
echo ""
echo "━━━ Non-Interactive Mode ━━━"
echo ""
echo "For CI/scripting, specify packages explicitly:"
echo "  maui android install --packages 'platforms;android-36,build-tools;36.0.0'"
echo ""
echo "Or use --ci for fully non-interactive mode:"
echo "  maui android install --ci --accept-licenses"
echo ""
echo "━━━ Dry Run ━━━"
echo ""
maui android install --dry-run --packages "platforms;android-36"
echo ""
echo "━━━ Run It ━━━"
echo ""
echo "To try the interactive experience, run:"
echo "  maui android install"
echo ""
echo "To try the emulator interactive creation:"
echo "  maui android emulator create my-test-avd"
