# Template for running tests on Helix on dnceng
parameters:
- name: prepareSteps
  type: stepList
  default: []
- name: postSteps
  type: stepList
  default: []
- name: enableSourceBuild
  type: boolean
  default: false
- name: enableSourceIndex
  type: boolean
  default: false
- name: sourceIndexParams
  type: object
  default: []
- name: publishAssets
  type: boolean
  default: false
- name: enableMicrobuild
  type: boolean
  default: false
- name: runAsPublic
  type: boolean
  default: true
- name: helixInternal
  type: string
  default: ''
- name: HelixAccessToken
  type: string
  default: ''
- name: creator
  type: string
  default: 'maui'
- name: extraHelixArguments
  type: string
  default: ''
- name: buildTaskProjects
  type: string
  default: '$(Build.SourcesDirectory)/Microsoft.Maui.BuildTasks.slnf'
- name: helixProject
  type: string
  default: '$(Build.SourcesDirectory)/eng/helix.proj'
- name: buildConfigurations
  type: object
  default:
  - Debug
  - Release
- name: helixPool
  type: object
 
stages:
- stage: HelixTests
  displayName: Run Helix Unit Tests
  dependsOn: []
  jobs:
  - ${{ each BuildConfiguration in parameters.buildConfigurations }}:
    - template: ${{ iif(eq(parameters.runAsPublic, 'true'), '/eng/common/templates/jobs/jobs.yml@self', '/eng/common/templates-official/jobs/jobs.yml@self') }}
      parameters:
        helixRepo: dotnet/maui
        pool: ${{ parameters.helixPool }}
        enableMicrobuild: ${{ parameters.enableMicrobuild }}
        enablePublishUsingPipelines: true
        enablePublishBuildAssets: ${{ parameters.publishAssets }}
        enableTelemetry: true
        enableSourceBuild: ${{ parameters.enableSourceBuild }}
        enableSourceIndex: ${{ parameters.enableSourceIndex }}
        sourceIndexParams: ${{ parameters.sourceIndexParams }}
        publishAssetsImmediately: true
        enablePublishBuildArtifacts: true
        enablePublishTestResults: true
        workspace:
          clean: all
        jobs:
        - job: test_helix_unit_tests_windows_${{ BuildConfiguration }}
          displayName: Windows Helix Unit Tests (${{ BuildConfiguration }})
          timeoutInMinutes: 240
          variables:
          - name: _BuildConfig
            value: ${{ BuildConfiguration }}
          steps:
          - ${{ each step in parameters.prepareSteps }}:
            - ${{ each pair in step }}:
                ${{ pair.key }}: ${{ pair.value }}

          - script: $(_buildScript) -restore -build -configuration ${{ BuildConfiguration }} -projects "${{ parameters.buildTaskProjects }}" /p:ArchiveTests=false /p:TreatWarningsAsErrors=$(TreatWarningsAsErrors) /bl:$(Build.Arcade.LogsPath)${{ BuildConfiguration }}/buildtasks.binlog $(_OfficialBuildIdArgs)
            displayName: 🛠️ Build BuildTasks

          - script: $(_msbuildCommand) "${{ parameters.helixProject }}" -warnAsError 0 -restore /p:Configuration=${{ BuildConfiguration }} /p:HelixInternal="${{ parameters.helixInternal }}" /p:TestRunNameSuffix="_${{ BuildConfiguration }}" /bl:$(Build.Arcade.LogsPath)${{ BuildConfiguration }}/helix_tests.binlog ${{ parameters.extraHelixArguments }}
            displayName: Run Helix Tests
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken) # We need to set this env var to publish helix results to Azure Dev Ops
              HelixAccessToken: ${{ parameters.HelixAccessToken }}
    
