# Template for build + pack on dnceng
parameters:
- name: prepareSteps
  type: stepList
  default: []
- name: postSteps
  type: stepList
  default: []
- name: enableSourceBuild
  type: boolean
  default: false
- name: enableSourceIndex
  type: boolean
  default: false
- name: sourceIndexParams
  type: object
  default: []
- name: runAsPublic
  type: boolean
  default: false
- name: buildProjects
  type: string
  default: 'Microsoft.Maui.sln'
- name: buildConfigurations
  type: object
  default:
  - Debug
  - Release
- name: buildPlatforms
  type: object
  default:
  - name: NetCore-Public
    image: 1es-windows-2022
    os: windows
    buildScript: build.cmd
  - name: Azure Pipelines
    vmImage: $(HostedMacImage)
    os: macOS
    buildScript: build.sh

stages:
- stage: Build
  displayName: Build .NET MAUI
  dependsOn: []
  jobs:
  - ${{ each BuildPlatform in parameters.buildPlatforms }}:
    - template: /eng/common/templates-official/jobs/jobs.yml
      parameters:
        helixRepo: dotnet/maui
        pool: ${{ BuildPlatform }}
        enableMicrobuild: true
        enablePublishUsingPipelines: true
        enablePublishBuildAssets: true
        enableTelemetry: true
        enableSourceBuild: ${{ parameters.enableSourceBuild }}
        enableSourceIndex: ${{ parameters.enableSourceIndex }}
        sourceIndexParams: ${{ parameters.sourceIndexParams }}
        publishAssetsImmediately: true
        enablePublishBuildArtifacts: true
        enablePublishTestResults: true
        workspace:
          clean: all
        jobs:
        - ${{ each BuildConfiguration in parameters.buildConfigurations }}:
          - job: build_net_${{ BuildPlatform.os }}_${{ BuildConfiguration }}
            displayName: Build ${{ BuildPlatform.os }} ${{ BuildConfiguration }}
            timeoutInMinutes: 240
            preSteps:
            - checkout: self
              fetchDepth: 1
              clean: true
            steps:
            - ${{ each step in parameters.prepareSteps }}:
              - ${{ each pair in step }}:
                  ${{ pair.key }}: ${{ pair.value }}

            - script: ${{ BuildPlatform.buildScript }} -restore -build -configuration ${{ BuildConfiguration }} -projects "Microsoft.Maui.BuildTasks.slnf" /p:ArchiveTests=false /p:TreatWarningsAsErrors=false /bl:$(Build.Arcade.LogsPath)buildtasks.binlog $(_OfficialBuildIdArgs)
              displayName: 🛠️ Build BuildTasks

            - script: ${{ BuildPlatform.buildScript }} -restore -build -configuration ${{ BuildConfiguration }} -projects "${{ parameters.buildProjects }}" /p:ArchiveTests=false /p:TreatWarningsAsErrors=false /bl:$(Build.Arcade.LogsPath)build.binlog $(_OfficialBuildIdArgs)
              displayName: 🛠️ Build ${{ parameters.buildProjects }}
