# Template for build + pack on dnceng
parameters:
- name: prepareSteps
  type: stepList
  default: []
- name: postSteps
  type: stepList
  default: []
- name: pool
  type: object
- name: macPool
  type: object
- name: enableSourceBuild
  type: boolean
  default: false
- name: enableSourceIndex
  type: boolean
  default: false
- name: sourceIndexParams
  type: object
  default: []
- name: publishAssets
  type: boolean
  default: false
- name: enableMicrobuild
  type: boolean
  default: false
- name: runAsPublic
  type: boolean
  default: true

stages:
- stage: Pack
  displayName: Pack .NET MAUI
  dependsOn: []
  jobs:
  - template: ${{ iif(eq(parameters.runAsPublic, 'true'), '/eng/common/templates/jobs/jobs.yml', '/eng/common/templates-official/jobs/jobs.yml@self') }}
    parameters:
      helixRepo: dotnet/maui
      enableMicrobuild: ${{ parameters.enableMicrobuild }}
      enablePublishUsingPipelines: true
      enablePublishBuildAssets: ${{ parameters.publishAssets }}
      enableTelemetry: true
      enableSourceBuild: ${{ parameters.enableSourceBuild }}
      enableSourceIndex: ${{ parameters.enableSourceIndex }}
      sourceIndexParams: ${{ parameters.sourceIndexParams }}
      publishAssetsImmediately: true
      enablePublishBuildArtifacts: true
      enablePublishTestResults: false
      templateContext:
        outputs:
        - output: pipelineArtifact
          artifact: APIScanFiles
          path: $(Agent.TempDirectory)/APIScanFiles
        - output: pipelineArtifact
          artifact: Metadata
          path: $(Agent.TempDirectory)/metadata

      workspace:
        clean: all

      jobs:
      - job: pack_net_macOS
        displayName: Pack macOS
        timeoutInMinutes: 240
        pool: ${{ parameters.macPool }}
        preSteps:
        - checkout: self
          fetchDepth: 1
          clean: true

        steps:
        - ${{ each step in parameters.prepareSteps }}:
          - ${{ each pair in step }}:
              ${{ pair.key }}: ${{ pair.value }}

        - script: $(_buildScriptMacOS) -restore -pack -configuration $(_BuildConfig) /bl:$(Build.Arcade.LogsPath)/$(_BuildConfig)/pack-mac.binlog $(_OfficialBuildIdArgs)
          displayName: Pack

        - task: CopyFiles@2
          displayName: Copy Native Binaries
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)/artifacts/bin'
            Contents: |
              */$(_BuildConfig)/*/*.resources.zip
            TargetFolder: '$(Agent.TempDirectory)/native-binaries'

        - task: PublishPipelineArtifact@1
          displayName: Publish Native Binaries
          inputs:
            targetPath: '$(Agent.TempDirectory)/native-binaries'
            artifact: MacNativeArtifacts
          condition: always()

        - ${{ each step in parameters.postSteps }}:
          - ${{ each pair in step }}:
              ${{ pair.key }}: ${{ pair.value }}

      - job: pack_net_Windows
        displayName: Pack Windows
        dependsOn:
        - pack_net_macOS
        timeoutInMinutes: 240
        pool: ${{ parameters.pool }}
        preSteps:
        - checkout: self
          fetchDepth: 1
          clean: true

        steps:
        - ${{ each step in parameters.prepareSteps }}:
          - ${{ each pair in step }}:
              ${{ pair.key }}: ${{ pair.value }}

        # Download Mac native binaries built on macOS
        - task: DownloadPipelineArtifact@2
          displayName: Download Mac Native Binaries
          inputs:
            artifact: MacNativeArtifacts
            path: '$(Build.SourcesDirectory)/artifacts/bin'

        # Run on public pipeline
        - ${{ if not(parameters.enableMicrobuild) }}:
          - script: $(_buildScript) -restore -pack -publish $(_PublishArgs) -configuration $(_BuildConfig) /bl:$(Build.Arcade.LogsPath)/$(_BuildConfig)/pack.binlog $(_OfficialBuildIdArgs)
            displayName: Pack & Publish

        # Run on internal pipeline
        - ${{ if and(not(parameters.runAsPublic) , parameters.enableMicrobuild) }}:
          - script: $(_buildScript) -restore -pack -sign $(_SignArgs) -configuration $(_BuildConfig) /bl:$(Build.Arcade.LogsPath)/$(_BuildConfig)/pack.binlog $(_OfficialBuildIdArgs)
            displayName: Pack, Sign

          # only for workloads
          - script: $(_buildScript) -restore -build -sign $(_SignArgs) -publish $(_PublishArgs) -configuration $(_BuildConfig) /bl:$(Build.Arcade.LogsPath)/$(_BuildConfig)/build-workloads.binlog -projects src/Workload/workloads.csproj $(_OfficialBuildIdArgs)
            displayName: Build Workloads, Sign & Publish

        - task: CopyFiles@2
          displayName: Copy assemblies for APIScan
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)\artifacts\bin\Controls.Core'
            Contents: |
              **/*.dll
              **/*.pdb
            TargetFolder: '$(Agent.TempDirectory)\APIScanFiles'

        - task: CopyFiles@2
          displayName: Copy Metadata
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)\artifacts\packages\$(_BuildConfig)\Shipping\metadata'
            Contents: |
              **/*.json
            TargetFolder: '$(Agent.TempDirectory)\metadata'

        - ${{ each step in parameters.postSteps }}:
          - ${{ each pair in step }}:
              ${{ pair.key }}: ${{ pair.value }}
