# Template for build + pack on dnceng
parameters:
- name: prepareSteps
  type: stepList
  default: []
- name: postSteps
  type: stepList
  default: []
- name: enableSourceBuild
  type: boolean
  default: false
- name: enableSourceIndex
  type: boolean
  default: false
- name: sourceIndexParams
  type: object
  default: []
- name: publishAssets
  type: boolean
  default: false
- name: enableMicrobuild
  type: boolean
  default: false
- name: runAsPublic
  type: boolean
  default: true
- name: buildProjects
  type: string
  default: '$(Build.SourcesDirectory)/Microsoft.Maui.sln'
- name: buildProjectsMac
  type: string
  default: '$(Build.SourcesDirectory)/Microsoft.Maui-mac.slnf'
- name: buildTaskProjects
  type: string
  default: '$(Build.SourcesDirectory)/Microsoft.Maui.BuildTasks.slnf'
- name: buildConfigurations
  type: object
  default:
  - Debug
  - Release
- name: buildPlatforms
  type: object

stages:
- stage: Build
  displayName: Build .NET MAUI
  dependsOn: []
  jobs:
  - ${{ each BuildPlatform in parameters.buildPlatforms }}:
    - template: ${{ iif(eq(parameters.runAsPublic, 'true'), '/eng/common/templates/jobs/jobs.yml', '/eng/common/templates-official/jobs/jobs.yml@self') }}
      parameters:
        helixRepo: dotnet/maui
        pool: ${{ BuildPlatform }}
        enableMicrobuild: ${{ parameters.enableMicrobuild }}
        enablePublishUsingPipelines: true
        enablePublishBuildAssets: ${{ parameters.publishAssets }}
        enableTelemetry: true
        enableSourceBuild: ${{ parameters.enableSourceBuild }}
        enableSourceIndex: ${{ parameters.enableSourceIndex }}
        sourceIndexParams: ${{ parameters.sourceIndexParams }}
        publishAssetsImmediately: true
        enablePublishBuildArtifacts: true
        enablePublishTestResults: true
        workspace:
          clean: all
        jobs:
        - ${{ each BuildConfiguration in parameters.buildConfigurations }}:
          - job: build_net_${{ BuildPlatform.os }}_${{ BuildConfiguration }}
            displayName: Build ${{ BuildPlatform.os }} (${{ BuildConfiguration }})
            timeoutInMinutes: 240
            variables:
            - name: _BuildConfig
              value: ${{ BuildConfiguration }}
            preSteps:
            - checkout: self
              fetchDepth: 1
              clean: true
            steps:
            - ${{ each step in parameters.prepareSteps }}:
              - ${{ each pair in step }}:
                  ${{ pair.key }}: ${{ pair.value }}

            # Display PR environment variables for diagnostic purposes (PR builds only)
            - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
              - script: |
                  echo "##[group]PR Build Environment Variables"
                  echo "Build.Reason: $(Build.Reason)"
                  echo "BUILD_REASON: $BUILD_REASON"
                  echo "System.PullRequest.PullRequestNumber: $(System.PullRequest.PullRequestNumber)"
                  echo "SYSTEM_PULLREQUEST_PULLREQUESTNUMBER: $SYSTEM_PULLREQUEST_PULLREQUESTNUMBER"
                  echo "CI: $CI"
                  echo "##[endgroup]"
                displayName: 🔍 Display PR Environment Variables
                env:
                  BUILD_REASON: $(Build.Reason)
                  SYSTEM_PULLREQUEST_PULLREQUESTNUMBER: $(System.PullRequest.PullRequestNumber)
                  CI: true

            - script: ${{ BuildPlatform.buildScript }} -restore -build -configuration ${{ BuildConfiguration }} -projects "${{ parameters.buildTaskProjects }}" /p:ArchiveTests=false /p:TreatWarningsAsErrors=$(TreatWarningsAsErrors) /bl:$(Build.Arcade.LogsPath)${{ BuildConfiguration }}/buildtasks_${{ BuildPlatform.os }}.binlog $(_OfficialBuildIdArgs)
              displayName: 🛠️ Build BuildTasks
              env:
                BUILD_REASON: $(Build.Reason)
                SYSTEM_PULLREQUEST_PULLREQUESTNUMBER: $(System.PullRequest.PullRequestNumber)

            - script: ${{ BuildPlatform.buildScript }} -restore -build -configuration ${{ BuildConfiguration }} -projects ${{ BuildPlatform.sln }} /p:ArchiveTests=false /p:TreatWarningsAsErrors=$(TreatWarningsAsErrors) /p:CodesignRequireProvisioningProfile=false /p:EnableWindowsTargeting=true /bl:$(Build.Arcade.LogsPath)${{ BuildConfiguration }}/build_${{ BuildPlatform.os }}.binlog $(_OfficialBuildIdArgs)
              displayName: 🛠️ Build Microsoft.Maui.sln
              env:
                BUILD_REASON: $(Build.Reason)
                SYSTEM_PULLREQUEST_PULLREQUESTNUMBER: $(System.PullRequest.PullRequestNumber)
