# Template for APIScan stage

parameters:
- name: prepareSteps
  type: stepList
  default: []
- name: postSteps
  type: stepList
  default: []
- name: pool
  type: object
- name: dependsOnStage
  type: object
  default: []

stages:
- stage: APIScan
  displayName: Run APIScan
  dependsOn: ${{ parameters.dependsOnStage }}
  jobs:
  - job: api_scan
    displayName: APIScan Job
    pool: ${{ parameters.pool }}
    templateContext:
      type: releaseJob
      isProduction: true
      inputs:
      - input: pipelineArtifact
        artifactName: APIScanFiles
        targetPath: $(Agent.TempDirectory)/APIScanFiles
    steps:
    - ${{ each step in parameters.prepareSteps }}:
      - ${{ each pair in step }}:
          ${{ pair.key }}: ${{ pair.value }}

    - task: APIScan@2
      displayName: Run APIScan
      inputs:
        softwareFolder: '$(Agent.TempDirectory)/APIScanFiles'
        softwareName: 'MAUI'
        softwareVersionNum: '9.0'
        softwareBuildNum: '$(Build.BuildId)'
        azureSubscription: 'dotnet-apiscan'
      env:
        AzureServicesAuthConnectionString: RunAs=App;AppId=$(AppId);TenantId=$(TenantId);ServiceConnectionId=$(ServiceConnectionId);
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)

    - task: PublishSecurityAnalysisLogs@3
      displayName: Publishing analysis artifacts
      inputs:
        ArtifactName: 'CodeAnalysisLogs'
        ArtifactType: 'Container'
        AllTools: true
        ToolLogsNotFoundAction: 'Standard'

    - ${{ each step in parameters.postSteps }}:
      - ${{ each pair in step }}:
          ${{ pair.key }}: ${{ pair.value }}
