# Template for devicetests on dnceng
parameters:
- name: prepareSteps
  type: stepList
  default: []
- name: postSteps
  type: stepList
  default: []
- name: pool
  type: object
- name: enableSourceBuild
  type: boolean
  default: false
- name: enableSourceIndex
  type: boolean
  default: false
- name: sourceIndexParams
  type: object
  default: []
- name: runAsPublic
  type: boolean
  default: true
- name: androidPool
  type: object
- name: iosPool
  type: object
- name: catalystPool
  type: object
- name: windowsPool
  type: object
  default: 'dotnet'
- name: iosVersions
  type: object
  default: [ 'latest' ]
- name: iosDeviceVersions
  type: object
  default: [ '15' ]
- name: androidApiLevels
  type: object
  default: [ 33 ]
- name: catalystVersions
  type: object
  default: [ 'latest' ]
- name: helixProject
  type: string
  default: 'eng/helix_xharness.proj'
- name: extraHelixArguments
  type: string
  default: ''
- name: BuildConfiguration
  type: string
  default: 'Debug'
- name: TargetFrameworkVersion
  type: string
  default: 'net9.0'

stages:
- stage: deviceTests_ios_android_${{ parameters.TargetFrameworkVersion }}
  displayName: ${{ parameters.TargetFrameworkVersion }} ios/android Helix Tests
  dependsOn: []
  jobs:
  - template: ${{ iif(eq(parameters.runAsPublic, 'true'), '/eng/common/templates/jobs/jobs.yml', '/eng/common/templates-official/jobs/jobs.yml@self') }}
    parameters:
      helixRepo: dotnet/maui
      pool: ${{ parameters.iosPool }}
      enableMicrobuild: true
      enablePublishUsingPipelines: true
      enablePublishBuildAssets: true
      enableTelemetry: true
      enableSourceBuild: ${{ parameters.enableSourceBuild }}
      enableSourceIndex: ${{ parameters.enableSourceIndex }}
      sourceIndexParams: ${{ parameters.sourceIndexParams }}
      publishAssetsImmediately: true
      enablePublishBuildArtifacts: true
      enablePublishTestResults: true
      workspace:
        clean: all
      jobs:
      - job: device_tests_ios
        displayName: DeviceTests iOS
        timeoutInMinutes: 240
        variables:
        - name: _BuildConfig
          value: ${{ parameters.BuildConfiguration }}
        preSteps:
        - checkout: self
          fetchDepth: 1
          clean: true

        steps:
        - ${{ each step in parameters.prepareSteps }}:
          - ${{ each pair in step }}:
              ${{ pair.key }}: ${{ pair.value }}

        # Run on public pipeline
        - ${{ if parameters.runAsPublic }}:
          - script: $(_buildScriptMacOS) -restore -build -configuration $(_BuildConfig) -projects '$(Build.SourcesDirectory)/Microsoft.Maui.BuildTasks.slnf' /bl:BuildBuildTasks.binlog $(_OfficialBuildIdArgs)
            displayName: Build BuildTasks

          - script: $(_buildScriptMacOS) -restore -build -configuration $(_BuildConfig) /p:BuildDeviceTests=true /bl:BuildDeviceTests.binlog $(_OfficialBuildIdArgs)
            displayName: Build DeviceTests

          - template: /eng/common/templates-official/steps/send-to-helix.yml
            parameters:
              HelixProjectPath: ${{ parameters.helixProject }}
              HelixProjectArguments: /p:TargetOS=ios /p:TestRunNameSuffix="_$(_BuildConfig)" /p:TestRunNamePrefix="DeviceTestsIOS_"
              HelixConfiguration: $(_BuildConfig)
              IncludeDotNetCli: true
              DisplayNamePrefix: DeviceTestsIOS

      - job: device_tests_android
        displayName: DeviceTests Android
        timeoutInMinutes: 240
        variables:
        - name: _BuildConfig
          value: ${{ parameters.BuildConfiguration }}
        preSteps:
        - checkout: self
          fetchDepth: 1
          clean: true

        steps:
        - ${{ each step in parameters.prepareSteps }}:
          - ${{ each pair in step }}:
              ${{ pair.key }}: ${{ pair.value }}

        # Run on public pipeline
        - ${{ if parameters.runAsPublic }}:
          - script: $(_buildScriptMacOS) -restore -build -configuration $(_BuildConfig) -projects '$(Build.SourcesDirectory)/Microsoft.Maui.BuildTasks.slnf' /bl:buidltasks.binlog $(_OfficialBuildIdArgs)
            displayName: Build BuildTasks

          - script: $(_buildScriptMacOS) -restore -build -configuration $(_BuildConfig) /p:BuildDeviceTests=true /bl:BuildDeviceTests.binlog $(_OfficialBuildIdArgs)
            displayName: Build DeviceTests

          - template: /eng/common/templates-official/steps/send-to-helix.yml
            parameters:
              HelixProjectPath: ${{ parameters.helixProject }}
              HelixProjectArguments: /p:TargetOS=android /p:TestRunNameSuffix="_$(_BuildConfig)" /p:TestRunNamePrefix="DeviceTestsAndroid_"
              HelixConfiguration: $(_BuildConfig)
              IncludeDotNetCli: true
              DisplayNamePrefix: DeviceTestsAndroid
