# Template for running tests on Helix on dnceng
parameters:
- name: prepareSteps
  type: stepList
  default: []
- name: postSteps
  type: stepList
  default: []
- name: enableSourceBuild
  type: boolean
  default: false
- name: enableSourceIndex
  type: boolean
  default: false
- name: sourceIndexParams
  type: object
  default: []
- name: runAsPublic
  type: boolean
  default: true
- name: buildPlatforms
  type: object
  default:
  - name: NetCore-Public
    image: 1es-windows-2022
    os: Windows
    buildScript: $(_helixScript)
    sln: $(buildProjects)
  - name: Azure Pipelines
    vmImage: $(HostedMacImage)
    os: macOS
    buildScript: $(_helixScriptMacOS)
    sln: $(buildProjectsMac)

stages:
- stage: HelixTests
  displayName: Run Helix Unit Tests
  dependsOn: []
  jobs:
  - template: /eng/common/templates-official/jobs/jobs.yml
    parameters:
      helixRepo: dotnet/maui
      pool:
        name: NetCore-Public
        vmImage: 1es-windows-2022
        os: windows
      enableMicrobuild: true
      enablePublishUsingPipelines: true
      enablePublishBuildAssets: true
      enableTelemetry: true
      enableSourceBuild: ${{ parameters.enableSourceBuild }}
      enableSourceIndex: ${{ parameters.enableSourceIndex }}
      sourceIndexParams: ${{ parameters.sourceIndexParams }}
      publishAssetsImmediately: true
      enablePublishBuildArtifacts: true
      enablePublishTestResults: true
      workspace:
        clean: all
      jobs:
      - job: test_helix_unit_tests
        displayName: Windows UnitTests
        timeoutInMinutes: 240
        steps:
        - ${{ each step in parameters.prepareSteps }}:
          - ${{ each pair in step }}:
              ${{ pair.key }}: ${{ pair.value }}

        - script: $(_buildScript) --restore
          displayName: Install .NET SDK and Workloads

        - script: $(_helixScriptMacOS)
          displayName: Run Unit Tests
