parameters:
  stageDependsOn: []
  jobMatrix: [] # Should define jobMatrix.name, jobMatrix.pool, jobMatrix.timeout, and either jobMatrix.testCategory OR jobMatrix.testName
  mauiSourcePath: $(Build.SourcesDirectory)
  buildConfig: Debug
  repoLogPath: $(Build.Arcade.LogsPath)
  publishTaskPrefix: '1ES.'
  integrationTestsProjects: '$(Build.SourcesDirectory)/src/TestUtils/src/Microsoft.Maui.IntegrationTests/Microsoft.Maui.IntegrationTests.csproj'

stages:
- stage: IntegrationTests
  displayName: Run Integration Tests
  dependsOn: ${{ parameters.stageDependsOn }}
  jobs:
  - ${{ each job in parameters.jobMatrix }}:
    - job: ${{ job.name }}
      displayName: ${{ coalesce(job.testName, job.testCategory) }} ${{ coalesce(job.pool.label, job.pool.os) }}
      pool: ${{ job.pool }}
      timeoutInMinutes: ${{ job.timeout }}
      ${{ if job.condition }}:
        condition: ${{ job.condition }}
      variables:
        # Build the filter based on whether testName or testCategory is provided
        ${{ if job.testName }}:
          testFilter: 'Name=${{ job.testName }}'
          testIdentifier: ${{ job.testName }}
        ${{ else }}:
          testFilter: 'Category=${{ job.testCategory }}'
          testIdentifier: ${{ job.testCategory }}
      steps:
      - script: ${{ job.buildScript }} -test -configuration ${{ parameters.buildConfig  }} -projects "${{ parameters.integrationTestsProjects }}" --filter "$(testFilter)" --logger trx --results-directory $(Agent.TempDirectory)/Microsoft.Maui.IntegrationTests /p:ProivioningMauiPacks=true /p:ArchiveTests=false /p:TreatWarningsAsErrors=$(TreatWarningsAsErrors) /bl:$(Build.Arcade.LogsPath)${{ parameters.buildConfig }}/buildtasks_os.binlog $(_OfficialBuildIdArgs)
        displayName: 🛠️ Run Integration Tests - $(testIdentifier) ${{ job.pool.os }}
        # Set IOS_TEST_DEVICE for all iOS-related tests (RunOniOS and RunOniOS_*)
        ${{ if or(eq(job.testCategory, 'RunOniOS'), startsWith(job.testName, 'RunOniOS')) }}:
          env:
            IOS_TEST_DEVICE: ios-simulator-64_18.5

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: VSTest
          testResultsFiles: '$(Agent.TempDirectory)/Microsoft.Maui.IntegrationTests/**/*.trx'
          testRunTitle: Integration Tests - $(testIdentifier) ${{ coalesce(job.pool.label, job.pool.os) }}
          failTaskOnMissingResultsFile: true
        condition: always()

      - task: ${{ parameters.publishTaskPrefix }}PublishPipelineArtifact@1
        displayName: Publish Logs
        inputs:
          targetPath: ${{ parameters.repoLogPath }}
          artifact: Logs - Integration Tests $(testIdentifier) ${{ coalesce(job.pool.label, job.pool.os) }} $(System.JobAttempt)
        condition: always()

      - template: /eng/pipelines/common/fail-on-issue.yml
        parameters:
          condition: always()
