parameters:
  jobMatrix: [] # Should define jobMatrix.name, jobMatrix.displayName, jobMatrix.pool, jobMatrix.timeout, jobMatrix.testOS
  mauiSourcePath: $(Build.SourcesDirectory)
  buildConfig: Debug
  repoLogPath: $(Build.Arcade.LogsPath)
  publishTaskPrefix: '1ES.'

stages:
- stage: HelixTests
  displayName: Run Helix Unit Tests
  dependsOn: []
  jobs:
  - template: /eng/common/templates-official/jobs/jobs.yml
    parameters:
      helixRepo: dotnet/maui
      pool:
        name: Azure Pipelines
        vmImage: $(HostedMacImage)
        os: macOS
      enableMicrobuild: true
      enablePublishUsingPipelines: true
      enablePublishBuildAssets: true
      enableTelemetry: true
      enableSourceBuild: ${{ parameters.enableSourceBuild }}
      enableSourceIndex: ${{ parameters.enableSourceIndex }}
      sourceIndexParams: ${{ parameters.sourceIndexParams }}
      publishAssetsImmediately: true
      enablePublishBuildArtifacts: true
      enablePublishTestResults: true
      workspace:
        clean: all
      jobs:
      - job: test_helix_unit_tests
        displayName: Helix UnitTests
        timeoutInMinutes: 240
        steps:
        - script: $(_buildScriptMacOS) --nodeReuse false --restore
          displayName: Install .NET SDK and Workloads
        - script: $(_helixScriptMacOS)
          displayName: Run Unit Tests
