parameters:
  stageDependsOn: []
  jobMatrix: [] # Should define jobMatrix.name, jobMatrix.pool, jobMatrix.timeout, and either jobMatrix.testCategory OR jobMatrix.testName
  mauiSourcePath: $(Build.SourcesDirectory)
  buildConfig: Debug
  repoLogPath: $(Build.Arcade.LogsPath)
  publishTaskPrefix: '1ES.'

stages:
- stage: IntegrationTests
  displayName: Run Integration Tests
  dependsOn: ${{ parameters.stageDependsOn }}
  jobs:
  - ${{ each job in parameters.jobMatrix }}:
    - job: ${{ job.name }}
      displayName: ${{ coalesce(job.testName, job.testCategory) }} ${{ coalesce(job.pool.label, job.pool.os) }}
      pool: ${{ job.pool }}
      timeoutInMinutes: ${{ job.timeout }}
      ${{ if job.condition }}:
        condition: ${{ job.condition }}
      variables:
        # Build the filter based on whether testName or testCategory is provided
        # XUnit filter syntax: FullyQualifiedName~ for name matching, Category= for traits
        ${{ if job.testName }}:
          testFilter: 'FullyQualifiedName~${{ job.testName }}'
          testIdentifier: ${{ job.testName }}
        ${{ else }}:
          testFilter: 'Category=${{ job.testCategory }}'
          testIdentifier: ${{ job.testCategory }}
      steps:
      - template: /eng/pipelines/arcade/setup-test-env.yml
        parameters:
          mauiSourcePath: ${{ parameters.mauiSourcePath }}
          buildConfig: ${{ parameters.buildConfig }}
          repoLogPath: ${{ parameters.repoLogPath }}

      - template: /eng/pipelines/common/run-dotnet-preview.yml
        parameters:
          displayName: Run Integration Tests - $(testIdentifier) ${{ job.pool.os }}
          mauiSourcePath: ${{ parameters.mauiSourcePath }}
          command: test
          project: ${{ parameters.mauiSourcePath }}/src/TestUtils/src/Microsoft.Maui.IntegrationTests/Microsoft.Maui.IntegrationTests.csproj
          arguments: '-c ${{ parameters.buildConfig }} --filter "$(testFilter)" --logger trx --results-directory $(Agent.TempDirectory)/Microsoft.Maui.IntegrationTests'
          useExitCodeForErrors: true
          retryCountOnTaskFailure: 1
          # Set IOS_TEST_DEVICE for all iOS-related tests (RunOniOS and RunOniOS_*)
          ${{ if or(eq(job.testCategory, 'RunOniOS'), startsWith(job.testName, 'RunOniOS')) }}:
            envVariables:
              IOS_TEST_DEVICE: ios-simulator-64_26.0

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: VSTest
          testResultsFiles: '$(Agent.TempDirectory)/Microsoft.Maui.IntegrationTests/**/*.trx'
          testRunTitle: Integration Tests - $(testIdentifier) ${{ coalesce(job.pool.label, job.pool.os) }}
          failTaskOnMissingResultsFile: true
        condition: always()

      - task: ${{ parameters.publishTaskPrefix }}PublishPipelineArtifact@1
        displayName: Publish Logs
        inputs:
          targetPath: ${{ parameters.repoLogPath }}
          artifact: Logs - Integration Tests $(testIdentifier) ${{ coalesce(job.pool.label, job.pool.os) }} $(System.JobAttempt)
        condition: always()

      - template: /eng/pipelines/common/fail-on-issue.yml
        parameters:
          condition: always()
