// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.IO.Compression;
using System.Reflection;
using System.Reflection.Metadata;
using System.Reflection.Metadata.Ecma335;
using System.Reflection.PortableExecutable;

namespace Microsoft.Maui.Controls.Build.Tasks;

/// <summary>
/// Generates a MIBC (Managed Instrumented Binary Code) profile file that lists all
/// InitializeComponent* methods found in one or more input assemblies. MIBC files are
/// consumed by crossgen2 and the .NET AOT compiler to guide profile-guided optimization.
///
/// The MAUI XAML processing pipeline generates several variants of InitializeComponent:
///   - InitializeComponent         — the primary entry point (all inflator modes)
///   - InitializeComponentRuntime  — runtime XAML inflation via LoadFromXaml (switch mode / HotReload fallback)
///   - InitializeComponentXamlC    — XamlC IL-compiled XAML inflation (switch mode)
///   - InitializeComponentSourceGen — source-generator compiled XAML inflation (switch mode)
/// All of these are included in the generated MIBC profile.
/// </summary>
static class MibcProfileGenerator
{
	/// <summary>
	/// Method names generated by the MAUI XAML toolchain.
	/// See CodeBehindCodeWriter.cs and XamlCTask.cs for where these names are produced.
	/// Matched by exact name (not prefix).
	/// </summary>
	static readonly string[] InitializeComponentMethodNames =
	[
		"InitializeComponent",
		"InitializeComponentRuntime",
		"InitializeComponentXamlC",
		"InitializeComponentSourceGen",
	];

	static int Main(string[] args)
	{
		if (args.Length < 2)
		{
			Console.Error.WriteLine("Usage: MibcProfileGenerator <output.mibc> <input.dll> [<input2.dll> ...]");
			Console.Error.WriteLine("       MibcProfileGenerator <output.mibc> @<responsefile>");
			Console.Error.WriteLine();
			Console.Error.WriteLine("Scans input assemblies for InitializeComponent* methods and produces");
			Console.Error.WriteLine("a MIBC profile file that can be consumed by crossgen2 (--mibc) or");
			Console.Error.WriteLine("validated with 'dotnet pgo dump <output.mibc>'.");
			Console.Error.WriteLine();
			Console.Error.WriteLine("A response file (@file) should contain one assembly path per line.");
			Console.Error.WriteLine();
			Console.Error.WriteLine("Matched method names:");
			foreach (var name in InitializeComponentMethodNames)
				Console.Error.WriteLine($"  - {name}");
			return 1;
		}

		string outputPath = args[0];
		var inputPaths = ExpandResponseFiles(args.Skip(1));
		bool uncompressed = string.Equals(Path.GetExtension(outputPath), ".dll", StringComparison.OrdinalIgnoreCase);

		if (inputPaths.Count == 0)
		{
			Console.Error.WriteLine("Error: No input assemblies specified.");
			return 1;
		}

		var methods = new List<DiscoveredMethod>();

		foreach (string inputPath in inputPaths)
		{
			if (!File.Exists(inputPath))
			{
				Console.Error.WriteLine($"Error: Input file not found: {inputPath}");
				return 1;
			}

			try
			{
				var discovered = DiscoverInitializeComponentMethods(inputPath);
				methods.AddRange(discovered);
				Console.WriteLine($"Found {discovered.Count} InitializeComponent* method(s) in {Path.GetFileName(inputPath)}");
			}
			catch (Exception ex)
			{
				Console.Error.WriteLine($"Error reading {inputPath}: {ex.Message}");
				return 1;
			}
		}

		if (methods.Count == 0)
		{
			Console.Error.WriteLine("Warning: No InitializeComponent* methods found in any input assembly.");
		}

		Console.WriteLine($"Total: {methods.Count} method(s) to emit into MIBC profile.");

		try
		{
			EmitMibcFile(outputPath, methods, uncompressed);
			Console.WriteLine($"Successfully wrote MIBC profile to {outputPath}");
		}
		catch (Exception ex)
		{
			Console.Error.WriteLine($"Error writing MIBC file: {ex.Message}");
			return 1;
		}

		return 0;
	}

	/// <summary>
	/// Expands arguments, treating any argument starting with '@' as a response file
	/// containing one assembly path per line. Non-response-file arguments are passed through.
	/// </summary>
	static List<string> ExpandResponseFiles(IEnumerable<string> args)
	{
		var result = new List<string>();
		foreach (var arg in args)
		{
			if (arg.StartsWith('@'))
			{
				string responseFile = arg.Substring(1);
				if (!File.Exists(responseFile))
				{
					Console.Error.WriteLine($"Error: Response file not found: {responseFile}");
					continue;
				}

				foreach (var line in File.ReadAllLines(responseFile))
				{
					var trimmed = line.Trim();
					if (trimmed.Length > 0 && !trimmed.StartsWith('#'))
						result.Add(trimmed);
				}
			}
			else
			{
				result.Add(arg);
			}
		}
		return result;
	}

	/// <summary>
	/// Represents a method discovered in an input assembly that should be included in the MIBC profile.
	/// </summary>
	sealed record DiscoveredMethod(
		string AssemblyName,
		Version? AssemblyVersion,
		byte[]? PublicKeyToken,
		string Namespace,
		string TypeName,
		string MethodName,
		byte[] Signature);

	/// <summary>
	/// Scans an assembly for all InitializeComponent* methods generated by the MAUI XAML toolchain.
	/// </summary>
	static List<DiscoveredMethod> DiscoverInitializeComponentMethods(string assemblyPath)
	{
		var results = new List<DiscoveredMethod>();
		var matchedNames = new HashSet<string>(InitializeComponentMethodNames);

		using var stream = File.OpenRead(assemblyPath);
		using var peReader = new PEReader(stream);
		var mdReader = peReader.GetMetadataReader();

		// Get assembly identity
		var assemblyDef = mdReader.GetAssemblyDefinition();
		string asmName = mdReader.GetString(assemblyDef.Name);
		Version? asmVersion = assemblyDef.Version;
		byte[]? publicKeyToken = GetPublicKeyToken(mdReader, assemblyDef);

		foreach (var typeHandle in mdReader.TypeDefinitions)
		{
			var typeDef = mdReader.GetTypeDefinition(typeHandle);
			string typeName = mdReader.GetString(typeDef.Name);

			// In ECMA-335, nested types have an empty Namespace; only the outermost
			// declaring type carries the real namespace. Walk up to find it.
			string ns = GetDeclaringNamespace(mdReader, typeDef);

			// Handle nested types: walk up to build the full name with '/' separators
			string fullTypeName = BuildFullTypeName(mdReader, typeDef, typeName);

			foreach (var methodHandle in typeDef.GetMethods())
			{
				var methodDef = mdReader.GetMethodDefinition(methodHandle);
				string methodName = mdReader.GetString(methodDef.Name);

				if (!matchedNames.Contains(methodName))
					continue;

				// Read the raw signature blob
				var sigBlob = mdReader.GetBlobBytes(methodDef.Signature);

				results.Add(new DiscoveredMethod(
					asmName,
					asmVersion,
					publicKeyToken,
					ns,
					fullTypeName,
					methodName,
					sigBlob));
			}
		}

		return results;
	}

	/// <summary>
	/// Gets the namespace for a type, walking up to the outermost declaring type for nested types.
	/// In ECMA-335 metadata, nested TypeDefs have an empty Namespace field.
	/// </summary>
	static string GetDeclaringNamespace(MetadataReader mdReader, TypeDefinition typeDef)
	{
		var current = typeDef;
		while (current.IsNested)
		{
			current = mdReader.GetTypeDefinition(current.GetDeclaringType());
		}
		return mdReader.GetString(current.Namespace);
	}

	/// <summary>
	/// Builds the full type name including enclosing types for nested types, using '/' as separator.
	/// </summary>
	static string BuildFullTypeName(MetadataReader mdReader, TypeDefinition typeDef, string simpleName)
	{
		if (!typeDef.IsNested)
			return simpleName;

		var parts = new Stack<string>();
		parts.Push(simpleName);

		var current = typeDef;
		while (current.IsNested)
		{
			var declaringHandle = current.GetDeclaringType();
			current = mdReader.GetTypeDefinition(declaringHandle);
			parts.Push(mdReader.GetString(current.Name));
		}

		return string.Join("/", parts);
	}

	/// <summary>
	/// Extracts the public key token from an assembly definition.
	/// </summary>
	static byte[]? GetPublicKeyToken(MetadataReader mdReader, AssemblyDefinition asmDef)
	{
		if (asmDef.PublicKey.IsNil)
			return null;

		byte[] publicKey = mdReader.GetBlobBytes(asmDef.PublicKey);
		if (publicKey.Length == 0)
			return null;

		// If this is a full public key, convert to token via AssemblyName
		if (publicKey.Length > 8)
		{
			var an = new AssemblyName();
			an.SetPublicKey(publicKey);
			return an.GetPublicKeyToken();
		}

		return publicKey;
	}

	/// <summary>
	/// Emits a MIBC profile file in the standard format expected by crossgen2 / dotnet-pgo.
	///
	/// The MIBC format is a PE assembly containing:
	///   1. A global method "AssemblyDictionary" that indexes groups by assembly name
	///   2. Per-assembly group methods that list profiled methods via ldtoken instructions
	///
	/// For each profiled method the group method contains:
	///   ldtoken [MemberRef for the method]
	///   pop
	/// </summary>
	static void EmitMibcFile(string outputPath, List<DiscoveredMethod> methods, bool uncompressed)
	{
		string assemblyName = Path.GetFileNameWithoutExtension(outputPath);

		var mdBuilder = new MetadataBuilder();
		var ilBuilder = new BlobBuilder();
		var methodBodyStream = new MethodBodyStreamEncoder(ilBuilder);

		// Module and assembly definition
		var mvidBlob = mdBuilder.ReserveGuid();
		mdBuilder.AddModule(
			0,
			mdBuilder.GetOrAddString(assemblyName),
			mvidBlob.Handle,
			default, default);

		mdBuilder.AddAssembly(
			mdBuilder.GetOrAddString(assemblyName),
			new Version(1, 0, 0, 0),
			default,
			default,
			default,
			AssemblyHashAlgorithm.None);

		// <Module> type definition (required for global methods)
		mdBuilder.AddTypeDefinition(
			default,
			default,
			mdBuilder.GetOrAddString("<Module>"),
			baseType: default,
			fieldList: MetadataTokens.FieldDefinitionHandle(1),
			methodList: MetadataTokens.MethodDefinitionHandle(1));

		// Build the void() static method signature for global methods
		var staticVoidSigBlob = new BlobBuilder();
		new BlobEncoder(staticVoidSigBlob)
			.MethodSignature(isInstanceMethod: false)
			.Parameters(0, r => r.Void(), _ => { });
		var staticVoidSigHandle = mdBuilder.GetOrAddBlob(staticVoidSigBlob);

		// Cache of assembly references keyed by full identity to avoid duplicates
		var assemblyRefCache = new Dictionary<string, AssemblyReferenceHandle>();

		// Cache of type references
		var typeRefCache = new Dictionary<string, TypeReferenceHandle>();

		// Create MemberRefs for all discovered methods and group by full assembly identity
		var groupedByAssembly = methods.GroupBy(m => GetAssemblyIdentityKey(m)).OrderBy(g => g.Key);
		var groupMethods = new List<(string GroupName, MethodDefinitionHandle Handle)>();

		int groupIndex = 0;
		foreach (var group in groupedByAssembly)
		{
			groupIndex++;
			string simpleAsmName = group.First().AssemblyName;
			string groupName = simpleAsmName + ";";

			// Emit one group method body with ldtoken/pop for each method
			var groupIlBuf = new BlobBuilder();
			var groupIl = new InstructionEncoder(groupIlBuf);

			foreach (var method in group)
			{
				// Ensure assembly reference exists, keyed by full identity
				string asmIdentityKey = GetAssemblyIdentityKey(method);
				if (!assemblyRefCache.TryGetValue(asmIdentityKey, out var asmRef))
				{
					AssemblyFlags flags = default;
					BlobHandle pktBlob = default;
					if (method.PublicKeyToken is { Length: > 0 })
					{
						pktBlob = mdBuilder.GetOrAddBlob(method.PublicKeyToken);
					}

					asmRef = mdBuilder.AddAssemblyReference(
						mdBuilder.GetOrAddString(method.AssemblyName),
						method.AssemblyVersion ?? new Version(0, 0, 0, 0),
						default,
						pktBlob,
						flags,
						default);
					assemblyRefCache[asmIdentityKey] = asmRef;
				}

				// Build type reference (handle nested types)
				var typeRef = GetOrAddTypeRef(mdBuilder, typeRefCache, asmRef, method.Namespace, method.TypeName);

				// Create MemberRef for the method with its original signature
				var memberRef = mdBuilder.AddMemberReference(
					typeRef,
					mdBuilder.GetOrAddString(method.MethodName),
					mdBuilder.GetOrAddBlob(method.Signature));

				// Emit: ldtoken <method>, pop
				groupIl.OpCode(ILOpCode.Ldtoken);
				groupIl.Token(memberRef);
				groupIl.OpCode(ILOpCode.Pop);
			}

			groupIl.OpCode(ILOpCode.Ret);

			// Add the group method as a global method
			int bodyOffset = methodBodyStream.AddMethodBody(groupIl, maxStack: 8);
			string methodName = $"Assemblies_{simpleAsmName}_{groupIndex}";
			var groupMethodHandle = mdBuilder.AddMethodDefinition(
				MethodAttributes.Public | MethodAttributes.Static,
				MethodImplAttributes.IL,
				mdBuilder.GetOrAddString(methodName),
				staticVoidSigHandle,
				bodyOffset,
				default);

			groupMethods.Add((groupName, groupMethodHandle));
		}

		// Emit AssemblyDictionary global method
		var dictIlBuf = new BlobBuilder();
		var dictIl = new InstructionEncoder(dictIlBuf);

		foreach (var (groupName, groupMethodHandle) in groupMethods)
		{
			dictIl.LoadString(mdBuilder.GetOrAddUserString(groupName));
			dictIl.OpCode(ILOpCode.Ldtoken);
			dictIl.Token(groupMethodHandle);
			dictIl.OpCode(ILOpCode.Pop);
		}

		dictIl.OpCode(ILOpCode.Ret);

		int dictBodyOffset = methodBodyStream.AddMethodBody(dictIl, maxStack: 8);
		mdBuilder.AddMethodDefinition(
			MethodAttributes.Public | MethodAttributes.Static,
			MethodImplAttributes.IL,
			mdBuilder.GetOrAddString("AssemblyDictionary"),
			staticVoidSigHandle,
			dictBodyOffset,
			default);

		// Write the MVID before serializing so it's included in the PE output
		new BlobWriter(mvidBlob.Content).WriteGuid(
			new Guid("97F4DBD4-F6D1-4FAD-91B3-1001F92068E5"));

		// Serialize to PE
		var peBuilder = new ManagedPEBuilder(
			new PEHeaderBuilder(),
			new MetadataRootBuilder(mdBuilder),
			ilBuilder,
			deterministicIdProvider: content => new BlobContentId(
				new Guid("97F4DBD4-F6D1-4FAD-91B3-1001F92068E5"), 0x04030201));

		var peBlob = new BlobBuilder();
		peBuilder.Serialize(peBlob);

		// Write output
		if (uncompressed)
		{
			using var fs = new FileStream(outputPath, FileMode.Create);
			peBlob.WriteContentTo(fs);
		}
		else
		{
			using var zip = ZipFile.Open(outputPath, ZipArchiveMode.Create);
			var entry = zip.CreateEntry(Path.GetFileName(outputPath) + ".dll", CompressionLevel.Optimal);
			using var entryStream = entry.Open();
			peBlob.WriteContentTo(entryStream);
		}
	}

	/// <summary>
	/// Gets or creates a TypeReference handle, handling nested types (separated by '/').
	/// </summary>
	static TypeReferenceHandle GetOrAddTypeRef(
		MetadataBuilder mdBuilder,
		Dictionary<string, TypeReferenceHandle> cache,
		AssemblyReferenceHandle asmRef,
		string ns,
		string typeName)
	{
		string cacheKey = $"{MetadataTokens.GetToken(asmRef):X}:{ns}.{typeName}";
		if (cache.TryGetValue(cacheKey, out var existing))
			return existing;

		// Handle nested types: "Outer/Inner" -> TypeRef for Outer, then nested TypeRef for Inner
		string[] parts = typeName.Split('/');
		TypeReferenceHandle parentTypeRef = default;

		for (int i = 0; i < parts.Length; i++)
		{
			string partName = parts[i];
			string partKey;

			if (i == 0)
			{
				partKey = $"{MetadataTokens.GetToken(asmRef):X}:{ns}.{partName}";
				if (!cache.TryGetValue(partKey, out parentTypeRef))
				{
					parentTypeRef = mdBuilder.AddTypeReference(
						asmRef,
						mdBuilder.GetOrAddString(ns),
						mdBuilder.GetOrAddString(partName));
					cache[partKey] = parentTypeRef;
				}
			}
			else
			{
				partKey = $"{MetadataTokens.GetToken(parentTypeRef):X}/{partName}";
				if (!cache.TryGetValue(partKey, out var nestedRef))
				{
					nestedRef = mdBuilder.AddTypeReference(
						parentTypeRef,
						default,
						mdBuilder.GetOrAddString(partName));
					cache[partKey] = nestedRef;
				}
				parentTypeRef = nestedRef;
			}
		}

		cache[cacheKey] = parentTypeRef;
		return parentTypeRef;
	}

	/// <summary>
	/// Builds a unique key from the full assembly identity (name + version + public key token)
	/// to correctly distinguish assemblies that share the same simple name.
	/// </summary>
	static string GetAssemblyIdentityKey(DiscoveredMethod method)
	{
		string version = method.AssemblyVersion?.ToString() ?? "0.0.0.0";
		string pkt = method.PublicKeyToken is { Length: > 0 }
			? Convert.ToHexString(method.PublicKeyToken).ToLowerInvariant()
			: "null";
		return $"{method.AssemblyName}, Version={version}, PublicKeyToken={pkt}";
	}
}
