<Project>

  <ItemGroup>
    <ProjectCapability Include="Maui" />
    <ProjectCapability Include="MauiAssets" />
    <ProjectCapability Include="MauiBlazor" />
    <ProjectCapability Include="MauiCore" />
    <ProjectCapability Include="MauiEssentials" />
  </ItemGroup>

  <ItemGroup>
    <ProjectCapability Include="MauiRepository" />
    <ProjectCapability Include="MauiRepositorySampleProject" Condition="'$(SampleProject)' == 'true'" />
  </ItemGroup>

  <PropertyGroup>
    <_MauiCoreBuildTasksTargets>$(_MauiBuildTasksLocation)Microsoft.Maui.Core.targets</_MauiCoreBuildTasksTargets>
    <_MauiCoreBuildTasksTargets Condition="'$(_MauiTargetPlatformIsWindows)' == 'true'">$(_MauiBuildTasksLocation)net$(_MauiMinimumSupportedDotNetTfm)-windows$(MinimumWindowsTargetFrameworkVersion)\Microsoft.Maui.Core.targets</_MauiCoreBuildTasksTargets>
    <_MauiControlsBuildTasksTargets>$(_MauiBuildTasksLocation)Microsoft.Maui.Controls.Build.Tasks.targets</_MauiControlsBuildTasksTargets>
    <_MauiControlsBuildTasksTargets Condition="'$(_MauiTargetPlatformIsiOS)' == 'true'">$(_MauiBuildTasksLocation)net6.0-ios10.0\Microsoft.Maui.Controls.Build.Tasks.targets</_MauiControlsBuildTasksTargets>
    <_MauiControlsBuildTasksTargets Condition="'$(_MauiTargetPlatformIsMacCatalyst)' == 'true'">$(_MauiBuildTasksLocation)net6.0-maccatalyst13.1\Microsoft.Maui.Controls.Build.Tasks.targets</_MauiControlsBuildTasksTargets>
    <_MauiControlsBuildTasksTargets Condition="'$(_MauiTargetPlatformIsWindows)' == 'true'">$(_MauiBuildTasksLocation)net6.0-windows10.0.17763.0\Microsoft.Maui.Controls.Build.Tasks.targets</_MauiControlsBuildTasksTargets>
    <_MauiCoreAfterBuildTasksTargets>$(_MauiBuildTasksLocation)Microsoft.Maui.Core.After.targets</_MauiCoreAfterBuildTasksTargets>
    <_MauiResizetizerBuildTasksTargets>$(_MauiBuildTasksLocation)Microsoft.Maui.Resizetizer.targets</_MauiResizetizerBuildTasksTargets>
    <_MauiBuildTasksTargetsReady Condition="Exists('$(_MauiCoreBuildTasksTargets)') and Exists('$(_MauiControlsBuildTasksTargets)') and Exists('$(_MauiCoreAfterBuildTasksTargets)') and Exists('$(_MauiResizetizerBuildTasksTargets)') and Exists('$(_MauiBuildTasksLocation)Microsoft.Maui.Controls.Build.Tasks.dll') and Exists('$(_MauiBuildTasksLocation)Microsoft.Maui.Resizetizer.dll')">true</_MauiBuildTasksTargetsReady>
  </PropertyGroup>

  <ImportGroup Condition="'$(_MauiBuildTasksPropsReady)' == 'true' and '$(_MauiBuildTasksTargetsReady)' == 'true'">

    <!-- Microsoft.Maui.Core.targets -->
    <Import Project="$(_MauiCoreBuildTasksTargets)" />

    <!-- Microsoft.Maui.Controls.Build.Tasks.targets -->
    <Import Project="$(_MauiControlsBuildTasksTargets)" />

    <!-- Microsoft.Maui.Resizetizer.targets -->
    <Import Project="$(_MauiResizetizerBuildTasksTargets)" />

  </ImportGroup>

  <Target Name="VerifyMauiBuildTasksBuilt" BeforeTargets="_CheckForInvalidConfigurationAndPlatform">
    <Error Condition="'$(_MauiBuildTasksPropsReady)' != 'true' or '$(_MauiBuildTasksTargetsReady)' != 'true'"
           Text="We have detected that the required MSBuild tasks are not yet built or they are out of date. (Expand to see more info) 
You will need to exit Visual Studio and wait for it to completely close. 
After the process has ended, run the build command on the CLI with the .NET MAUI repository as the working directory:
    dotnet build Microsoft.Maui.BuildTasks.slnf
You can also start Visual Studio using the cake script:
    dotnet cake --target VS --workloads global
For best results, each time you rebase, merge from main or checkout a different branch, rebuild the build tasks." />
  </Target>

</Project>
