<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>release</AssemblyName>
    <RootNamespace>DotNet.Release.Cli</RootNamespace>
    <IsPackable>false</IsPackable>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotNet.Release.Core\DotNet.Release.Core.csproj" />
    <ProjectReference Include="..\DotNet.Release.Maestro\DotNet.Release.Maestro.csproj" />
    <ProjectReference Include="..\DotNet.Release.NuGet\DotNet.Release.NuGet.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="$(SystemCommandLinePackageVersion)" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DotNet.Release.Cli.Tests" />
  </ItemGroup>

</Project>
