name: "Triage: Apply Labels"
on:
  pull_request:
    types: [reopened, synchronize, opened]
  # issues:
  #   types: [opened, edited]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to triage'
        required: true
        type: number

permissions:
  contents: read
  issues: read
  models: read

jobs:
  triage-issue:
    name: Apply Labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine PLATFORM label for the issue
        id: triage-platform
        uses: ./.github/actions/triage
        with:
          issue: ${{ github.event_name == 'workflow_dispatch' && inputs.issue_number || '29673' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          label-prefix: 'platform/'
          mode: 'multi-label'

      - name: Determine AREA label for the issue
        id: triage-area
        uses: ./.github/actions/triage
        with:
          issue: ${{ github.event_name == 'workflow_dispatch' && inputs.issue_number || '29673' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          label-prefix: 'area-'
          mode: 'single-label'

      - name: Determine REGRESSION label for the issue
        id: triage-regression
        uses: ./.github/actions/triage
        with:
          issue: ${{ github.event_name == 'workflow_dispatch' && inputs.issue_number || '29673' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          label: 'potential-regression'
          mode: 'regression'

      - name: Log Labels
        run: |
          cat "${{ steps.triage-platform.outputs.labels-file }}"
          cat "${{ steps.triage-area.outputs.labels-file }}"
          cat "${{ steps.triage-regression.outputs.labels-file }}"
