name: "Copilot Setup Steps"

on: workflow_dispatch

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Run a pre-work build
        shell: pwsh
        continue-on-error: true
        run: .\build.ps1

      - name: Add the local .NET to the envvars (PATH, DOTNET_ROOT)
        shell: bash
        run: |
          echo "$GITHUB_WORKSPACE/bin/dotnet" >> "$GITHUB_PATH"
          echo "DOTNET_ROOT=$GITHUB_WORKSPACE/bin/dotnet" >> "$GITHUB_ENV"

          cat "$GITHUB_PATH"
          cat "$GITHUB_ENV"

      - name: Ensure we are using the correct .NET
        shell: pwsh
        run: |
          dotnet --version
          dotnet --info
          dotnet workload --info
