name: PR code format check
on: pull_request

# This action only need a single permission in order to autoformat the code.
permissions:
  contents: read
  
jobs:
  autoformat-code:
    name: code format check
    runs-on: ubuntu-latest

    steps:
    - name: 'Autoformat'
      uses: rolfbjarne/autoformat@v0.5
      with:
        script: 'dotnet format Microsoft.Maui.sln --no-restore --exclude Templates/src BlazorWebView/src/SharedSource/BlazorWebViewDeveloperTools.cs BlazorWebView/src/SharedSource/BlazorWebViewServiceCollectionExtensions.cs Graphics/src/Graphics.Win2D/W2DCanvas.cs Graphics/src/Graphics.Win2D/W2DExtensions.cs'
        onlyFilesModifiedInPullRequest: true
        git_commit_message: 'Auto-format source code'
